export const state = () => ({
  items: [
    {"Name":"Basilard","Class":"S.Sword","Description":"Basic short sword. Alucard assumes defensive stance if [Attack] is held.","Attack":1,"Speed":"Very quick","DMG":"CUT","Found":["Alchemy Laboratory"],"Dropped":["Bloody Zombie"],"Specials":[{"Type":1,"ATT":5,"Info":"Crossing Attack, Can be made in mid-air and can be downward changing [forward] for [down\/forward]."}]},
    {"Name":"Stone sword","Class":"S.Sword","Description":"May \"petrify\" enemies...","Attack":1,"Speed":"Normal","DMG":"CUT,STN","Dropped":["Gorgon"]},
    {"Name":"Short sword","Class":"S.Sword","Description":"Common short sword.","Attack":2,"Speed":"Normal","DMG":"CUT","Dropped":["Bone Scimitar"]},
    {"Name":"Holbein dagger","Class":"S.Sword","Description":"Swift upper diagonal attack.","Attack":6,"Speed":"Instantaneous","DMG":"CUT","Dropped":["Lesser Demon"]},
    {"Name":"Rapier","Class":"S.Sword","Description":"Long bladed sword.","Attack":7,"Speed":"Normal","DMG":"CUT","Dropped":["Dhuron","Sword Lord"],"Specials":[{"Type":2,"ATT":15,"Info":"Multiple Attacks."}]},
    {"Name":"Jewel sword","Class":"S.Sword","Description":"Transforms enemies into jewels.","Attack":15,"Speed":"Slow","DMG":"CUT","Found":["Entrance"],"Dropped":["Discus Lord"],"Specials":[{"Type":2,"ATT":15,"MP":5,"Info":"Materializes $1 coins."}]},
    {"Name":"Were Bane","Class":"S.Sword","Description":"Effective against werebeasts.","Attack":18,"Speed":"Normal","DMG":"CUT","Dropped":["Hunting Girl"],"Specials":[{"Type":2,"ATT":40,"Info":"Multiple Attacks."}]},
    {"Name":"Shotel","Class":"S.Sword","Description":"Abyssinian curved sword.","Attack":20,"Speed":"Slow","DMG":"CUT","Found":["Reverse Outer Wall"],"Dropped":["Blade Master"],"Specials":[{"Type":2,"ATT":20,"Info":"Throws sword like a boomerang."}]},
    {"Name":"Combat Knife","Class":"S.Sword","Description":"Flat combat dagger Sucessive strikes results in \"direct attack\" + \"crossing attack\".","Attack":24,"Speed":"Very quick","DMG":"CUT","Found":["Catacombs"],"Dropped":["Gurkha"],"Specials":[{"Type":1,"ATT":15,"Info":"Crossing Attack, can be made in mid-air and can be downward changing [foward] for [down\/foward]."}]},
    {"Name":"Tyrfing","Class":"Sword","Description":"Cursed dark sword. Weaker sword in the game. Useful to cause the lesser possible damage.","Attack":"-30","Speed":"Very slow","DMG":"CUT","Found":["Castle Keep"]},
    {"Name":"Alucart sword","Class":"Sword","Description":"Resembles family sword.","Speed":"Quick","DMG":"CUT","Found":["Marble Gallery"]},
    {"Name":"Gladius","Class":"Sword","Description":"Sword of ancient Rome.","Attack":3,"Speed":"Normal","DMG":"CUT","Found":["Outer Wall"]},
    {"Name":"Scimitar","Class":"Sword","Description":"Single edged sword.","Attack":5,"Speed":"Normal","DMG":"CUT","Found":["Underground Caverns"],"Dropped":["Skull Lord"]},
    {"Name":"Cutlass","Class":"Sword","Description":"Sword of the English Navy.","Attack":7,"Speed":"Normal","DMG":"CUT","Found":["Royal Chapel"],"Dropped":["Sword Lord","Corner Guard","Owl Knight"]},
    {"Name":"Saber","Class":"Sword","Description":"Light cavalry sword.","Attack":9,"Speed":"Normal","DMG":"CUT","Dropped":["Armor Lord","Magic Tome"],"Sold":1500},
    {"Name":"Falchion","Class":"Sword","Description":"Norman curved sword.","Attack":10,"Speed":"Normal","DMG":"CUT","Found":["Castle Keep"]},
    {"Name":"Broadsword","Class":"Sword","Description":"Simple mercenary's sword.","Attack":12,"Speed":"Normal","DMG":"CUT","Found":["Olrox's Quarters"],"Dropped":["Spectral Sword13"]},
    {"Name":"Bekatowa","Class":"Sword","Description":"Plain, easy-to-use sword.","Attack":14,"Speed":"Normal","DMG":"CUT","Found":["Clock Tower"],"Dropped":["Sword Lord"]},
    {"Name":"Damascus sword","Class":"Sword","Description":"Fine sword honed to razor-edge.","Attack":17,"Speed":"Normal","DMG":"CUT","Dropped":["Corner Guard"],"Sold":4000},
    {"Name":"Hunter sword","Class":"Sword","Description":"Ivory handled hunting sword.","Attack":20,"Defense":1,"Speed":"Normal","DMG":"CUT","Dropped":["Blade"]},
    {"Name":"Bastard sword","Class":"Sword","Description":"Standard sword.","Attack":20,"Speed":"Normal","DMG":"CUT","Dropped":["Spectral Sword13"]},
    {"Name":"Talwar","Class":"Sword","Description":"Curved Indian sword.","Attack":22,"Speed":"Normal","DMG":"CUT","Found":["Anti-Chapel"]},
    {"Name":"Sword of Hador","Class":"Sword","Description":"House of Hador heirloom.","Attack":24,"Speed":"Normal","DMG":"CUT","Found":["Death Wing's Lair"]},
    {"Name":"Mormegil","Class":"Sword","Description":"Black sword - strong vs. holy.","Attack":25,"Speed":"Normal","DMG":"CUT","Found":["Catacombs"]},
    {"Name":"Gurthang","Class":"Sword","Description":"Gets stronger when bloodied. ATT+26 when \"Dark Metamorphosis\" is active.","Attack":15,"Defense":1,"Speed":"Normal","DMG":"CUT","Dropped":["Spectral Sword36"],"Specials":[{"Type":2,"ATT":30,"Info":"Instantaneous \"Dark metamorphosis\"."}]},
    {"Name":"Firebrand","Class":"Sword","Description":"Fire sword of Oberon.","Attack":25,"Speed":"Normal","DMG":"CUT,FIR","Dropped":["Lossoth"],"Sold":10000,"Specials":[{"Type":2,"ATT":40,"MP":5,"Info":"Super Attack."}]},
    {"Name":"Icebrand","Class":"Sword","Description":"Ice sword of Mim.","Attack":25,"Speed":"Normal","DMG":"CUT,ICE","Found":["Catacombs"],"Dropped":["Fishhead"],"Sold":10000,"Specials":[{"Type":2,"ATT":40,"MP":5,"Info":"Super Attack."}]},
    {"Name":"Thunderbrand","Class":"Sword","Description":"Lightning sword of Indra.","Attack":25,"Speed":"Normal","DMG":"CUT,THU","Sold":10000,"Specials":[{"Type":2,"ATT":40,"MP":5,"Info":"Super Attack."}]},
    {"Name":"Vorpal blade","Class":"Sword","Description":"Slices cleanly through enemies.","Attack":25,"Speed":"Instantaneous","DMG":"CUT","Dropped":["Archer"]},
    {"Name":"Luminus","Class":"Sword","Description":"Sword forged by elves.","Attack":26,"Speed":"Normal","DMG":"CUT","Found":["Reverse Clock Tower"]},
    {"Name":"Holy sword","Class":"Sword","Description":"Cross hilt - strong vs. undead.","Attack":26,"Speed":"Normal","DMG":"CUT,HOL","Found":["Colosseum"],"Dropped":["Vandal Sword"],"Specials":[{"Type":2,"ATT":35,"MP":5,"Info":"Super Attack."}]},
    {"Name":"Harper","Class":"Sword","Description":"The sword named Harper.","Attack":28,"Speed":"Normal","DMG":"CUT","Sold":12000},
    {"Name":"Gram","Class":"Sword","Description":"The sword named Gram.","Attack":30,"Speed":"Normal","DMG":"CUT","Found":["Reverse Colosseum"]},
    {"Name":"Terminus Est","Class":"Sword","Description":"Poisoned executioner's sword.","Attack":32,"Defense":2,"Speed":"Normal","DMG":"CUT,PSN","Dropped":["Nova Skeleton"]},
    {"Name":"Marsil","Class":"Sword","Description":"Powerful sword of flame. Flames cause extra damage.","Attack":33,"Defense":1,"Speed":"Normal","DMG":"CUT,FIR","Dropped":["Fire Demon"],"Specials":[{"Type":2,"ATT":60,"MP":5,"Info":"Super Attack"}]},
    {"Name":"Dark Blade","Class":"Sword","Description":"Sword forged by elves.","Attack":35,"Defense":2,"Speed":"Normal","DMG":"CUT","Found":["Reverse Caverns"]},
    {"Name":"Mourneblade","Class":"Sword","Description":"Feeds upon enemy's souls. Restores 8 HP per stike.","Attack":36,"Defense":1,"Speed":"Normal","DMG":"CUT","Dropped":["Azaghal"]},
    {"Name":"Crissaegrim","Class":"Sword","Description":"Countless blades dice enemy. 4 slices per Attack.","Attack":36,"Defense":1,"Speed":"Instantaneous","DMG":"CUT","Dropped":["Schmoo"]},
    {"Name":"Mablung Sword","Class":"Sword","Description":"Spirit sword - improves DEF.","Attack":39,"Defense":2,"Speed":"Normal","DMG":"CUT","Dropped":["Spectral Sword36"],"Specials":[{"Type":3,"Info":"Summons shield's powers."}]},
    {"Name":"Alucard sword","Class":"Sword","Description":"Mother's family heirloom.","Attack":42,"Speed":"Quick","DMG":"CUT","Found":["Reverse Caverns"],"Specials":[{"Type":2,"ATT":50,"MP":5,"Info":"Teleport + Back Double Attack ."}]},
    {"Name":"Sword Familiar","Class":"Sword","Description":"Sentient sword familiar. ATT = Familiar LV.","Attack":"Familiar LV","Speed":"Normal","DMG":"CUT"},
    {"Name":"Badelaire","Class":"Sword","Description":"Power increases with game play. ATT = hours played.","Attack":"Game hours","Speed":"Normal","DMG":"CUT","Found":["Forbidden Library"]},
    {"Name":"Chakram","Class":"Throw 1","Description":"Sikh steel throwing ring.","Attack":15,"Speed":"Instantaneous","DMG":"CUT","Dropped":["Discus Lord"]},
    {"Name":"Heaven sword","Class":"Throw 1","Description":"Enchanted floating sword.","Attack":21,"Defense":2,"Speed":"Instantaneous","DMG":"CUT","Dropped":["Cloaked Knight"],"Specials":[{"Type":3,"ATT":21,"Info":"Equip two Heaven swords and execute the command. Various swords makes combo attacks."}]},
    {"Name":"Runesword","Class":"Throw 1","Description":"Flying rune-inscribed sword.","Attack":40,"Defense":"-4","Speed":"Instantaneous","DMG":"CUT","Dropped":["Dodo Bird"]},
    {"Name":"Knuckle duster","Class":"Fist","Description":"Iron studded brass knuckles.","Attack":4,"Speed":"Very quick","DMG":"HIT","Dropped":["Frog"]},
    {"Name":"Blue knuckles","Class":"Fist","Description":"Knuckles for uppercut-use.","Attack":8,"Speed":"Instantaneous","DMG":"HIT","Dropped":["Toad"]},
    {"Name":"Jewel knuckles","Class":"Fist","Description":"Jewel reinforced knuckles.","Attack":21,"Speed":"Very quick","DMG":"HIT","Found":["Outer Wall"],"Dropped":["Rock Knight"]},
    {"Name":"Iron Fist","Class":"Fist","Description":"Owned by Karate master.","Attack":26,"Speed":"Very quick","DMG":"HIT","Dropped":["Werewolf34"],"Specials":[{"Type":2,"ATT":40,"Info":"Multiple punches."}]},
    {"Name":"Fist of Tulkas","Class":"Fist","Description":"Blessed by Tulkas the Valar.","Attack":38,"Defense":5,"Speed":"Very quick","DMG":"HIT","Dropped":["Lion"],"Specials":[{"Type":1,"ATT":70,"Info":"Multiple punches. Can be made in mid-air."}]},
    {"Name":"Mace","Class":"Club","Description":"Iron cudgel.","Attack":9,"Speed":"Normal","DMG":"HIT","Sold":2000},
    {"Name":"Morningstar","Class":"Club","Description":"Spiked iron club.","Attack":11,"Speed":"Normal","DMG":"HIT","Found":["Royal Chapel"],"Dropped":["Flail Guard"]},
    {"Name":"Shield rod","Class":"Club","Description":"Extra effective with shield. ATT+5 with shield.","Attack":11,"Defense":2,"Speed":"Normal","DMG":"HIT","Found":["Colosseum"],"Specials":[{"Type":1,"ATT":10,"Info":"Throws a \"Gradius\" shield."}]},
    {"Name":"Holy rod","Class":"Club","Description":"Anointed rod.","Attack":12,"Speed":"Quick","DMG":"HIT,HOL","Found":["Long Library"],"Specials":[{"Type":1,"ATT":37,"Info":"Angelical summoning."}]},
    {"Name":"Star flail","Class":"Club","Description":"Flail with spiked balls.","Attack":15,"Speed":"Quick","DMG":"HIT","Found":["Clock Tower"],"Specials":[{"Type":1,"ATT":35,"Info":"Improved Attack"}]},
    {"Name":"Moon rod","Class":"Club","Description":"Rod with lunar markings.","Attack":17,"Speed":"Normal","DMG":"HIT","Found":["Reverse Clock Tower"],"Specials":[{"Type":2,"ATT":35,"MP":5,"Info":"Shoots 5 lunar projectiles."}]},
    {"Name":"Muramasa","Class":"Two-hand","Description":"Bloodthirsty sword. Continuous Dark Metamorphosis. Gets stronger absorving blood. Max ATT = 999","Attack":"-5","Defense":"-4","Speed":"Normal","DMG":"CUT,CUR","Dropped":["Vandal Sword"]},
    {"Name":"Namakura","Class":"Two-hand","Description":"Poorly made sword.","Attack":"-5","Speed":"Slow","DMG":"CUT,CUR","Dropped":["Blade Soldier"]},
    {"Name":"Red Rust","Class":"Two-hand","Description":"Rusty red sword. Don't attack downwards. Attacks fails.","Attack":"-2","Speed":"Slow","DMG":"CUT,CUR","Dropped":["Bone Scimitar"]},
    {"Name":"Takemitsu","Class":"Two-hand","Description":"Bamboo sword. Don't attack downward.","Attack":1,"Speed":"Slow","DMG":"HIT","Dropped":["Flea Man","Puppet Sword"]},
    {"Name":"Nunchaku","Class":"Two-hand","Description":"Strikes enemy twice.","Attack":10,"Speed":"Normal","DMG":"HIT","Found":["Underground Caverns"]},
    {"Name":"Claymore","Class":"Two-hand","Description":"Scotch two-handed sword.","Attack":26,"Speed":"Normal","DMG":"CUT","Found":["Underground Caverns"],"Dropped":["Valhalla Knight"],"Specials":[{"Type":1,"ATT":44,"MP":5,"Info":"Thrusting Attack. Can be made in mid-air."}]},
    {"Name":"Sword of Dawn","Class":"Two-hand","Description":"Summons Dawn Warriors.","Attack":27,"Speed":"Normal","DMG":"CUT","Found":["Reverse Keep"],"Specials":[{"Type":2,"MP":5,"Info":"Summons Dawn Warriors"}]},
    {"Name":"Flamberge","Class":"Two-hand","Description":"Flame-edged sword.","Attack":31,"Speed":"Normal","DMG":"CUT","Dropped":["Cloaked Knight"],"Specials":[{"Type":1,"ATT":56,"MP":5,"Info":"Thrusting Attack. Can be made in mid-air."}]},
    {"Name":"Zwei hander","Class":"Two-hand","Description":"German two-handed sword;.","Attack":38,"Speed":"Normal","DMG":"CUT","Dropped":["Blue Venus Weed"],"Specials":[{"Type":1,"ATT":60,"MP":5,"Info":"Thrusting Attack. Can be made in mid-air."}]},
    {"Name":"Estoc","Class":"Two-hand","Description":"German thrust sword. Attack Thrusting Attack.","Attack":39,"Speed":"Normal","DMG":"CUT","Found":["Olrox's Quarters"],"Dropped":["Cloaked Knight"]},
    {"Name":"Obsidian sword","Class":"Two-hand","Description":"Two-handed obsidian sword.","Attack":42,"Speed":"Normal","DMG":"CUT","Dropped":["Lesser Demon"],"Specials":[{"Type":1,"ATT":68,"MP":5,"Info":"Thrusting Attack. Can be made in mid-air."}]},
    {"Name":"Great sword","Class":"Two-hand","Description":"Greatsword of Aubec.","Attack":65,"Speed":"Normal","DMG":"CUT","Dropped":["Guardian"]},
    {"Name":"Katana","Class":"Two-hand","Description":"Unsigned katana.","Attack":32,"Speed":"Normal","DMG":"CUT","Dropped":["Tombstone"],"Specials":[{"Type":2,"ATT":50,"Info":"Dice enemy."}]},
    {"Name":"Osafune Katana","Class":"Two-hand","Description":"Osafune-made katana.","Attack":50,"Defense":"-10","Speed":"Normal","DMG":"CUT","Found":["Reverse Caverns"],"Specials":[{"Type":1,"ATT":79,"Info":"Teleport + Attack."}]},
    {"Name":"Yasutsuna","Class":"Two-hand","Description":"Yasutsuna-made katana.","Attack":60,"Defense":"-20","Speed":"Instantaneous","DMG":"CUT","Dropped":["Werewolf34"]},
    {"Name":"Masamune","Class":"Two-hand","Description":"Legendary Masamune katana.","Attack":90,"Defense":"-20","Speed":"Normal","DMG":"CUT","Found":["Necromancy Laboratory"],"Dropped":["Black Panther"],"Specials":[{"Type":2,"ATT":149,"Info":"Attack+Teleport+Attack."}]},
    {"Name":"Alucart shield","Class":"Shield","Description":"Resembles family shield.","Found":["Marble Gallery"],"Specials":[{"Type":3,"MP":10,"Info":"?"}]},
    {"Name":"Leather shield","Class":"Shield","Description":"Leather shield - low DEF.","Defense":1,"Found":["Alchemy Laboratory"],"Dropped":["Slinger"],"Specials":[{"Type":3,"MP":10,"Info":"Summons a cow. +20 DEF temporarily."}]},
    {"Name":"Medusa shield","Class":"Shield","Description":"Gorgon headed shield. Causes STN damage on contact.","Attack":13,"Defense":1,"DMG":"STN","Dropped":["Medusa Head7","Medusa Head8"],"Specials":[{"Type":3,"MP":30,"Info":"Shoots petrifying rays damaging all enemies."}]},
    {"Name":"Knight shield","Class":"Shield","Description":"Armored knight's shield.","Defense":2,"Found":["Colosseum"],"Dropped":["Slinger"],"Specials":[{"Type":3,"MP":10,"Info":"Summons a horse. +20 ATT temporarily."}]},
    {"Name":"Iron shield","Class":"Shield","Description":"Hard iron shield. Confers 3 seconds of invulnerability for each block.","Defense":2,"Dropped":["Winged Guard"],"Sold":3980,"Specials":[{"Type":3,"ATT":40,"MP":20,"Info":"Summons a knight which throws giant swords."}]},
    {"Name":"AxeLord shield","Class":"Shield","Description":"Favorite shield of Axe Lords.","Defense":3,"Dropped":["Axe Knight9"],"Specials":[{"Type":3,"ATT":20,"MP":20,"Info":"Summons an AxeLord which attacks the first enemy in his path."}]},
    {"Name":"Dark shield","Class":"Shield","Description":"Unholy dark shield. Contact causes DRK damage.","Attack":10,"Defense":3,"DMG":"DRK","Dropped":["Malachi"],"Specials":[{"Type":3,"ATT":30,"MP":30,"Info":"Summons meteors which damages all enemies."}]},
    {"Name":"Goddess shield","Class":"Shield","Description":"Engraved with goddess image.","Defense":4,"Found":["Necromancy Laboratory"],"Specials":[{"Type":3,"MP":40,"Info":"Brief protection against DRK."}]},
    {"Name":"Shaman shield","Class":"Shield","Description":"Shield used in magic rituals.","Defense":4,"Found":["Clock Tower"],"Specials":[{"Type":3,"MP":10,"Info":"Summons a magical goat. +20 INT temporarily."}]},
    {"Name":"Skull shield","Class":"Shield","Description":"Shield with Knight's crest.","Defense":4,"Dropped":["Skull Lord"],"Specials":[{"Type":3,"ATT":100,"MP":40,"Info":"Summons skulls that shoots a powerful beam."}]},
    {"Name":"Fire shield","Class":"Shield","Description":"Shield with fire properties. Grants fire immunity.","Defense":4,"Dropped":["Fire Demon"],"Specials":[{"Type":3,"ATT":70,"MP":50,"Info":"Summons fire salamanders (from Gradius) which damages all enemies"}]},
    {"Name":"Herald shield","Class":"Shield","Description":"Shield with heart crest. Grants 1 Heart for each block.","Defense":4,"Found":["Underground Caverns"],"Specials":[{"Type":3,"MP":10,"Info":"Summons a goddess. Briefly protects against FIR and THU."}]},
    {"Name":"Alucard shield","Class":"Shield","Description":"Strong vs. all attacks.","Defense":5,"Found":["Cave"],"Specials":[{"Type":3,"ATT":255,"MP":20,"Info":"Reunite powers from all shields."}]},
    {"Name":"Monster vial 1","Class":"Throw 2","Description":"Summons merman ally. [use]","Attack":40,"Dropped":["Merman3"]},
    {"Name":"Monster vial 2","Class":"Throw 2","Description":"Summons bat ally. [use]","Attack":25,"Dropped":["Bat"]},
    {"Name":"Monster vial 3","Class":"Throw 2","Description":"Summons skeleton ally. [use]","Attack":30,"Found":["Catacombs"],"Dropped":["Skeleton","Bone Ark","Yorick"]},
    {"Name":"Magic Missile","Class":"Throw 2","Description":"Shoots a magic arrow. [use]","Attack":30,"Found":["Clock Tower","Royal Chapel","Underground Caverns"],"Dropped":["Bone Musket","Skeleton Archer","Sniper of Goth"]},
    {"Name":"Bwaka knife","Class":"Throw 2","Description":"Bwaka throwing knife. [use]","Attack":30,"Found":["Clock Tower"],"Dropped":["Poltergeist"],"Sold":400},
    {"Name":"Boomerang","Class":"Throw 2","Description":"Anti-aereal weapon. [use]","Attack":30,"Dropped":["Skelerang"],"Sold":500},
    {"Name":"Javelin","Class":"Throw 2","Description":"Throwing spear. [use]","Attack":50,"Dropped":["Spear Guard"],"Sold":800},
    {"Name":"Fire boomerang","Class":"Throw 2","Description":"Flaming boomerang. [use]","Attack":50,"Dropped":["Skelerang"],"Sold":1000},
    {"Name":"Iron ball","Class":"Throw 2","Description":"Plate Lord's iron ball. [use]","Attack":60,"Found":["Olrox's Quarters"],"Dropped":["Plate Lord","Skull","Spiked Ball"]},
    {"Name":"TNT","Class":"Throw 2","Description":"Creates pillar of flame. [use]","Attack":60,"Found":["Clock Tower","Royal Chapel"],"Dropped":["Skeleton Ape","Bomb Knight"]},
    {"Name":"Dynamite","Class":"Throw 2","Description":"Powerful! Be careful... [use]","Attack":100,"Dropped":["Bomb Knight"]},
    {"Name":"Shuriken","Class":"Throw 2","Description":"Japanese throwing star. [use]","Attack":50,"Found":["Clock Tower","Royal Chapel"],"Dropped":["Flying Zombie","Jack O' Bones"],"Sold":240},
    {"Name":"Cross shuriken","Class":"Throw 2","Description":"Powerful throwing star. [use]","Attack":70,"Found":["Catacombs"],"Dropped":["Blade Master"],"Sold":5000},
    {"Name":"Buffalo star","Class":"Throw 2","Description":"Razor-sharp master star. [use]","Attack":90,"Dropped":["Ghost Dancer"],"Sold":8000},
    {"Name":"Flame star","Class":"Throw 2","Description":"Flaming throwing star. [use]","Attack":100,"Dropped":["Jack O' Bones"],"Sold":15000},
    {"Name":"Neutron bomb","Class":"Bomb","Description":"Damages all enemies. [use]","Attack":30,"Dropped":["Plate Lord","Cave Troll"]},
    {"Name":"Power of Sire","Class":"Bomb","Description":"Damages all enemies. [use]","Attack":30,"Found":["Abandoned Mine","Cave"]},
    {"Name":"Karma Coin","Class":"Bomb","Description":"Coin with 2 effects. [use]","Attack":50,"Found":["Abandoned Mine","Catacombs"],"Dropped":["Orobourous","Fire Warg"]},
    {"Name":"Pentagram","Class":"Bomb","Description":"Damages all enemies. [use]","Attack":50,"Found":["Clock Tower"],"Dropped":["Ctulhu","Spellbook"]},
    {"Name":"Bat Pentagram","Class":"Bomb","Description":"Damages all enemies. [use]","Attack":99,"Dropped":["Ctulhu"]},
    {"Name":"Potion","Class":"Medicine","Description":"Restores 50 HP. [use]","Found":["Alchemy Laboratory","Long Library","Royal Chapel"],"Dropped":["Bat","Corpseweed"],"Sold":800},
    {"Name":"High Potion","Class":"Medicine","Description":"Restores 100 HP. [use]","Dropped":["Flea Armor"],"Sold":2000},
    {"Name":"Elixir","Class":"Medicine","Description":"Restores all HP. [use]","Found":["Underground Caverns"],"Sold":8000},
    {"Name":"Manna prism","Class":"Medicine","Description":"Restores all MP. [use]","Found":["Olrox's Quarters"],"Dropped":["Ectoplasm","Salome"],"Sold":4000},
    {"Name":"Heart Refresh","Class":"Medicine","Description":"Restores 500 hearts. [use]","Dropped":["Venus Weed","Archer","Blue Venus Weed"]},
    {"Name":"Antivenom","Class":"Medicine","Description":"Cures poisoning. [use]","Found":["Long Library","Underground Caverns"],"Dropped":["Bone Pillar","Corpseweed"],"Sold":200},
    {"Name":"Uncurse","Class":"Medicine","Description":"Removes curse. [use]","Found":["Long Library"],"Dropped":["Ectoplasm"],"Sold":200},
    {"Name":"Attack potion","Class":"Medicine","Description":"Temporarily raises ATT by 20. [use]","Found":["Marble Gallery"]},
    {"Name":"Shield potion","Class":"Medicine","Description":"Temporarily raises DEF by 20. [use]","Found":["Entrance"],"Dropped":["Skeleton"]},
    {"Name":"Smart potion","Class":"Medicine","Description":"Temporarily raises INT by 20. [use]","Dropped":["Marionette"]},
    {"Name":"Luck potion","Class":"Medicine","Description":"Temporarily raises LCK by 20. [use]","Found":["Olrox's Quarters"],"Dropped":["Bitterfly","Imp"]},
    {"Name":"Str. potion","Class":"Medicine","Description":"Temporarily raises STR by 20. [use]","Found":["Marble Gallery","Royal Chapel"],"Dropped":["Were Skeleton"]},
    {"Name":"Resist fire","Class":"Medicine","Description":"Brief resistance to fire. [use]","Found":["Olrox's Quarters"],"Dropped":["Gremlin"]},
    {"Name":"Resist ice","Class":"Medicine","Description":"Brief resistance to ice. [use]","Found":["Underground Caverns"],"Dropped":["Fishhead"]},
    {"Name":"Resist thunder","Class":"Medicine","Description":"Resistance to lightning. [use]","Found":["Alchemy Laboratory"]},
    {"Name":"Resist stone","Class":"Medicine","Description":"Resistance to stone. [use]","Found":["Castle Keep"],"Dropped":["Medusa Head7","Medusa Head8"]},
    {"Name":"Resist dark","Class":"Medicine","Description":"Resistance to darkness. [use]","Found":["Castle Keep"],"Dropped":["Phantom Skull","Karasuman"]},
    {"Name":"Resist holy","Class":"Medicine","Description":"Resistance to holy. [use]","Found":["Castle Keep"]},
    {"Name":"Library card","Class":"Medicine","Description":"Enchanted library card. [use]","Found":["Marble Gallery","Colosseum","Catacombs"],"Sold":500},
    {"Name":"Hammer","Class":"Medicine","Description":"Unpetrify. [Familyar use only]","Dropped":["Hammer","Gorgon"],"Sold":200},
    {"Name":"Life apple","Class":"Medicine","Description":"Heals. [Familiar use only]","Found":["Entrance"],"Dropped":["Harpy"]},
    {"Name":"Frankfurter","Class":"Food","Description":"Local favorite. Restores 19 HP. [use]","Dropped":["Flying Zombie"]},
    {"Name":"Pot roast","Class":"Food","Description":"Castlevania pot roast. Restores 50 HP. [use]","Found":["Entrance","Outer Wall","Clock Tower","Castle Keep","Underground Caverns"],"Dropped":["Flail Guard"]},
    {"Name":"Turkey","Class":"Food","Description":"Roast turkey. Restores 80 HP. [use]","Found":["Entrance","Castle Keep","Abandoned Mine"],"Dropped":["Flea Rider"]},
    {"Name":"Sirloin","Class":"Food","Description":"Sirloin steak. Restores 100 HP. [use]","Found":["Castle Keep"],"Dropped":["Lossoth","Minotaur"]},
    {"Name":"Miso soup","Class":"Food","Description":"Japanese miso soup. Restores 20 HP. [use]","Dropped":["Grave Keeper"]},
    {"Name":"Hamburger","Class":"Food","Description":"100% USA Grade A. Meal Ticket only. Restores 20 HP. [use]","Descricao":"100% USA Classe A. Recupera 20 HP. [use]."},
    {"Name":"Pizza","Class":"Food","Description":"New York style!. Restores 21 HP. [use]","Dropped":["Frog","Toad"]},
    {"Name":"Ham and eggs","Class":"Food","Description":"Increases cholesterol. Restores 22 HP. [use]","Dropped":["Flea Rider","Bone Halberd"]},
    {"Name":"Omelette","Class":"Food","Description":"Western omelette. Meal Ticket only. Restores 23 HP. [use]","Descricao":"Omelete do Oeste. Recupera 23 HP. [use]"},
    {"Name":"Morning set","Class":"Food","Description":"Eggs, toast and coffee. Restores 24 HP. [use]","Dropped":["Ouija Table"]},
    {"Name":"Lunch A","Class":"Food","Description":"Lunch set A. Restores 25 HP. [use]","Dropped":["Tin man"]},
    {"Name":"Lunch B","Class":"Food","Description":"Lunch set B. Meal Ticket only. Restores 26 HP. [use]","Descricao":"PF B. Recupera 26 HP. [use]"},
    {"Name":"Spaghetti","Class":"Food","Description":"Spaghetti Carbonara. Meal Ticket only. Restores 27 HP. [use]","Descricao":"Spaghetti Carbonara. Recupera 27 HP. [use]"},
    {"Name":"Curry rice","Class":"Food","Description":"Cooked with coconut milk. Meal Ticket only. Restores 28 HP. [use]","Descricao":"Cozido com leite de côco. Recupera 28 HP. [use]"},
    {"Name":"Gyros plate","Class":"Food","Description":"With fries. Meal Ticket only. Restores 29 HP. [use]","Descricao":"Com fritas. Recupera 29 HP. [use]"},
    {"Name":"Ramen","Class":"Food","Description":"Chinese ramen noodles. Restores 30 HP. [use]","Dropped":["Schmoo"]},
    {"Name":"Natou","Class":"Food","Description":"Smelly fermented soybean. Restores 32 HP. [use]","Dropped":["Grave Keeper"]},
    {"Name":"Sushi","Class":"Food","Description":"Toro, ebi, tamago. Restores 100 HP. [use]","Dropped":["Killer Fish","Dark Octopus"]},
    {"Name":"Shortcake","Class":"Food","Description":"Strawberry shortcake. Restores 11 HP. [use]","Dropped":["Salem Witch"]},
    {"Name":"Tart","Class":"Food","Description":"Strawberry tart. Restores 12 HP. [use]","Dropped":["Diplocephalus"]},
    {"Name":"Cheesecake","Class":"Food","Description":"With chocolate chips. Meal Ticket only. Restores 14 HP. [use]","Descricao":"Com pedaços de chocolate. Recupera 14 HP. [use]"},
    {"Name":"Cheese","Class":"Food","Description":"Delicious cheese. Restores 18 HP. [use]","Found":["Olrox's Quarters"],"Dropped":["Flea Man"]},
    {"Name":"Chinese bun","Class":"Food","Description":"Vegetable steamed bun. Meal Ticket Only. Restores 10 HP. [use]","Descricao":"Bolinhos vegetais cozidos a vapor. Recupera 10 HP. [use]"},
    {"Name":"Red bean bun","Class":"Food","Description":"Chinese red bean bun. Restores 12 HP. [use]","Dropped":["Black Crow"]},
    {"Name":"Pork bun","Class":"Food","Description":"Chinese pork bun. Restores 17 HP. [use]","Dropped":["Blue Raven"]},
    {"Name":"Dim Sum set","Class":"Food","Description":"3 Dim Sum dishes. Restores 30 HP. [use]","Found":["Reverse Outer Wall"]},
    {"Name":"Toadstool","Class":"Food","Description":"Poisonous mushroom. Causes \"poison\". [use]","Found":["Underground Caverns"]},
    {"Name":"Shiitake","Class":"Food","Description":"Japanese mushroom. Restores 30 HP. [use]","Found":["Underground Caverns","Abandoned Mine"]},
    {"Name":"Peanuts","Class":"Food","Description":"Difficult to eat. Restores 50 HP. Throw up and press up. [use]","Found":["Abandoned Mine"]},
    {"Name":"Ice cream","Class":"Food","Description":"3-layer ice cream. Restores 15 HP. [use]","Dropped":["Frozen Shade"]},
    {"Name":"Parfait","Class":"Food","Description":"With whipped cream. Meal Ticket only. Restores 16 HP. [use]","Descricao":"Com creme batido. Recupera 16 HP. [use]"},
    {"Name":"Pudding","Class":"Food","Description":"A la mode. Meal Ticket only. Restores 17 HP. [use]","Descricao":"À moda. Recupera 17 HP. [use]"},
    {"Name":"Grapes","Class":"Food","Description":"Juicy seedless grapes. Restores 5 HP. [use]","Dropped":["Thornweed"]},
    {"Name":"Orange","Class":"Food","Description":"Japanese tangerine. Meal Ticket only. Restores 6 HP. [use]","Descricao":"Tangerina japonesa. Recupera 6 HP. [use]"},
    {"Name":"Banana","Class":"Food","Description":"Best when nearly rotten. Restores 7 HP. [use]","Dropped":["Skeleton Ape"]},
    {"Name":"Pineapple","Class":"Food","Description":"Tart southern fruit. Meal Ticket only. Restores 8 HP. [use]","Descricao":"Fruta azeda sulina. Recupera 8 HP. [use]"},
    {"Name":"Apple","Class":"Food","Description":"Crunchy delicious apple . Restores 9 HP. [use]","Dropped":["Harpy"]},
    {"Name":"Strawberry","Class":"Food","Description":"Ripe red strawberry. Restores 10 HP. [use]","Dropped":["Thornweed"]},
    {"Name":"Green tea","Class":"Food","Description":"Japanese green tea. Restores 10 HP. [use]","Dropped":["Dark Octopus"]},
    {"Name":"Barley tea","Class":"Food","Description":"Cool barley tea. Restores 15 HP. [use]","Found":["Abandoned Mine"],"Dropped":["Ouija Table"]},
    {"Name":"Grape juice","Class":"Food","Description":"Sparkling juice. Restores 20 HP. [use]","Found":["Royal Chapel"]},
    {"Name":"Meal ticket","Class":"Food","Description":"Mystery food ticket. [use]","Found":["Underground Caverns"],"Dropped":["Stone Rose","Black Panther"],"Sold":2000},
    {"Name":"Circlet","Class":"Head","Description":"Circlet.","Intelligence":5,"Dropped":["Marionette"],"Sold":4000},
    {"Name":"Gold circlet","Class":"Head","Description":"Restores HP by holy damage.","Intelligence":6,"Dropped":["Salem Witch"]},
    {"Name":"Coral circlet","Class":"Head","Description":"Immune to curses.","Intelligence":7,"Dropped":["Venus Weed"]},
    {"Name":"Cat-eye circl.","Class":"Head","Description":"Big HP restore by cat damage.","Intelligence":8,"Found":["Catacombs"]},
    {"Name":"Topaz circlet","Class":"Head","Description":"Restores HP by poison damage.","Intelligence":10,"Found":["Long Library"]},
    {"Name":"Beryl circlet","Class":"Head","Description":"Restores HP by lightning damage.","Intelligence":10,"Found":["Reverse Entrance"]},
    {"Name":"Opal circlet","Class":"Head","Description":"Restores HP by ice damage.","Intelligence":10,"Dropped":["Frozen Half"]},
    {"Name":"Ruby circlet","Class":"Head","Description":"Restores HP by fire damage.","Intelligence":10,"Found":["Cave"]},
    {"Name":"Silver crown","Class":"Head","Description":"Increases Intelligence.","Intelligence":12,"Sold":12000},
    {"Name":"Sunglasses","Class":"Head","Description":"Cool looking sunglasses.","Defense":1,"Intelligence":"-1","Found":["Alchemy Laboratory"]},
    {"Name":"Felt hat","Class":"Head","Description":"Felt hat.","Defense":1,"Intelligence":1,"Dropped":["Phantom Skull"]},
    {"Name":"Velvet hat","Class":"Head","Description":"Velvet hat.","Defense":1,"Intelligence":2,"Sold":400},
    {"Name":"Holy glasses","Class":"Head","Description":"Sees beyond magical curses.","Defense":1,"Intelligence":5,"Found":["Marble Gallery"]},
    {"Name":"Goggles","Class":"Head","Description":"Comfortable eye protection.","Defense":1,"Intelligence":4,"Found":["Royal Chapel"]},
    {"Name":"Leather hat","Class":"Head","Description":"Tanned leather hat.","Defense":2,"Sold":1000},
    {"Name":"Ballroom mask","Class":"Head","Description":"Mask used at a ball.","Defense":2,"Dropped":["Bone Pillar"]},
    {"Name":"Bandanna","Class":"Head","Description":"Protects sensitive head parts.","Defense":2,"Intelligence":1,"Found":["Underground Caverns"]},
    {"Name":"Stone mask","Class":"Head","Description":"Ancient ceremonial stone mask.","Defense":2,"Intelligence":4,"Dropped":["Ghost Dancer"]},
    {"Name":"Steel helm","Class":"Head","Description":"Standard adventurer's helm.","Defense":3,"Intelligence":1,"Found":["Clock Tower"]},
    {"Name":"Dragon helm","Class":"Head","Description":"Frightens enemy halving their DEF.","Defense":3,"Strength":4,"Found":["Reverse Clock Tower"]},
    {"Name":"Wizard hat","Class":"Head","Description":"Wide-brimmed for protection.","Defense":5,"Strength":1,"Intelligence":1,"Constitution":1,"Dropped":["Salome"]},
    {"Name":"Cloth tunic","Class":"Armor","Description":"Simple cloth tunic.","Defense":1,"Dropped":["Zombie","Bloody Zombie"]},
    {"Name":"Hide cuirass","Class":"Armor","Description":"Tanned leather cuirass.","Defense":2,"Found":["Alchemy Laboratory"],"Dropped":["Dhuron"]},
    {"Name":"Alucart mail","Class":"Armor","Description":"Resists fire, lightning, ice?.","Defense":2,"Found":["Marble Gallery"]},
    {"Name":"Bronze cuirass","Class":"Armor","Description":"Bronze cuirass.","Defense":3,"Found":["Long Library"],"Dropped":["Axe Knight4"]},
    {"Name":"Mirror cuirass","Class":"Armor","Description":"Polished to resist stoning.","Defense":3,"Found":["Outer Wall"]},
    {"Name":"Healing mail","Class":"Armor","Description":"Restores HP while walking.","Defense":4,"Found":["Clock Tower"]},
    {"Name":"Iron cuirass","Class":"Armor","Description":"Iron cuirass.","Defense":4,"Dropped":["Spear Guard","Flea Armor"],"Sold":1500},
    {"Name":"Fire mail","Class":"Armor","Description":"Strong vs. fire-based attacks.","Defense":4,"Dropped":["Gremlin","Hellfire Beast"]},
    {"Name":"Steel cuirass","Class":"Armor","Description":"Steel cuirass.","Defense":5,"Sold":4000},
    {"Name":"Silver plate","Class":"Armor","Description":"Silver breastplate.","Defense":6,"Found":["Royal Chapel"]},
    {"Name":"Gold plate","Class":"Armor","Description":"Gold breastplate.","Defense":8,"Dropped":["Gurkha","Hammer"]},
    {"Name":"Lightning mail","Class":"Armor","Description":"Strong vs. lightning attacks.","Defense":8,"Dropped":["Hellfire Beast"]},
    {"Name":"Ice mail","Class":"Armor","Description":"Strong vs. ice-based attacks.","Defense":8,"Found":["Clock Tower"],"Dropped":["Frozen Shade"]},
    {"Name":"Dark armor","Class":"Armor","Description":"Impervious to evil attacks.","Defense":8,"Dropped":["Malachi"]},
    {"Name":"Platinum mail","Class":"Armor","Description":"Platinum breastplate.","Defense":10,"Found":["Castle Keep"],"Dropped":["Rock knight"]},
    {"Name":"Holy mail","Class":"Armor","Description":"Strong vs. holy attacks.","Defense":11,"Found":["Entrance"]},
    {"Name":"Spike Breaker","Class":"Armor","Description":"Spike-breaking armor.","Defense":12,"Found":["Catacombs"]},
    {"Name":"Brilliant mail","Class":"Armor","Description":"Increases sub-weapon strength.","Defense":12,"Intelligence":1,"Dropped":["Sniper of Goth"]},
    {"Name":"Fury plate","Class":"Armor","Description":"DEF goes up when damage taken.","Defense":13,"Dropped":["Minotaurus"]},
    {"Name":"Diamond plate","Class":"Armor","Description":"Diamond breastplate.","Defense":15,"Sold":12000},
    {"Name":"Mojo mail","Class":"Armor","Description":"Increases magic attack power.","Defense":15,"Intelligence":1,"Dropped":["Tin man"]},
    {"Name":"Dracula tunic","Class":"Armor","Description":"Embroidered nobleman's tunic.","Defense":15,"Strength":1,"Intelligence":1,"Constitution":1,"Found":["Long Library"]},
    {"Name":"Axe Lord armor","Class":"Armor","Description":"Wearer becomes an Axe Knight.","Defense":15,"Found":["Long Library"],"Dropped":["Spiked Ball"]},
    {"Name":"Alucard mail","Class":"Armor","Description":"Resists fire, lightning, ice.","Defense":20,"Found":["Death Wing's Lair"]},
    {"Name":"God's Garb","Class":"Armor","Description":"Strongest of all armor.","Defense":25,"Constitution":2,"Dropped":["Guardian"]},
    {"Name":"Walk armor","Class":"Armor","Description":"DEF increases with map coverage. DEF=Rooms\/60","Defense":"ROOMS/60","Intelligence":"-5","Found":["Catacombs"]},
    {"Name":"Cloth cape","Class":"Cloak","Description":"Well-made but shabby looking.","Constitution":1,"Found":["Alchemy Laboratory"]},
    {"Name":"Reverse cloak","Class":"Cloak","Description":"Dual colored reversible cape. [System Menu].","Constitution":3,"Sold":2000},
    {"Name":"Blood cloak","Class":"Cloak","Description":"Converts damage to hearts.","Constitution":4,"Luck":"-1","Found":["Colosseum"]},
    {"Name":"Elven cloak","Class":"Cloak","Description":"Perfect for forest camouflage.","Constitution":5,"Sold":3000},
    {"Name":"Crystal cloak","Class":"Cloak","Description":"Enchanted semi-invisible cape.","Constitution":6,"Found":["Underground Caverns"]},
    {"Name":"Royal cloak","Class":"Cloak","Description":"Gorgeous blue cape.","Constitution":8,"Found":["Reverse Keep"]},
    {"Name":"Joseph's cloak","Class":"Cloak","Description":"Select color. [System Menu].","Constitution":9,"Sold":30000},
    {"Name":"Twilight cloak","Class":"Cloak","Description":"Black cape for vampires.","Constitution":10,"Found":["Anti-Chapel"]},
    {"Name":"Zircon","Class":"Other","Description":"Sparkling ring. Can be sold for $150.","Found":["Outer Wall","Royal Chapel","Underground Caverns","Reverse Keep","Reverse Caverns","Anti-Chapel","Reverse Entrance","Reverse Colosseum"],"Dropped":["Merman2","Merman3","Blue Raven"]},
    {"Name":"Aquamarine","Class":"Other","Description":"Fairly valuable ring. Can be sold for $800.","Found":["Royal Chapel","Anti-Chapel","Reverse Colosseum"],"Dropped":["Black Crow","Killer Fish"]},
    {"Name":"Turquoise","Class":"Other","Description":"Fairly valuable ring. Can be sold for $1500.","Found":["Castle Keep","Forbidden Library","Necromancy Laboratory"],"Dropped":["Fire Warg"]},
    {"Name":"Onyx","Class":"Other","Description":"Valuable ring. Can be sold for $3000.","Found":["Long Library","Underground Caverns","Olrox's Quarters"]},
    {"Name":"Garnet","Class":"Other","Description":"Valuable ring. Can be sold for $5000.","Found":["Outer Wall","Olrox's Quarters","Reverse Keep","Reverse Outer Wall","Reverse Caverns"],"Dropped":["Wereskeleton"]},
    {"Name":"Opal","Class":"Other","Description":"Valuable ring. Can be sold for $8000.","Found":["Forbidden Library","Reverse Caverns","Reverse Entrance","Death Wing's Lair"]},
    {"Name":"Diamond","Class":"Other","Description":"Highly valuable ring. Can be sold for $20000.","Found":["Anti-Chapel","Reverse Caverns","Reverse Clock Tower","Floating Catacombs"]},
    {"Name":"Silver Ring","Class":"Other","Description":"Inscription \"... in ... Tower\".","Found":["Royal Chapel"]},
    {"Name":"Gold Ring","Class":"Other","Description":"Inscription \"Wear ... Clock ...\".","Found":["Underground Caverns"]},
    {"Name":"Secret boots","Class":"Other","Description":"Discretly increases height!","Found":["Underground Caverns"]},
    {"Name":"Ankh of Life","Class":"Other","Description":"Improves heal item power.","Found":["Royal Chapel"]},
    {"Name":"Bloodstone","Class":"Other","Description":"Improves blood-healing ability.","Found":["Catacombs"]},
    {"Name":"Staurolite","Class":"Other","Description":"Strengthens power of cross.","Found":["Forbidden Library"]},
    {"Name":"Mystic pendant","Class":"Other","Description":"Increases MP restoration rate.","Found":["Royal Chapel"],"Dropped":["Bitterfly"]},
    {"Name":"Talisman","Class":"Other","Description":"May absorb damage taken.","Found":["Reverse Entrance"],"Dropped":["Bone Musket"]},
    {"Name":"Heart broach","Class":"Other","Description":"Reduces heart consumption.","Dropped":["Dodo Bird"]},
    {"Name":"Medal","Class":"Other","Description":"ATT+1 DEF+1.","Attack":1,"Defense":1,"Dropped":["Owl Knight"]},
    {"Name":"Lapis lazuli","Class":"Other","Description":"Jewel which brings luck.","Luck":20,"Dropped":["Orobourous"]},
    {"Name":"Gauntlet","Class":"Other","Description":"ATT+5.","Attack":5,"Dropped":["Paranthropus","Lion"]},
    {"Name":"Necklace of J","Class":"Other","Description":"DEF+5.","Defense":5,"Dropped":["Frozen Half"]},
    {"Name":"Nauglamir","Class":"Other","Description":"Dwarven necklace. DEF+15.","Defense":15,"Dropped":["Cave Troll"]},
    {"Name":"King's stone","Class":"Other","Description":"Gemstone buckle. STR+10.","Strength":10,"Dropped":["Imp"]},
    {"Name":"Covenant stone","Class":"Other","Description":"Gemstone buckle. STR+15.","Strength":15,"Dropped":["Azaghal"]},
    {"Name":"Sunstone","Class":"Other","Description":"Improves status after sunrise.","Strength":5,"Intelligence":5,"Constitution":5,"Luck":5,"Found":["Reverse Clock Tower"]},
    {"Name":"Moonstone","Class":"Other","Description":"Improves status after sunset.","Strength":5,"Intelligence":5,"Constitution":5,"Luck":5,"Found":["Clock Tower"]},
    {"Name":"Ring of Arcana","Class":"Other","Description":"Increases rare item appearance.","Found":["Long Library","Necromancy Laboratory"]},
    {"Name":"Ring of Ares","Class":"Other","Description":"Confers strength of 24 men.","Defense":"-24","Strength":24,"Found":["Catacombs"]},
    {"Name":"Ring of Pales","Class":"Other","Description":"Ring with holy powers.","Strength":1,"Intelligence":1,"Constitution":1,"Luck":1,"Sold":1000},
    {"Name":"Ring of Feanor","Class":"Other","Description":"Increases overall strength.","Strength":7,"Intelligence":7,"Constitution":7,"Luck":2,"Dropped":["Karasuman"]},
    {"Name":"Ring of Varda","Class":"Other","Description":"Golden ring to rule over all.","Strength":30,"Intelligence":30,"Constitution":10,"Luck":5,"Dropped":["Paranthropus"]},
    {"Name":"Duplicator","Class":"Other","Description":"Duplicates [use] items.","Intelligence":"-10","Constitution":"-10","Luck":10,"Sold":500000},
    {"Name":"Soul of Bat","Class":"Relic","Description":"Transform into Bat.","Found":["Long Library"]},
    {"Name":"Fire of Bat","Class":"Relic","Description":"Shoot fireballs as Bat.","Found":["Clock Tower"]},
    {"Name":"Echo of Bat","Class":"Relic","Description":"Use radar as Bat.","Found":["Olrox's Quarters"]},
    {"Name":"Force of Echo","Class":"Relic","Description":"Attack with radar waves.","Found":["Reverse Caverns"]},
    {"Name":"Soul of Wolf","Class":"Relic","Description":"Transform into Wolf.","Found":["Outer Wall"]},
    {"Name":"Power of Wolf","Class":"Relic","Description":"Run swiftly as Wolf.","Found":["Entrance"]},
    {"Name":"Skill of Wolf","Class":"Relic","Description":"Skill move as Wolf.","Found":["Alchemy Laboratory"]},
    {"Name":"Form of Mist","Class":"Relic","Description":"Transform into Mist.","Found":["Colosseum"]},
    {"Name":"Power of Mist","Class":"Relic","Description":"Extends Mist transformation time.","Found":["Castle Keep"]},
    {"Name":"Gas Cloud","Class":"Relic","Description":"Transform into poisonous cloud.","Found":["Floating Catacombs"]},
    {"Name":"Cube of Zoe","Class":"Relic","Description":"Causes items to materialize.","Found":["Entrance"]},
    {"Name":"Spirit Orb","Class":"Relic","Description":"Shows enemy damage.","Found":["Marble Gallery"]},
    {"Name":"Gravity Boots","Class":"Relic","Description":"Wearer can jump high.","Found":["Marble Gallery"]},
    {"Name":"Leap Stone","Class":"Relic","Description":"Wearer can do double jump.","Found":["Castle Keep"]},
    {"Name":"Holy Symbol","Class":"Relic","Description":"Protection while underwater.","Found":["Underground Caverns"]},
    {"Name":"Faerie Scroll","Class":"Relic","Description":"Displays enemy's name.","Found":["Long Library"]},
    {"Name":"Jewel of Open","Class":"Relic","Description":"Can open locked blue doors.","Sold":2000},
    {"Name":"Merman Statue","Class":"Relic","Description":"Summons the oarsman.","Found":["Underground Caverns"]},
    {"Name":"Bat Card","Class":"Relic","Description":"Summons \"Bat\" Familiar.","Found":["Alchemy Laboratory"]},
    {"Name":"Ghost Card","Class":"Relic","Description":"Summons \"Ghost\" Familiar.","Found":["Castle Keep"]},
    {"Name":"Faerie Card","Class":"Relic","Description":"Summons \"Faerie\" Familiar.","Found":["Long Library"]},
    {"Name":"Demon Card","Class":"Relic","Description":"Summons \"Demon\" Familiar.","Found":["Abandoned Mine"]},
    {"Name":"Sword Card","Class":"Relic","Description":"Summons \"Sword\" Familiar.","Found":["Olrox's Quarters"]},
    {"Name":"Heart of Vlad","Class":"Relic","Description":"1 of 5 Treasures. Garante imunidade a maldições.","Found":["Anti-Chapel"]},
    {"Name":"Tooth of Vlad","Class":"Relic","Description":"1 of 5 Treasures. STR+10.","Strength":10,"Found":["Reverse Outer Wall"]},
    {"Name":"Rib of Vlad","Class":"Relic","Description":"1 of 5 Treasures. CON+10.","Constitution":10,"Found":["Death Wing's Lair"]},
    {"Name":"Ring of Vlad","Class":"Relic","Description":"1 of 5 Treasures. INT+10.","Intelligence":10,"Found":["Reverse Clock Tower"]},
    {"Name":"Eye of Vlad","Class":"Relic","Description":"1 of 5 Treasures. LCK+10.","Luck":10,"Found":["Cave"]}
  ],
  enemies: [
    {"ID":1,"Name":"Dracula","Description":"Destroyed by Richter in 1792. (5 years ago)","Blood":false,"LV":"?","EXP":0,"HP":600,"STR":"?","DEF":"?","Found":["Final Stage Bloodlines"]},
    {"ID":2,"Name":"Blood Skeleton","Description":"Revives due to blood soaked bones.","Blood":false,"LV":0,"EXP":0,"HP":9,"STR":8,"DEF":0,"Found":["Alchemy Laboratory","Catacombs","Floating Catacombs"]},
    {"ID":3,"Name":"Bat","Description":"Vampire bats. Feared as servants of evil.","Blood":true,"LV":1,"EXP":10,"HP":1,"STR":16,"DEF":0,"Found":["Entrance","Royal Chapel","Underground Caverns","Cave","Floating Catacombs"],"Drop1":"Potion","Drop2":"Monster vial 2"},
    {"ID":4,"Name":"Stone Skull","Description":"Indestructible spinning skull. (Exists in bull and human forms.)","Blood":false,"LV":1,"EXP":0,"HP":"?","STR":60,"DEF":"?","Found":["Black Marble Gallery","Reverse Outer Wall"]},
    {"ID":5,"Name":"Zombie","Description":"Fresh corpses. Magically animated.","Blood":false,"LV":1,"EXP":5,"HP":1,"STR":14,"DEF":0,"Weak":"FIR,HOL","Found":["Entrance"],"Drop1":"$100","Drop2":"Cloth tunic"},
    {"ID":6,"Name":"Merman2","Description":"Legendary \"creature\". Attacks all invaders.","Blood":true,"LV":2,"EXP":12,"HP":10,"STR":13,"DEF":0,"Strong":"H2O","Weak":"FIR,THU","Found":["Entrance"],"Drop1":"Zircon","Drop2":"Monster vial 1"},
    {"ID":7,"Name":"Skeleton","Description":"Magically animated skeleton.","Blood":false,"LV":2,"EXP":10,"HP":9,"STR":2,"DEF":0,"Weak":"HOL","Found":["Alchemy Laboratory","Marble Gallery","Outer Wall","Floating Catacombs"],"Drop1":"Shield potion","Drop2":"Monster vial 3"},
    {"ID":8,"Name":"Warg","Description":"Wolves which guards castle entrance.","Blood":true,"LV":2,"EXP":10,"HP":32,"STR":20,"DEF":0,"Weak":"FIR","Found":["Entrance"]},
    {"ID":9,"Name":"Bone Scimitar","Description":"Ferocious skeleton swordsman.","Blood":false,"LV":3,"EXP":15,"HP":18,"STR":5,"DEF":2,"Found":["Entrance","Alchemy Laboratory"],"Drop1":"Short sword","Drop2":"Red Rust"},
    {"ID":10,"Name":"Merman3","Description":"Fireball-spitting Merman. Largest of merman kind.","Blood":true,"LV":3,"EXP":12,"HP":10,"STR":14,"DEF":0,"Strong":"H2O","Weak":"FIR,THU","Found":["Entrance"],"Drop1":"Zircon","Drop2":"Monster vial 1"},
    {"ID":11,"Name":"Spittle Bone","Description":"4-legged skeleton. Drips poison.","Blood":false,"LV":3,"EXP":20,"HP":18,"STR":7,"DEF":3,"Weak":"HOL","Found":["Alchemy Laboratory"]},
    {"ID":12,"Name":"Axe Knight4","Description":"Low level axe knight.","Blood":false,"LV":4,"EXP":10,"HP":32,"STR":6,"DEF":3,"Weak":"HIT","Found":["Alchemy Laboratory","Marble Gallery"],"Drop1":"Axe","Drop2":"Bronze cuirass"},
    {"ID":13,"Name":"Bloody Zombie","Description":"Eastern Church soldiers dispatched 300 years ago.","Blood":true,"LV":4,"EXP":15,"HP":24,"STR":10,"DEF":3,"Weak":"FIR,HOL","Found":["Entrance","Alchemy Laboratory"],"Drop1":"Cloth tunic","Drop2":"Basilard"},
    {"ID":14,"Name":"Slinger","Description":"Bone-hurling skeleton.","Blood":false,"LV":4,"EXP":10,"HP":12,"STR":5,"DEF":0,"Weak":"HOL","Found":["Marble Gallery"],"Drop1":"Leather shield","Drop2":"Knight shield"},
    {"ID":15,"Name":"Ouija Table","Description":"Possessed Ouija table.","Blood":false,"LV":5,"EXP":20,"HP":20,"STR":4,"DEF":0,"Found":["Marble Gallery"],"Drop1":"Barley tea","Drop2":"Morning set"},
    {"ID":16,"Name":"Skelerang","Description":"Boomerang wielding skeleton.","Blood":false,"LV":5,"EXP":15,"HP":18,"STR":12,"DEF":0,"Weak":"HOL","Found":["Marble Gallery","Royal Chapel","Olrox's Quarters"],"Drop1":"Boomerang","Drop2":"Fire boomerang"},
    {"ID":17,"Name":"Thornweed","Description":"Plant with razor-sharp leaves.","Blood":false,"LV":5,"EXP":20,"HP":12,"STR":10,"DEF":0,"Strong":"HIT","Weak":"FIR","Found":["Abandoned Mine","Catacombs","Black Marble Gallery"],"Drop1":"Grapes","Drop2":"Strawberry"},
    {"ID":18,"Name":"Gaibon","Description":"Fire-breathing flying demon.","Blood":false,"LV":6,"EXP":200,"HP":200,"STR":7,"DEF":0,"Found":["Entrance","Alchemy Laboratory","Cave"]},
    {"ID":19,"Name":"Ghost","Description":"Low level flaming ghosts. (Can be avoided with a shield.)","Blood":false,"LV":6,"EXP":10,"HP":11,"STR":5,"DEF":0,"Strong":"DRK","Weak":"HOL","Found":["Marble Gallery"],"Drop1":"$400","Drop2":"Antivenom"},
    {"ID":20,"Name":"Marionette","Description":"Demonic puppet from Hell.","Blood":false,"LV":6,"EXP":30,"HP":20,"STR":8,"DEF":8,"Weak":"FIR","Found":["Marble Gallery"],"Drop1":"Smart potion","Drop2":"Circlet"},
    {"ID":21,"Name":"Slogra","Description":"Demon with enchanted spear.","Blood":false,"LV":6,"EXP":200,"HP":200,"STR":6,"DEF":0,"Found":["Entrance","Alchemy Laboratory","Cave"]},
    {"ID":22,"Name":"Diplocephalus","Description":"Nauseating two-headed beast. Which is the head?","Blood":true,"LV":7,"EXP":50,"HP":80,"STR":6,"DEF":0,"Strong":"H2O","Weak":"FIR,HOL","Found":["Marble Gallery"],"Drop1":"Pentagram","Drop2":"Tart"},
    {"ID":23,"Name":"Flea Man","Description":"Strange human-like creature.","Blood":true,"LV":7,"EXP":17,"HP":11,"STR":9,"DEF":0,"Found":["Marble Gallery","Long Library"],"Drop1":"Takemitsu","Drop2":"Cheese"},
    {"ID":24,"Name":"Medusa Head7","Description":"From Medusa's hair.","Blood":true,"LV":7,"EXP":20,"HP":12,"STR":12,"DEF":0,"Immune":"STN","Found":["Outer Wall","Clock Tower","Black Marble Gallery"],"Drop1":"Resist stone","Drop2":"Medusa shield"},
    {"ID":25,"Name":"Blade Soldier","Description":"Novice of twin-bladed combat.","Blood":false,"LV":8,"EXP":20,"HP":16,"STR":15,"DEF":4,"Found":["Colosseum"],"Drop1":"$400","Drop2":"Namakura"},
    {"ID":26,"Name":"Bone Musket","Description":"Skeleton equipped with rifles.","Blood":false,"LV":8,"EXP":20,"HP":24,"STR":12,"DEF":5,"Weak":"HOL","Found":["Outer Wall","Colosseum"],"Drop1":"Magic Missile","Drop2":"Talisman"},
    {"ID":27,"Name":"Medusa Head8","Description":"From Medusa's hair. Can \"petrifify\".","Blood":true,"LV":8,"EXP":30,"HP":12,"STR":7,"DEF":0,"Absorb":"STN","Found":["Outer Wall","Clock Tower","Black Marble Gallery","Reverse Clock Tower"],"Drop1":"Resist stone","Drop2":"Medusa shield"},
    {"ID":28,"Name":"Plate Lord","Description":"Heavily armored knight with iron ball.","Blood":false,"LV":8,"EXP":90,"HP":90,"STR":18,"DEF":6,"Found":["Marble Gallery","Colosseum"],"Drop1":"Iron ball","Drop2":"Neutron bomb"},
    {"ID":29,"Name":"Stone Rose","Description":"Mutated plant. Seeds petrify.","Blood":false,"LV":8,"EXP":60,"HP":60,"STR":12,"DEF":12,"Strong":"H2O","Weak":"CUT","Absorb":"DRK","Found":["Marble Gallery"],"Drop1":"Leather shield","Drop2":"Meal ticket"},
    {"ID":30,"Name":"Axe Knight9","Description":"Well armored axe knight.","Blood":false,"LV":9,"EXP":50,"HP":42,"STR":10,"DEF":6,"Found":["Outer Wall","Castle Keep","Colosseum"],"Drop1":"Axe","Drop2":"AxeLord shield"},
    {"ID":31,"Name":"Ctulhu","Description":"Fire and ice demon. Seems reluctant to fight.","Blood":false,"LV":9,"EXP":100,"HP":200,"STR":24,"DEF":2,"Strong":"DRK","Weak":"HOL","Found":["Marble Gallery","Necromancy Laboratory"],"Drop1":"Pentagram","Drop2":"Bat Pentagram"},
    {"ID":32,"Name":"Bone Archer","Description":"Skeleton archer equipped with bow.","Blood":false,"LV":10,"EXP":50,"HP":10,"STR":12,"DEF":2,"Found":["Outer Wall","Underground Caverns"],"Drop1":"$400","Drop2":"Magic Missile"},
    {"ID":33,"Name":"Bone Pillar","Description":"Cannon built of white dragon skulls.","Blood":false,"LV":10,"EXP":30,"HP":64,"STR":12,"DEF":2,"Weak":"HOL","Found":["Royal Chapel"],"Drop1":"Antivenom","Drop2":"Ballroom mask"},
    {"ID":34,"Name":"Doppleganger10","Description":"Shape-shifting demon.","Blood":true,"LV":10,"EXP":500,"HP":120,"STR":7,"DEF":5,"Found":["Outer Wall"]},
    {"ID":35,"Name":"Owl","Description":"Local barnyard owl Mutated by castle's influence.","Blood":true,"LV":10,"EXP":30,"HP":26,"STR":20,"DEF":0,"Weak":"FIR","Found":["Entrance","Colosseum"]},
    {"ID":36,"Name":"Phantom Skull","Description":"Executed soldier's head. Hunting for vengeance.","Blood":false,"LV":10,"EXP":30,"HP":15,"STR":14,"DEF":0,"Strong":"DRK","Weak":"HOL","Found":["Clock Tower"],"Drop1":"Felt hat","Drop2":"Resist dark"},
    {"ID":37,"Name":"Scylla wyrm","Description":"Snake living off Scylla.","Blood":false,"LV":10,"EXP":100,"HP":130,"STR":14,"DEF":3,"Weak":"THU","Found":["Underground Caverns"]},
    {"ID":38,"Name":"Skeleton Ape","Description":"Animated ape skeleton. Hurls wooden barrels.","Blood":false,"LV":10,"EXP":30,"HP":10,"STR":10,"DEF":2,"Weak":"HOL","Found":["Outer Wall","Underground Caverns"],"Drop1":"Banana","Drop2":"TNT"},
    {"ID":39,"Name":"Spear Guard","Description":"Armored warrior with naginata.","Blood":false,"LV":10,"EXP":70,"HP":20,"STR":12,"DEF":4,"Weak":"HOL","Found":["Outer Wall","Underground Caverns"],"Drop1":"Javelin","Drop2":"Iron cuirass"},
    {"ID":40,"Name":"Spellbook","Description":"Book of beginner's spells.","Blood":false,"LV":10,"EXP":30,"HP":26,"STR":7,"DEF":0,"Strong":"HIT","Weak":"FIR","Found":["Long Library"],"Drop1":"$1000","Drop2":"Pentagram"},
    {"ID":41,"Name":"Winged Guard","Description":"Slow-flying skeleton warrior.","Blood":false,"LV":10,"EXP":30,"HP":15,"STR":12,"DEF":0,"Found":["Royal Chapel"],"Drop1":"Iron shield","Drop2":"Javelin"},
    {"ID":42,"Name":"Ectoplasm","Description":"Physical manifestations of bodiless tormented souls.","Blood":false,"LV":11,"EXP":70,"HP":18,"STR":6,"DEF":0,"Strong":"CUT","Weak":"FIR,HOL","Found":["Long Library"],"Drop1":"Uncurse","Drop2":"Manna prism"},
    {"ID":43,"Name":"Sword Lord","Description":"Knight armed with Greatsword.","Blood":false,"LV":11,"EXP":80,"HP":61,"STR":12,"DEF":8,"Found":["Outer Wall","Clock Tower"],"Drop1":"Cutlass","Drop2":"Bekatowa"},
    {"ID":44,"Name":"Toad","Description":"Toad magically enlarged by demonic baptism.","Blood":true,"LV":11,"EXP":20,"HP":10,"STR":14,"DEF":4,"Strong":"H2O","Weak":"FIR,THU","Found":["Underground Caverns"],"Drop1":"Blue knuckles","Drop2":"Pizza"},
    {"ID":45,"Name":"Armor Lord","Description":"Heavily armored undead warrior.","Blood":false,"LV":12,"EXP":100,"HP":84,"STR":18,"DEF":6,"Strong":"CUT","Found":["Outer Wall","Colosseum"],"Drop1":"Rapier","Drop2":"Saber"},
    {"ID":46,"Name":"Corner Guard","Description":"Armored guard. Strong in perilous areas.","Blood":false,"LV":12,"EXP":30,"HP":48,"STR":13,"DEF":3,"Found":["Royal Chapel"],"Drop1":"Cutlass","Drop2":"Damascus sword"},
    {"ID":47,"Name":"Dhuron","Description":"Headless skeleton. Wields a rapier.","Blood":false,"LV":12,"EXP":50,"HP":32,"STR":7,"DEF":3,"Weak":"HOL","Found":["Long Library"],"Drop1":"Hide cuirass","Drop2":"Rapier"},
    {"ID":48,"Name":"Frog","Description":"Cave-dwelling frog.","Blood":true,"LV":12,"EXP":20,"HP":2,"STR":13,"DEF":1,"Strong":"H2O","Weak":"FIR,THU","Found":["Underground Caverns"],"Drop1":"Knuckle duster","Drop2":"Pizza"},
    {"ID":49,"Name":"Frozen Shade","Description":"Ice-wielding female spirit.","Blood":false,"LV":12,"EXP":40,"HP":16,"STR":16,"DEF":0,"Immune":"H2O","Weak":"FIR","Absorb":"ICE","Found":["Underground Caverns"],"Drop1":"Ice mail","Drop2":"Ice cream"},
    {"ID":50,"Name":"Magic Tome","Description":"Book of ancient weapons.","Blood":false,"LV":12,"EXP":35,"HP":22,"STR":12,"DEF":2,"Strong":"HIT","Weak":"FIR","Found":["Long Library"],"Drop1":"$2000","Drop2":"Saber"},
    {"ID":51,"Name":"Skull Lord","Description":"Giant skull spirit.","Blood":false,"LV":12,"EXP":50,"HP":80,"STR":25,"DEF":4,"Strong":"DRK","Weak":"HOL","Found":["Clock Tower"],"Drop1":"Scimitar","Drop2":"Skull shield"},
    {"ID":52,"Name":"Black Crow","Description":"Flesh-eating raven.","Blood":true,"LV":13,"EXP":50,"HP":15,"STR":10,"DEF":0,"Strong":"THU","Found":["Royal Chapel"],"Drop1":"Aquamarine","Drop2":"Red bean bun"},
    {"ID":53,"Name":"Blue Raven","Description":"Spirit of long-dead blue raven.","Blood":true,"LV":13,"EXP":50,"HP":15,"STR":10,"DEF":0,"Strong":"THU","Found":["Royal Chapel"],"Drop1":"Zircon","Drop2":"Pork bun"},
    {"ID":54,"Name":"Corpseweed","Description":"Plant with razor-sharp leaves.","Blood":false,"LV":13,"EXP":100,"HP":18,"STR":20,"DEF":0,"Strong":"HIT","Weak":"FIR","Found":["Abandoned Mine"],"Drop1":"Antivenom","Drop2":"Potion"},
    {"ID":55,"Name":"Flail Guard","Description":"Skeleton equipped with spiked iron flail.","Blood":false,"LV":13,"EXP":50,"HP":36,"STR":14,"DEF":2,"Weak":"HOL","Found":["Clock Tower"],"Drop1":"Morningstar","Drop2":"Pot roast"},
    {"ID":56,"Name":"Flea Rider","Description":"Flea Man riding on specially trained war-goose.","Blood":true,"LV":13,"EXP":50,"HP":17,"STR":18,"DEF":0,"Found":["Castle Keep"],"Drop1":"Turkey","Drop2":"Ham and eggs"},
    {"ID":57,"Name":"Spectral Sword13","Description":"Evil demon-sword. Causes poltergeist phenomena.","Blood":false,"LV":13,"EXP":80,"HP":90,"STR":25,"DEF":4,"Found":["Alchemy Laboratory"],"Drop1":"Broadsword","Drop2":"Bastard sword"},
    {"ID":58,"Name":"Bone Halberd","Description":"Naginata-wielding skeleton.","Blood":false,"LV":14,"EXP":40,"HP":30,"STR":12,"DEF":2,"Weak":"HOL","Found":["Royal Chapel"],"Drop1":"Javelin","Drop2":"Ham and eggs"},
    {"ID":59,"Name":"Scylla","Description":"Mythological sea monster.","Blood":false,"LV":14,"EXP":500,"HP":200,"STR":18,"DEF":0,"Weak":"THU","Found":["Underground Caverns"]},
    {"ID":60,"Name":"Hunting Girl","Description":"Invisible huntress spirit.","Blood":false,"LV":15,"EXP":70,"HP":88,"STR":18,"DEF":0,"Strong":"CUT,HOL","Found":["Royal Chapel","Colosseum"],"Drop1":"Were Bane","Drop2":"Cheesecake"},
    {"ID":61,"Name":"Mudman","Description":"Animated mud golem. (Generated by Lesser Demon Boss.)","Blood":false,"LV":15,"EXP":50,"HP":15,"STR":20,"DEF":0,"Found":["Long Library"]},
    {"ID":62,"Name":"Owl Knight","Description":"Heavily armored knight. Attacks with trained owl.","Blood":false,"LV":15,"EXP":50,"HP":180,"STR":17,"DEF":2,"Strong":"CUT","Found":["Entrance","Colosseum"],"Drop1":"Cutlass","Drop2":"Medal"},
    {"ID":63,"Name":"Spectral Sword15","Description":"Evil demon-sword. Causes poltergeist phenomena.","Blood":false,"LV":15,"EXP":100,"HP":100,"STR":25,"DEF":6,"Found":["Royal Chapel"],"Drop1":"Broadsword","Drop2":"Bastard sword"},
    {"ID":64,"Name":"Vandal Sword","Description":"Sword Lord wields sword even when banished.","Blood":false,"LV":15,"EXP":100,"HP":120,"STR":30,"DEF":0,"Strong":"HIT","Found":["Clock Tower"],"Drop1":"Holy sword","Drop2":"Muramasa"},
    {"ID":65,"Name":"Flea Armor","Description":"Flea Man armed with axe and shield.","Blood":false,"LV":16,"EXP":40,"HP":18,"STR":17,"DEF":0,"Found":["Clock Tower"],"Drop1":"High potion","Drop2":"Iron cuirass"},
    {"ID":66,"Name":"Hippogryph","Description":"Part horse, lion and eagle.","Blood":false,"LV":16,"EXP":800,"HP":800,"STR":16,"DEF":0,"Strong":"THU","Found":["Royal Chapel"]},
    {"ID":67,"Name":"Paranthropus","Description":"Giant skeleton. (You can step on its head.)","Blood":false,"LV":16,"EXP":50,"HP":100,"STR":24,"DEF":0,"Weak":"HOL","Found":["Colosseum","Reverse Outer Wall"],"Drop1":"Gauntlet","Drop2":"Ring of Varda"},
    {"ID":68,"Name":"Slime","Description":"Monster made from gel.","Blood":false,"LV":16,"EXP":50,"HP":32,"STR":16,"DEF":10,"Immune":"CUT","Weak":"FIR","Found":["Catacombs"]},
    {"ID":69,"Name":"Blade Master","Description":"Master of twin-bladed combat.","Blood":false,"LV":17,"EXP":80,"HP":65,"STR":20,"DEF":4,"Found":["Colosseum"],"Drop1":"Shotel","Drop2":"Cross shuriken"},
    {"ID":70,"Name":"Wereskeleton","Description":"Were panther skeleton.","Blood":false,"LV":17,"EXP":50,"HP":33,"STR":20,"DEF":4,"Weak":"HOL","Found":["Catacombs"],"Drop1":"Str. potion","Drop2":"Garnet"},
    {"ID":71,"Name":"Grave Keeper","Description":"Grave Keeper. Master of unarmed combat.","Blood":true,"LV":18,"EXP":60,"HP":123,"STR":20,"DEF":0,"Weak":"FIR,ICE,THU","Found":["Colosseum","Catacombs"],"Drop1":"Miso soup","Drop2":"Natou"},
    {"ID":72,"Name":"Gremlin","Description":"Pyromaniacal gremlin.","Blood":false,"LV":18,"EXP":60,"HP":100,"STR":20,"DEF":0,"Strong":"FIR","Weak":"ICE","Found":["Abandoned Mine","Catacombs","Necromancy Laboratory"],"Drop1":"Resist fire","Drop2":"Fire mail"},
    {"ID":73,"Name":"Harpy","Description":"Creature with head of woman and body of bird.","Blood":false,"LV":18,"EXP":70,"HP":26,"STR":18,"DEF":0,"Strong":"THU","Found":["Clock Tower"],"Drop1":"Apple","Drop2":"Life apple"},
    {"ID":74,"Name":"Minotaurus","Description":"Bull-headed monster.","Blood":false,"LV":18,"EXP":400,"HP":300,"STR":20,"DEF":3,"Found":["Colosseum"]},
    {"ID":75,"Name":"Werewolf18","Description":"Shape-shifting lycanthrope.","Blood":false,"LV":18,"EXP":300,"HP":260,"STR":20,"DEF":1,"Found":["Colosseum"]},
    {"ID":76,"Name":"Bone Ark","Description":"Portable skull shrine carried by skeleton priests.","Blood":false,"LV":19,"EXP":40,"HP":250,"STR":20,"DEF":4,"Weak":"FIR,HOL","Found":["Catacombs"],"Drop1":"Monster vial 3","Drop2":"Skull shield"},
    {"ID":77,"Name":"Valhalla Knight","Description":"Bloodthirsty undead knight who eternally seeks combat.","Blood":false,"LV":19,"EXP":100,"HP":161,"STR":16,"DEF":0,"Weak":"HOL","Found":["Colosseum","Reverse Clock Tower"],"Drop1":"Estoc","Drop2":"Claymore"},
    {"ID":78,"Name":"Cloaked knight","Description":"Mysterious cloaked swordsman.","Blood":false,"LV":20,"EXP":80,"HP":65,"STR":20,"DEF":1,"Found":["Clock Tower","Reverse Clock Tower"],"Drop1":"Flamberge","Drop2":"Heaven sword"},
    {"ID":79,"Name":"Fishhead","Description":"Fish head guardian.","Blood":false,"LV":20,"EXP":50,"HP":70,"STR":15,"DEF":2,"Strong":"FIR","Weak":"HOL","Found":["Underground Caverns"],"Drop1":"Resist ice","Drop2":"Icebrand"},
    {"ID":80,"Name":"Lesser Demon","Description":"Short magic-wielding demon. Summons demonic allies.","Blood":true,"LV":20,"EXP":100,"HP":400,"STR":20,"DEF":5,"Immune":"DRK","Weak":"HOL","Found":["Long Library","Necromancy Laboratory"],"Drop1":"Obsidian sword","Drop2":"Holbein dagger"},
    {"ID":81,"Name":"Lossoth","Description":"Searches among graves and knows much wise lore.","Blood":true,"LV":20,"EXP":50,"HP":99,"STR":18,"DEF":0,"Found":["Catacombs"],"Drop1":"Sirloin","Drop2":"Firebrand"},
    {"ID":82,"Name":"Salem Witch","Description":"Ghost witches from Salem.","Blood":false,"LV":20,"EXP":80,"HP":180,"STR":20,"DEF":0,"Found":["Abandoned Mine","Necromancy Laboratory"],"Drop1":"Gold circlet","Drop2":"Shortcake"},
    {"ID":83,"Name":"Blade","Description":"Eldest Giant brother. Wields two huge daggers.","Blood":false,"LV":21,"EXP":100,"HP":380,"STR":24,"DEF":24,"Found":["Entrance","Black Marble Gallery"],"Drop1":"Hunter sword","Drop2":"Gold Plate"},
    {"ID":84,"Name":"Gurkha","Description":"Giant brother. Wields a gurkha knife.","Blood":false,"LV":21,"EXP":120,"HP":420,"STR":24,"DEF":0,"Found":["Entrance","Black Marble Gallery"],"Drop1":"Combat Knife","Drop2":"Gold Plate"},
    {"ID":85,"Name":"Hammer","Description":"Giant brother. Uses a huge steel hammer.","Blood":false,"LV":21,"EXP":110,"HP":250,"STR":20,"DEF":0,"Found":["Black Marble Gallery"],"Drop1":"Hammer","Drop2":"Gold Plate"},
    {"ID":86,"Name":"Discus Lord","Description":"Discus-wielding armored knight.","Blood":false,"LV":22,"EXP":140,"HP":450,"STR":29,"DEF":10,"Found":["Catacombs"],"Drop1":"Chakram","Drop2":"Jewel sword"},
    {"ID":87,"Name":"Karasuman","Description":"Demon Lord of Ravens.","Blood":false,"LV":22,"EXP":1000,"HP":500,"STR":20,"DEF":10,"Strong":"DRK","Found":["Clock Tower","Death Wing's Lair"],"Drop1":"Resist dark","Drop2":"Ring of Feanor"},
    {"ID":88,"Name":"Large Slime","Description":"Monster created from slimy gel substance.","Blood":false,"LV":22,"EXP":100,"HP":64,"STR":32,"DEF":10,"Immune":"CUT","Weak":"FIR","Found":["Catacombs"]},
    {"ID":89,"Name":"Hellfire Beast","Description":"Thunder-wielding demon. \"Called Musician from Hell\".","Blood":false,"LV":23,"EXP":150,"HP":380,"STR":17,"DEF":8,"Found":["Catacombs"],"Drop1":"Lightning mail","Drop2":"Fire mail"},
    {"ID":90,"Name":"Cerberos","Description":"Watchdog of Hell.","Blood":false,"LV":24,"EXP":1500,"HP":800,"STR":20,"DEF":0,"Weak":"ICE","Absorb":"FIR","Found":["Abandoned Mine"]},
    {"ID":91,"Name":"Killer Fish","Description":"Master Fish-head.","Blood":false,"LV":25,"EXP":100,"HP":120,"STR":50,"DEF":4,"Strong":"FIR,H2O","Weak":"THU","Found":["Underground Caverns","Reverse Caverns"],"Drop1":"Aquamarine","Drop2":"Sushi"},
    {"ID":92,"Name":"Olrox","Description":"Magic-wielding vampire. Rules upper part of castle.","Blood":false,"LV":25,"EXP":500,"HP":666,"STR":0,"DEF":0,"Strong":"DRK","Found":["Olrox's Quarters"]},
    {"ID":93,"Name":"Succubus","Description":"Female demon. Invades men's dreams.","Blood":false,"LV":25,"EXP":2000,"HP":666,"STR":255,"DEF":0,"Strong":"DRK","Found":["Nightmare"]},
    {"ID":94,"Name":"Tombstone","Description":"Gravestone possessed by evil spirits of dead.","Blood":false,"LV":25,"EXP":88,"HP":5,"STR":40,"DEF":100,"Strong":"CUT","Immune":"STN","Weak":"HIT","Found":["Reverse-Keep"],"Drop1":"Katana","Drop2":"Green tea"},
    {"ID":95,"Name":"Venus Weed","Description":"Watered with human blood.","Blood":false,"LV":25,"EXP":150,"HP":500,"STR":28,"DEF":0,"Weak":"FIR","Found":["Abandoned Mine"],"Drop1":"Coral circlet","Drop2":"Heart Refresh"},
    {"ID":96,"Name":"Lion","Description":"The cowardly lion.","Blood":false,"LV":27,"EXP":1000,"HP":150,"STR":37,"DEF":25,"Found":["Forbidden Library"],"Drop1":"Gauntlet","Drop2":"Fist of Tulkas"},
    {"ID":97,"Name":"Scarecrow","Description":"Impaled man looking for brain.","Blood":false,"LV":27,"EXP":1000,"HP":120,"STR":120,"DEF":6,"Found":["Forbidden Library"],"Drop1":"Javelin","Drop2":"Muramasa"},
    {"ID":98,"Name":"Granfaloon","Description":"Nightmarish creature. Composed of many.","Blood":false,"LV":28,"EXP":3000,"HP":400,"STR":0,"DEF":0,"Strong":"DRK","Weak":"HOL","Found":["Catacombs"]},
    {"ID":99,"Name":"Schmoo","Description":"Monster nicknamed \"Schmoo\".","Blood":false,"LV":28,"EXP":1000,"HP":50,"STR":40,"DEF":0,"Weak":"FIR,HOL","Found":["Forbidden Library"],"Drop1":"Ramen","Drop2":"Crissaegrim"},
    {"ID":100,"Name":"Tin man","Description":"Heartless tin man.","Blood":false,"LV":28,"EXP":1000,"HP":48,"STR":32,"DEF":36,"Strong":"CUT","Found":["Forbidden Library"],"Drop1":"Lunch A","Drop2":"Mojo mail"},
    {"ID":101,"Name":"Balloon pod","Description":"Holds countless poison seeds.","Blood":false,"LV":29,"EXP":88,"HP":3,"STR":55,"DEF":0,"Found":["Anti-Chapel","Reverse Caverns"]},
    {"ID":102,"Name":"Yorick","Description":"Skeleton eternally chasing his own skull.","Blood":false,"LV":29,"EXP":300,"HP":10,"STR":20,"DEF":0,"Found":["Reverse-Keep"],"Drop1":"Monster vial 3","Drop2":"Skull shield"},
    {"ID":103,"Name":"Bomb Knight","Description":"Bomb-tossing armored knight.","Blood":false,"LV":30,"EXP":140,"HP":46,"STR":37,"DEF":20,"Found":["Reverse Clock Tower"],"Drop1":"TNT","Drop2":"Dynamite"},
    {"ID":104,"Name":"Flying Zombie","Description":"Zombies which attack even when cut in half.","Blood":true,"LV":32,"EXP":50,"HP":190,"STR":37,"DEF":10,"Weak":"FIR,HOL","Found":["Death Wing's Lair"],"Drop1":"Shuriken","Drop2":"Frankfurter"},
    {"ID":105,"Name":"Bitterfly","Description":"Mutated insect. Visible only to magicians.","Blood":false,"LV":33,"EXP":128,"HP":4,"STR":55,"DEF":0,"Found":["Necromancy Laboratory"],"Drop1":"Luck potion","Drop2":"Mystic pendant"},
    {"ID":106,"Name":"Jack O'Bones","Description":"Expert at throwing weapons.","Blood":false,"LV":33,"EXP":150,"HP":20,"STR":40,"DEF":4,"Weak":"HOL","Found":["Reverse Entrance","Black Marble Gallery","Reverse Outer Wall","Reverse Caverns"],"Drop1":"Shuriken","Drop2":"Flame star"},
    {"ID":107,"Name":"Archer","Description":"Fiendish accurate archer.","Blood":false,"LV":34,"EXP":140,"HP":300,"STR":40,"DEF":8,"Found":["Anti-Chapel"],"Drop1":"Heart Refresh","Drop2":"Vorpal Blade"},
    {"ID":108,"Name":"Werewolf34","Description":"Half-man, half-wolf.","Blood":false,"LV":34,"EXP":200,"HP":280,"STR":40,"DEF":1,"Found":["Reverse Coloseum"],"Drop1":"Iron Fist","Drop2":"Yasutsuna"},
    {"ID":109,"Name":"Black Panther","Description":"Liquid creature. Takes black panther shape.","Blood":false,"LV":35,"EXP":600,"HP":35,"STR":45,"DEF":0,"Weak":"FIR","Found":["Anti-Chapel"],"Drop1":"Meal ticket","Drop2":"Masamune"},
    {"ID":110,"Name":"Darkwing Bat","Description":"Giant vampire bat.","Blood":false,"LV":35,"EXP":1200,"HP":600,"STR":35,"DEF":0,"Found":["Reverse Clock Tower"]},
    {"ID":111,"Name":"Dragon Rider","Description":"White dragon ridden by Flea Man.","Blood":false,"LV":35,"EXP":150,"HP":120,"STR":41,"DEF":4,"Found":["Reverse Entrance"]},
    {"ID":112,"Name":"Minotaur","Description":"Half-man, half-bull.","Blood":false,"LV":35,"EXP":250,"HP":320,"STR":45,"DEF":4,"Found":["Reverse Coloseum"],"Drop1":"Sirloin","Drop2":"Fury plate"},
    {"ID":113,"Name":"Nova Skeleton","Description":"Wields fearsome beam weapon.","Blood":false,"LV":35,"EXP":444,"HP":20,"STR":20,"DEF":4,"Found":["Reverse Entrance","Black Marble Gallery","Reverse Outer Wall","Reverse Caverns"],"Drop1":"Monster vial 3","Drop2":"Terminus Est"},
    {"ID":114,"Name":"Orobourous","Description":"Wyrm controlled by Flea Man.","Blood":false,"LV":35,"EXP":150,"HP":200,"STR":47,"DEF":4,"Found":["Reverse Entrance"],"Drop1":"Karma Coin","Drop2":"Lapis lazuli"},
    {"ID":115,"Name":"White Dragon","Description":"Animated skeleton of huge dragon.","Blood":false,"LV":35,"EXP":150,"HP":260,"STR":1,"DEF":2,"Strong":"FIR","Weak":"HOL","Found":["Reverse Coloseum"]},
    {"ID":116,"Name":"Fire Warg","Description":"Fireball-spitting wolf.","Blood":false,"LV":36,"EXP":160,"HP":200,"STR":200,"DEF":0,"Immune":"FIR","Weak":"ICE","Found":["Reverse Entrance"],"Drop1":"Turquoise","Drop2":"Karma Coin"},
    {"ID":117,"Name":"Rock Knight","Description":"Rock-tossing armored knight.","Blood":false,"LV":36,"EXP":250,"HP":160,"STR":50,"DEF":20,"Found":["Reverse Caverns"],"Drop1":"Jewel knuckles","Drop2":"Platinum mail"},
    {"ID":118,"Name":"Sniper of Goth","Description":"Angel archer. Slew Amalaric of the Goths.","Blood":false,"LV":36,"EXP":200,"HP":50,"STR":40,"DEF":10,"Strong":"HOL","Weak":"DRK","Found":["Anti-Chapel"],"Drop1":"Magic Missile","Drop2":"Brilliant mail"},
    {"ID":119,"Name":"Spectral Sword36","Description":"Evil demon-sword. Causes poltergeist phenomena.","Blood":false,"LV":36,"EXP":400,"HP":540,"STR":55,"DEF":4,"Found":["Anti-Chapel"],"Drop1":"Gurthang","Drop2":"Mablung Sword"},
    {"ID":120,"Name":"Ghost Dancer","Description":"Skeleton with leaping attack.","Blood":false,"LV":37,"EXP":160,"HP":30,"STR":56,"DEF":0,"Weak":"HOL","Found":["Death Wing's Lair"],"Drop1":"Buffalo star","Drop2":"Stone mask"},
    {"ID":121,"Name":"Warg Rider","Description":"Skeleton mounted on warg.","Blood":false,"LV":37,"EXP":160,"HP":120,"STR":41,"DEF":3,"Strong":"CUT","Immune":"FIR","Weak":"ICE","Found":["Reverse Entrance"]},
    {"ID":122,"Name":"Cave Troll","Description":"Pre-intellingent bloosucker with long tongue for sucking.","Blood":true,"LV":38,"EXP":333,"HP":88,"STR":35,"DEF":5,"Strong":"H2O","Weak":"FIR","Found":["Reverse Caverns"],"Drop1":"Neutron bomb","Drop2":"Nauglamir"},
    {"ID":123,"Name":"Dark Octopus","Description":"Evil mutated octopus.","Blood":true,"LV":38,"EXP":120,"HP":280,"STR":45,"DEF":2,"Strong":"H2O","Weak":"FIR,THU","Found":["Reverse Caverns"],"Drop1":"Sushi","Drop2":"Green tea"},
    {"ID":124,"Name":"Fire Demon","Description":"Flame demon.","Blood":false,"LV":38,"EXP":666,"HP":320,"STR":45,"DEF":15,"Immune":"FIR","Found":["Necromancy Laboratory"],"Drop1":"Fire shield","Drop2":"Marsil"},
    {"ID":125,"Name":"Gorgon","Description":"Armor plated war-beast.","Blood":false,"LV":38,"EXP":555,"HP":240,"STR":35,"DEF":40,"Strong":"HIT,CUT,FIR,STN","Found":["Black Marble Gallery"],"Drop1":"Hammer","Drop2":"Stone sword"},
    {"ID":126,"Name":"Malachi","Description":"Gruesome Demon from Hell.","Blood":false,"LV":39,"EXP":666,"HP":450,"STR":52,"DEF":20,"Weak":"HOL","Absorb":"DRK","Found":["Necromancy Laboratory"],"Drop1":"Dark shield","Drop2":"Dark armor"},
    {"ID":127,"Name":"Akmodan II","Description":"Ancient egyptian mummy.","Blood":false,"LV":40,"EXP":2500,"HP":1200,"STR":40,"DEF":0,"Immune":"STN,PSN,CUR","Weak":"FIR,HOL","Absorb":"DRK","Found":["Death Wing's Lair"]},
    {"ID":128,"Name":"Blue Venus Weed","Description":"Advanced Venus Weed. Fed with demon blood.","Blood":false,"LV":40,"EXP":1000,"HP":550,"STR":45,"DEF":1,"Weak":"FIR","Found":["Reverse Entrance","Reverse Caverns"],"Drop1":"Zwei hander","Drop2":"Heart Refresh"},
    {"ID":129,"Name":"Doppleganger40","Description":"Shape-shifting demon.","Blood":true,"LV":40,"EXP":2001,"HP":777,"STR":35,"DEF":16,"Found":["Reverse Caverns"]},
    {"ID":130,"Name":"Medusa","Description":"Snake-headed demoness with gaze of stone.","Blood":false,"LV":40,"EXP":2500,"HP":1100,"STR":35,"DEF":8,"Strong":"HIT","Absorb":"STN","Found":["Anti-Chapel"]},
    {"ID":131,"Name":"The Creature","Description":"Made from the body parts of powerful warriors.","Blood":false,"LV":40,"EXP":2500,"HP":1100,"STR":30,"DEF":15,"Immune":"THU","Found":["Reverse Outer Wall"]},
    {"ID":132,"Name":"Fake Grant","Description":"Zombie impersonating Grant.","Blood":false,"LV":41,"EXP":1200,"HP":800,"STR":38,"DEF":4,"Found":["Reverse Coloseum"]},
    {"ID":133,"Name":"Fake Trevor","Description":"Zombie impersonating Trevor.","Blood":false,"LV":41,"EXP":1000,"HP":1200,"STR":38,"DEF":8,"Found":["Reverse Coloseum"]},
    {"ID":134,"Name":"Imp","Description":"Mischevious little demon.","Blood":false,"LV":41,"EXP":66,"HP":43,"STR":10,"DEF":0,"Found":["Necromancy Laboratory","Anti-Chapel","Reverse Caverns"],"Drop1":"Luck potion","Drop2":"King's stone"},
    {"ID":135,"Name":"Fake Sypha","Description":"Zombie impersonating Sypha.","Blood":false,"LV":42,"EXP":1500,"HP":1000,"STR":9,"DEF":2,"Found":["Reverse Coloseum"]},
    {"ID":136,"Name":"Beezelbub","Description":"Beelzebub Lord of Flies.","Blood":false,"LV":44,"EXP":4444,"HP":2000,"STR":60,"DEF":13,"Weak":"HOL","Absorb":"DRK","Found":["Necromancy Laboratory"]},
    {"ID":137,"Name":"Azaghal","Description":"Executioner of Hell.","Blood":false,"LV":45,"EXP":700,"HP":330,"STR":80,"DEF":22,"Strong":"HIT,DRK","Found":["Death Wing's Lair"],"Drop1":"Covenant stone","Drop2":"Mourneblade"},
    {"ID":138,"Name":"Frozen Half","Description":"New-half ice spirit. Servant of Galamoth.","Blood":false,"LV":45,"EXP":600,"HP":118,"STR":35,"DEF":2,"Strong":"H2O","Weak":"FIR","Absorb":"ICE","Found":["Floating Catacombs"],"Drop1":"Necklace of J","Drop2":"Opal circlet"},
    {"ID":139,"Name":"Salome","Description":"Young female witch.","Blood":false,"LV":45,"EXP":450,"HP":210,"STR":50,"DEF":2,"Found":["Floating Catacombs"],"Drop1":"Wizard hat","Drop2":"Manna prism"},
    {"ID":140,"Name":"Richter Belmont","Description":"Master Vampire hunter.","Blood":true,"LV":48,"EXP":0,"HP":400,"STR":25,"DEF":10,"Immune":"HOL,STN","Weak":"DRK","Found":["Castle Keep"]},
    {"ID":141,"Name":"Dodo Bird","Description":"Rare bird. Runs when sees people.","Blood":false,"LV":49,"EXP":111,"HP":2,"STR":1,"DEF":0,"Found":["Reverse Entrance"],"Drop1":"Heart Broach","Drop2":"Runesword"},
    {"ID":142,"Name":"Galamoth","Description":"Magical being with plan to rule the netherworld.","Blood":false,"LV":50,"EXP":9999,"HP":12000,"STR":50,"DEF":56,"Found":["Floating Catacombs"]},
    {"ID":143,"Name":"Guardian","Description":"High level Armor Lord.","Blood":false,"LV":60,"EXP":1500,"HP":500,"STR":50,"DEF":34,"Strong":"CUT","Immune":"FIR,ICE,THU","Absorb":"DRK","Found":["Black Marble Gallery"],"Drop1":"Great Sword","Drop2":"God's Garb"},
    {"ID":144,"Name":"Death","Description":"Dracula's close friend.","Blood":false,"LV":66,"EXP":4444,"HP":888,"STR":0,"DEF":0,"Weak":"HOL","Absorb":"DRK","Found":["Cave"]},
    {"ID":145,"Name":"Shaft","Description":"Dark Priest of Dracula.","Blood":false,"LV":88,"EXP":0,"HP":1300,"STR":40,"DEF":30,"Immune":"PSN","Found":["Black Marble Gallery"]},
    {"ID":146,"Name":"Lord Dracula","Description":"Lord of Wallachia. Father of Alucard.","Blood":false,"LV":98,"EXP":0,"HP":10000,"STR":70,"DEF":18,"Strong":"FIR,THU","Immune":"PSN","Absorb":"DRK","Found":["Black Marble Gallery"]}
  ],
  attacks: [
    {"Name":"Fire Ball","Enemy":"Merman2","ATT":20,"Type":"FIR"},
    {"Name":"Body Slam","Enemy":"Merman2","ATT":13,"Type":"HIT"},
    {"Name":"Bone Throw","Enemy":"Skeleton","ATT":8,"Type":"HIT"},
    {"Name":"Bite","Enemy":"Warg","ATT":28,"Type":"CUT"},
    {"Name":"Sword Swing","Enemy":"Bone Scimitar","ATT":5,"Type":"HIT"},
    {"Name":"Fire Ball","Enemy":"Merman3","ATT":24,"Type":"FIR"},
    {"Name":"Poison Drip","Enemy":"Spittle Bone","ATT":5,"Type":"PSN"},
    {"Name":"Axe","Enemy":"Axe Knight4","ATT":8,"Type":"CUT"},
    {"Name":"Knife","Enemy":"Bloody Zombie","ATT":10,"Type":"CUT"},
    {"Name":"Bone Throw","Enemy":"Slinger","ATT":8,"Type":"HIT"},
    {"Name":"Telekinesis","Enemy":"Ouija Table","ATT":5,"Type":"HIT"},
    {"Name":"Boomerang","Enemy":"Skelerang","ATT":18,"Type":"HIT"},
    {"Name":"Fire Ball","Enemy":"Gaibon","ATT":8,"Type":"FIR"},
    {"Name":"Fire Cannon","Enemy":"Gaibon","ATT":12,"Type":"FIR"},
    {"Name":"Beak","Enemy":"Slogra","ATT":6,"Type":"HIT"},
    {"Name":"Enchanted Spear","Enemy":"Slogra","ATT":9,"Type":"CUT"},
    {"Name":"Spear Shot","Enemy":"Slogra","ATT":10,"Type":"HIT"},
    {"Name":"Fire Ball","Enemy":"Diplocephalus","ATT":12,"Type":"FIR"},
    {"Name":"Blade","Enemy":"Blade Soldier","ATT":20,"Type":"CUT"},
    {"Name":"Rifle Shot","Enemy":"Bone Musket","ATT":45,"Type":"HIT"},
    {"Name":"Stone Touch","Enemy":"Medusa Head8","ATT":7,"Type":"STN"},
    {"Name":"Iron Ball","Enemy":"Plate Lord","ATT":35,"Type":"HIT"},
    {"Name":"Stone Seed","Enemy":"Stone Rose","ATT":5,"Type":"PSN"},
    {"Name":"Seed","Enemy":"Stone Rose","ATT":6,"Type":"HIT"},
    {"Name":"Axe","Enemy":"Axe Knight9","ATT":14,"Type":"CUT"},
    {"Name":"Axe Rush","Enemy":"Axe Knight9","ATT":14,"Type":"CUT"},
    {"Name":"Fire Ball","Enemy":"Ctulhu","ATT":38,"Type":"FIR"},
    {"Name":"Ice Wave","Enemy":"Ctulhu","ATT":48,"Type":"ICE"},
    {"Name":"Arrow","Enemy":"Bone Archer","ATT":20,"Type":"HIT"},
    {"Name":"Fire Breath","Enemy":"Bone Pillar","ATT":23,"Type":"FIR"},
    {"Name":"Alucart sword","Enemy":"Doppleganger10","ATT":9,"Type":"CUT"},
    {"Name":"Dagger","Enemy":"Doppleganger10","ATT":6,"Type":"CUT"},
    {"Name":"Wing Smash","Enemy":"Doppleganger10","ATT":15,"Type":"HIT"},
    {"Name":"Barrel Throw","Enemy":"Skeleton Ape","ATT":20,"Type":"FIR"},
    {"Name":"Ape Punch","Enemy":"Skeleton Ape","ATT":12,"Type":"HIT"},
    {"Name":"Spear Stab","Enemy":"Spear Guard","ATT":14,"Type":"CUT"},
    {"Name":"Spear Swipe","Enemy":"Spear Guard","ATT":16,"Type":"CUT"},
    {"Name":"Skull","Enemy":"Spellbook","ATT":14,"Type":"HIT"},
    {"Name":"Cursed Touch","Enemy":"Ectoplasm","ATT":6,"Type":"CUR"},
    {"Name":"Puppet Sword","Enemy":"Sword Lord","ATT":23,"Type":"CUT"},
    {"Name":"Tongue","Enemy":"Toad","ATT":14,"Type":"HIT"},
    {"Name":"Sword","Enemy":"Armor Lord","ATT":24,"Type":"CUT"},
    {"Name":"Shield","Enemy":"Armor Lord","ATT":24,"Type":"CUT"},
    {"Name":"Flame","Enemy":"Armor Lord","ATT":30,"Type":"FIR"},
    {"Name":"Sword","Enemy":"Corner Guard","ATT":16,"Type":"CUT"},
    {"Name":"Rapier","Enemy":"Dhuron","ATT":15,"Type":"CUT"},
    {"Name":"Thunder Rapier","Enemy":"Dhuron","ATT":30,"Type":"THU"},
    {"Name":"Tongue","Enemy":"Frog","ATT":13,"Type":"HIT"},
    {"Name":"Ice Shard","Enemy":"Frozen Shade","ATT":18,"Type":"ICE"},
    {"Name":"Artic Blast","Enemy":"Frozen Shade","ATT":23,"Type":"ICE"},
    {"Name":"Ancient Weapons","Enemy":"Magic Tome","ATT":20,"Type":"CUT"},
    {"Name":"Poison Spit","Enemy":"Corpseweed","ATT":28,"Type":"PSN"},
    {"Name":"Spiked Flail","Enemy":"Flail Guard","ATT":24,"Type":"HIT"},
    {"Name":"Halberd","Enemy":"Bone Halberd","ATT":25,"Type":"CUT"},
    {"Name":"Sword","Enemy":"Hunting Girl","ATT":18,"Type":"CUT"},
    {"Name":"Ribs","Enemy":"Mudman","ATT":30,"Type":"CUT"},
    {"Name":"Sword","Enemy":"Owl Knight","ATT":25,"Type":"CUT"},
    {"Name":"Broken Sword","Enemy":"Vandal Sword","ATT":30,"Type":"HIT"},
    {"Name":"Axe","Enemy":"Flea Armor","ATT":25,"Type":"CUT"},
    {"Name":"Egg","Enemy":"Hippogryph","ATT":10,"Type":"HIT"},
    {"Name":"Fire Breath","Enemy":"Hippogryph","ATT":28,"Type":"FIR"},
    {"Name":"Bone Cleaver","Enemy":"Paranthropus","ATT":30,"Type":"HIT"},
    {"Name":"Bone Throw","Enemy":"Paranthropus","ATT":24,"Type":"HIT"},
    {"Name":"Blade","Enemy":"Blade Master","ATT":25,"Type":"CUT"},
    {"Name":"Hammer Head","Enemy":"Wereskeleton","ATT":1,"Type":"HIT"},
    {"Name":"Panther Rush","Enemy":"Wereskeleton","ATT":20,"Type":"HIT"},
    {"Name":"Bone Spread","Enemy":"Wereskeleton","ATT":28,"Type":"HIT"},
    {"Name":"Karate","Enemy":"Grave Keeper","ATT":25,"Type":"HIT"},
    {"Name":"Pyromania","Enemy":"Gremlin","ATT":24,"Type":"FIR"},
    {"Name":"Dagger Throw","Enemy":"Harpy","ATT":26,"Type":"HIT"},
    {"Name":"Harpy Kick","Enemy":"Harpy","ATT":24,"Type":"HIT"},
    {"Name":"Fire Eagle","Enemy":"Harpy","ATT":20,"Type":"HIT"},
    {"Name":"Axe","Enemy":"Minotaurus","ATT":35,"Type":"CUT"},
    {"Name":"Uppercut","Enemy":"Minotaurus","ATT":40,"Type":"HIT"},
    {"Name":"Bull Charge","Enemy":"Minotaurus","ATT":20,"Type":"HIT"},
    {"Name":"Poison Breath","Enemy":"Minotaurus","ATT":15,"Type":"PSN"},
    {"Name":"Punch","Enemy":"Werewolf18","ATT":28,"Type":"HIT"},
    {"Name":"Slide","Enemy":"Werewolf18","ATT":20,"Type":"HIT"},
    {"Name":"Lycan Charge","Enemy":"Werewolf18","ATT":20,"Type":"HIT"},
    {"Name":"Energy Discus","Enemy":"Werewolf18","ATT":30,"Type":"HIT"},
    {"Name":"Rolling Jump","Enemy":"Werewolf18","ATT":40,"Type":"HIT"},
    {"Name":"Poison Leap","Enemy":"Werewolf18","ATT":15,"Type":"PSN"},
    {"Name":"Fire Wave","Enemy":"Werewolf18","ATT":40,"Type":"FIR"},
    {"Name":"Undead Horse","Enemy":"Valhalla Knight","ATT":21,"Type":"HIT"},
    {"Name":"Thunder Sphere","Enemy":"Bone Ark","ATT":49,"Type":"THU"},
    {"Name":"Lance","Enemy":"Valhalla Knight","ATT":38,"Type":"CUT"},
    {"Name":"Flying Sword","Enemy":"Cloaked knight","ATT":30,"Type":"CUT"},
    {"Name":"Fire Spit","Enemy":"Fishhead","ATT":32,"Type":"FIR"},
    {"Name":"Fire Breath","Enemy":"Fishhead","ATT":37,"Type":"FIR"},
    {"Name":"Claw","Enemy":"Lesser Demon","ATT":24,"Type":"HIT"},
    {"Name":"Magical Spit","Enemy":"Lesser Demon","ATT":36,"Type":"HIT"},
    {"Name":"Magic Bolt","Enemy":"Lesser Demon","ATT":44,"Type":"HIT"},
    {"Name":"Fire Wave","Enemy":"Lossoth","ATT":29,"Type":"FIR"},
    {"Name":"Fire Spread","Enemy":"Lossoth","ATT":29,"Type":"FIR"},
    {"Name":"Curse","Enemy":"Salem Witch","ATT":25,"Type":"CUR"},
    {"Name":"Tri-Spirit","Enemy":"Salem Witch","ATT":35,"Type":"CUT"},
    {"Name":"Dagger","Enemy":"Blade","ATT":25,"Type":"CUT"},
    {"Name":"Kick","Enemy":"Blade","ATT":28,"Type":"HIT"},
    {"Name":"Gurkha Knife","Enemy":"Gurkha","ATT":30,"Type":"HIT"},
    {"Name":"Knife Throw","Enemy":"Gurkha","ATT":30,"Type":"HIT"},
    {"Name":"Hammer","Enemy":"Hammer","ATT":40,"Type":"HIT"},
    {"Name":"Discus","Enemy":"Discus Lord","ATT":32,"Type":"CUT"},
    {"Name":"Raven","Enemy":"Karasuman","ATT":32,"Type":"HIT"},
    {"Name":"Feather Array","Enemy":"Karasuman","ATT":24,"Type":"HIT"},
    {"Name":"Homing Spheres","Enemy":"Karasuman","ATT":28,"Type":"HIT"},
    {"Name":"Lightning Finger","Enemy":"Hellfire Beast","ATT":30,"Type":"THU"},
    {"Name":"Flame Pillar","Enemy":"Hellfire Beast","ATT":28,"Type":"FIR"},
    {"Name":"Fire Spit","Enemy":"Cerberos","ATT":35,"Type":"FIR"},
    {"Name":"Fire Stream","Enemy":"Cerberos","ATT":40,"Type":"FIR"},
    {"Name":"Curse Touch","Enemy":"Tombstone","ATT":40,"Type":"CUR"},
    {"Name":"Rose Throw","Enemy":"Venus Weed","ATT":40,"Type":"CUT"},
    {"Name":"Vine Weed","Enemy":"Venus Weed","ATT":36,"Type":"CUT"},
    {"Name":"Claw","Enemy":"Lion","ATT":77,"Type":"CUT"},
    {"Name":"Dark Touch","Enemy":"Schmoo","ATT":40,"Type":"DRK"},
    {"Name":"Rotating Axe","Enemy":"Tin man","ATT":55,"Type":"CUT"},
    {"Name":"Tin Gun","Enemy":"Tin man","ATT":33,"Type":"HIT"},
    {"Name":"Poison Spores","Enemy":"Balloon pod","ATT":2,"Type":"PSN"},
    {"Name":"Bomb","Enemy":"Bomb Knight","ATT":70,"Type":"FIR"},
    {"Name":"Dark Touch","Enemy":"Bitterfly","ATT":55,"Type":"DRK"},
    {"Name":"Bone Shuriken","Enemy":"Jack O'Bones","ATT":30,"Type":"HIT"},
    {"Name":"Arrow","Enemy":"Archer","ATT":55,"Type":"CUT"},
    {"Name":"Punch","Enemy":"Werewolf34","ATT":45,"Type":"HIT"},
    {"Name":"Slide","Enemy":"Werewolf34","ATT":45,"Type":"HIT"},
    {"Name":"Lycan Charge","Enemy":"Werewolf34","ATT":40,"Type":"HIT"},
    {"Name":"Rolling Jump","Enemy":"Werewolf34","ATT":40,"Type":"HIT"},
    {"Name":"Energy Discus","Enemy":"Werewolf34","ATT":72,"Type":"HIT"},
    {"Name":"Axe","Enemy":"Minotaur","ATT":65,"Type":"CUT"},
    {"Name":"Poison Breath","Enemy":"Minotaur","ATT":5,"Type":"PSN"},
    {"Name":"Nova Beam","Enemy":"Nova Skeleton","ATT":150,"Type":"HIT"},
    {"Name":"Charge","Enemy":"White Dragon","ATT":8,"Type":"HIT"},
    {"Name":"Fire Breath","Enemy":"White Dragon","ATT":67,"Type":"FIR"},
    {"Name":"Bite","Enemy":"Fire Warg","ATT":48,"Type":"CUT"},
    {"Name":"Fire Breath","Enemy":"Fire Warg","ATT":60,"Type":"FIR"},
    {"Name":"Rock","Enemy":"Rock Knight","ATT":37,"Type":"HIT"},
    {"Name":"Rock Toss","Enemy":"Rock Knight","ATT":100,"Type":"HIT"},
    {"Name":"Arrow","Enemy":"Sniper of Goth","ATT":65,"Type":"CUT"},
    {"Name":"Arrows Array","Enemy":"Sniper of Goth","ATT":55,"Type":"CUT"},
    {"Name":"Spear","Enemy":"Warg Rider","ATT":55,"Type":"CUT"},
    {"Name":"Blood Suck","Enemy":"Cave Troll","ATT":50,"Type":"CUT"},
    {"Name":"Neutron Field","Enemy":"Cave Troll","ATT":50,"Type":"CUT"},
    {"Name":"Ink","Enemy":"Dark Octopus","ATT":52,"Type":"HIT"},
    {"Name":"Fire Spit","Enemy":"Fire Demon","ATT":70,"Type":"FIR"},
    {"Name":"Stone Breath","Enemy":"Gorgon","ATT":27,"Type":"STN"},
    {"Name":"Dark Orb","Enemy":"Malachi","ATT":65,"Type":"DRK"},
    {"Name":"Poison Claw","Enemy":"Malachi","ATT":85,"Type":"PSN"},
    {"Name":"Punch","Enemy":"Akmodan II","ATT":66,"Type":"HIT"},
    {"Name":"Rotating Throw","Enemy":"Akmodan II","ATT":35,"Type":"HIT"},
    {"Name":"Disease Cloud","Enemy":"Akmodan II","ATT":1,"Type":"PSN"},
    {"Name":"Rose Throw","Enemy":"Blue Venus Weed","ATT":70,"Type":"CUT"},
    {"Name":"Vine Weed","Enemy":"Blue Venus Weed","ATT":50,"Type":"CUT"},
    {"Name":"Terminus Est","Enemy":"Doppleganger40","ATT":35,"Type":"PSN"},
    {"Name":"Stone Sword","Enemy":"Doppleganger40","ATT":5,"Type":"STN"},
    {"Name":"Wing Smash","Enemy":"Doppleganger40","ATT":55,"Type":"HIT"},
    {"Name":"Rebound Stone","Enemy":"Doppleganger40","ATT":12,"Type":"HOL"},
    {"Name":"Sword","Enemy":"Medusa","ATT":45,"Type":"CUT"},
    {"Name":"Stone Gaze","Enemy":"Medusa","ATT":13,"Type":"STN"},
    {"Name":"Hammer","Enemy":"The Creature","ATT":55,"Type":"HIT"},
    {"Name":"Roll","Enemy":"The Creature","ATT":55,"Type":"HIT"},
    {"Name":"Dagger","Enemy":"Fake Grant","ATT":33,"Type":"CUT"},
    {"Name":"Bone Whip","Enemy":"Fake Trevor","ATT":43,"Type":"HIT"},
    {"Name":"Dagger","Enemy":"Fake Trevor","ATT":37,"Type":"CUT"},
    {"Name":"Dagger Crash","Enemy":"Fake Trevor","ATT":37,"Type":"CUT"},
    {"Name":"Holy Water","Enemy":"Fake Trevor","ATT":18,"Type":"HOL"},
    {"Name":"Dark Cross","Enemy":"Fake Trevor","ATT":38,"Type":"DRK"},
    {"Name":"Huge Dark Cross","Enemy":"Fake Trevor","ATT":42,"Type":"DRK"},
    {"Name":"Fire","Enemy":"Fake Sypha","ATT":60,"Type":"FIR"},
    {"Name":"Ice","Enemy":"Fake Sypha","ATT":35,"Type":"ICE"},
    {"Name":"Zombie","Enemy":"Fake Sypha","ATT":40,"Type":"CUR"},
    {"Name":"Homing Lights","Enemy":"Fake Sypha","ATT":45,"Type":"HOL"},
    {"Name":"Dark Touch","Enemy":"Beezelbub","ATT":60,"Type":"DRK"},
    {"Name":"Fly","Enemy":"Beezelbub","ATT":66,"Type":"DRK"},
    {"Name":"Vermin","Enemy":"Beezelbub","ATT":5,"Type":"PSN"},
    {"Name":"Huge Sword","Enemy":"Azaghal","ATT":80,"Type":"CUT"},
    {"Name":"Ice Touch","Enemy":"Frozen Half","ATT":35,"Type":"ICE"},
    {"Name":"Frozen Orb","Enemy":"Frozen Half","ATT":60,"Type":"ICE"},
    {"Name":"Ice Rock","Enemy":"Frozen Half","ATT":75,"Type":"ICE"},
    {"Name":"\"Maximum Power\"","Enemy":"Frozen Half","ATT":65,"Type":"ICE"},
    {"Name":"Magic Dot","Enemy":"Salome","ATT":60,"Type":"HIT"},
    {"Name":"Skull Throw","Enemy":"Salome","ATT":65,"Type":"HIT"},
    {"Name":"Kitten","Enemy":"Salome","ATT":60,"Type":"CAT?"},
    {"Name":"Whip","Enemy":"Richter Belmont","ATT":35,"Type":"HOL"},
    {"Name":"Slide","Enemy":"Richter Belmont","ATT":35,"Type":"HIT"},
    {"Name":"Blade Dash","Enemy":"Richter Belmont","ATT":55,"Type":"HIT"},
    {"Name":"Axe","Enemy":"Richter Belmont","ATT":40,"Type":"HOL"},
    {"Name":"Holy Book","Enemy":"Richter Belmont","ATT":70,"Type":"HOL"},
    {"Name":"Holy Water","Enemy":"Richter Belmont","ATT":35,"Type":"FIR"},
    {"Name":"Holy Cross","Enemy":"Richter Belmont","ATT":35,"Type":"HOL"},
    {"Name":"Flame Whip","Enemy":"Richter Belmont","ATT":60,"Type":"HOL"},
    {"Name":"Axe Crash","Enemy":"Richter Belmont","ATT":40,"Type":"HOL"},
    {"Name":"Holy Book Crash","Enemy":"Richter Belmont","ATT":70,"Type":"HOL"},
    {"Name":"Agunea Crash","Enemy":"Richter Belmont","ATT":40,"Type":"HOL"},
    {"Name":"Hydro Storm","Enemy":"Richter Belmont","ATT":35,"Type":"HOL"},
    {"Name":"Holy Cross Crash","Enemy":"Richter Belmont","ATT":40,"Type":"HOL"},
    {"Name":"Staff","Enemy":"Galamoth","ATT":50,"Type":"HIT"},
    {"Name":"Kick","Enemy":"Galamoth","ATT":85,"Type":"HIT"},
    {"Name":"Lightning","Enemy":"Galamoth","ATT":98,"Type":"THU"},
    {"Name":"Dark Balls","Enemy":"Galamoth","ATT":92,"Type":"HIT"},
    {"Name":"Great Sword","Enemy":"Guardian","ATT":120,"Type":"CUT"},
    {"Name":"Shield","Enemy":"Guardian","ATT":120,"Type":"CUT"},
    {"Name":"Flame","Enemy":"Guardian","ATT":90,"Type":"FIR"},
    {"Name":"Orb","Enemy":"Shaft","ATT":64,"Type":"HIT"},
    {"Name":"Fire Orb","Enemy":"Shaft","ATT":42,"Type":"FIR"},
    {"Name":"Lightning Orb","Enemy":"Shaft","ATT":43,"Type":"THU"},
    {"Name":"\"Alien Heads\"","Enemy":"Lord Dracula","ATT":85,"Type":"HIT"},
    {"Name":"Triangle-flash","Enemy":"Lord Dracula","ATT":95,"Type":"HIT"},
    {"Name":"Energy Ball","Enemy":"Lord Dracula","ATT":140,"Type":"HIT"}
  ]
});

export const getters = {
  enemy: (state) => (name) => {
    name = name.replace(/-/g, ' ');
    return state.enemies.find(enemy => enemy.Name == name);
  },
  attacks: (state) => (enemy) => {
    return state.attacks.filter(attack => attack.Enemy == enemy);
  },
  previous: (state) => (id) => {
    return state.enemies.find(enemy => enemy.ID == +id - 1 );
  },
  next: (state) => (id) => {
    return state.enemies.find(enemy => enemy.ID == +id + 1);
  },
  item: (state) => (name) => {
    return state.items.find(item => item.Name.replace(/ /g,'-') == name.replace(/ /g,'-'));
  },
  itemsByClass: (state) => (name) => {
    return state.items.filter(item => item.Class == name);
  }
}
