<template>
  <div>
    <Navbar/>
    <div class="container">
      <div class="breadcrumb">
        <NuxtLink to="/">GOD</NuxtLink> &raquo;
        <NuxtLink to="/">Castlevania: Symphony of the Night</NuxtLink> &raquo;
        Bugs
      </div>
      <Header/>
      <h2>Bugs</h2>
      <hr/>
      <main>
        <center><NuxtLink to="oddities">Oddities</NuxtLink> | <NuxtLink to="easter-eggs">Easter Eggs</NuxtLink> | <NuxtLink to="bugs">Bugs</NuxtLink> | <NuxtLink to="glitches">Glitches</NuxtLink></center>
        <p>Aqui estão os "bugs" (erros dos programadores no planejamento do jogo) catalogadas por meu amigo, <b>Jack (O' Bones) Wilker Barros</b>.</p>
        <ol>
          <li><b>O lampião mágico:</b> Em <NuxtLink to="maps/Alchemy-Laboratory">Alchemy Laboratory</NuxtLink>, em cima de um fogareiro com uma chama branca onde você encontra o <Item item="Leather shield"/> tem duas velas. A peculiaridade dessas velas é que só aparece uma de cada vez. Quando você vem da esquerda para a direita, você vê a vela da esquerda. Encoste na parede à esquerda e suba até a terceira plataforma, e observe que a vela some. Desça para checar de perto, volte e suba até a última plataforma. Desça novamente e note que você só vê a vela à direita. A vela da esquerda tem $1 e a vela da direita, 25$.</li>
          <li><b>Vela que desaparece em Floating Catacombs:</b> Na primeira sala dessa área há duas velas, uma com um 'Axe' e outra com um coração grande. Suba, entre na sala de save, volte e destrua a vela com um coração grande. Desça e a vela que continha o Axe desaparece.</li>
          <li><b>Vela que desaparece em <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>:</b> na sala onde tem dois <NuxtLink to="enemies/Valhalla-Knight">Valhalla Knight</NuxtLink>s, entre normalmente da direita para esquerda e você encontrará os seguintes itens nos candelabros: coração pequeno, $25, $25. Entrando da esquerda para direita você encontra: coração pequeno, $25, $25. Ou seja, sempre que você entra nessa sala some um candelabro. na verdade, tem 4 que são, da esquerda para direita, coração pequeno, $25, $25 e coração pequeno. Obs.: se você entrar voando sem matar nenhum <NuxtLink to="enemies/Axe-Knight">Axe Knight</NuxtLink> elas não somem.</li>
          <li><b>Jarra com <img src="~static/img/items/life-max-up.gif" alt=""/>Life Max Up desaparece em <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink>:</b> Para fazer a jarra que fica em baixo do elevador desaparecer, suba de onde está a jarra até a primeira escada, destrua a primeira vela e não pegue o coração deixado por ela. Dê um 'Hyper Jump', e ainda com o coração da vela na tela, desça até a jarra. Se não tiver a <Item item="Gravity Boots"/>, suba até o <NuxtLink to="enemies/Skeleton">Skeleton</NuxtLink>, desça, destrua a vela sem pegar seu coração e vá até a jarra.</li>
          <li><b>Velas "mudas":</b> Em <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink>, na sala dos <NuxtLink to="enemies/Vandal-Sword">Vandal Sword</NuxtLink>s, as velas não emitem som quando são destruídas.</li>
          <li><b>Vela com dois itens no Castelo Invertido:</b> Em Black Marble Gallery, à direita do Relógio Central onde tem dois <NuxtLink to="enemies/Gorgon">Gorgon</NuxtLink>s, uma das velas dessa sala deixa um coração grande e um pequeno. (Na verdade são duas velas no mesmo lugar).</li>
          <li><b>Machados que desaparecem:</b> Em <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>, na sala com <NuxtLink to="enemies/Axe-Knight9">Axe Knight</NuxtLink>s e <NuxtLink to="enemies/Valhalla-Knight">Valhalla Knight</NuxtLink>s voe como morcego e pare bem no centro da sala, de modo que dê para visualizar os três <NuxtLink to="enemies/Axe-Knight9">Axe Knight</NuxtLink>s. Espere que eles joguem os machados e note que os machados desaparecem.</li>
          <li><b><NuxtLink to="enemies/Axe-Knight9">Axe Knight</NuxtLink> desaparesce:</b> Entre na mesma sala do item anterior usando o 'Wing Smash' da direita para esquerda. Obs.: têm outros modos de se fazer isso, mas esse é o mais fácil.</li>
          <li><b>O lobo e as paredes:</b> Se você fizer a magia 'Wolf Charge' encostado ou próximo a uma parede do lado esquerdo, o lobo pára. Já se a parede for à direita ele se choca bruscamente.</li>
          <li><b>Passar normalmente por baixo da cachoeira transformado em morcego ou névoa:</b> No final da cachoeira em Underground Caverns, transforme-se em morcego, ponha para baixo até que as asas do morcego toquem a água de modo que quando você se mova faça o barulho das asas batendo na água. Segure para a direita em direção à cachoeira. O morcego irá passar por baixo da cachoeira sem se destransformar. Isso porque, na realidade não existe água no final da cachoeira onde ela se encontra como lago.</li>
          <li><b>Lugar onde o pulo não funciona:</b> Em Undeground Caverns, na sala onde você aciona o botão para chamar o <NuxtLink to="enemies/Skeleton-Ape">Skeleton Ape</NuxtLink>, tem uma espécie de "mesinha" no centro. Suba em cima dessa "mesinha", segure <img src="~static/img/baixo.gif" alt="Baixo"/> e aperte <img src="~static/img/x.gif" alt="X"/>. Nada acontecerá. Existe outras "mesinhas" como esta espalhadas pelo jogo. Obs.: Fazendo isso em um piso comum, Alucard pulará normalmente.</li>
          <li><b>Canoeiro dentro da parede:</b> Em Underground Caverns, após pegar a relíquia <Item item="Merman Statue"/>, siga para o outro lugar em que você encontra o Ferryman. Entre na sala com a relíquia desligada e note que ele não está na sala. Avance umas duas telas, ligue a relíquia e retorne à entrada da sala. Note que o Canoeiro está lá, só que virado para porta, suba na canoa e ele entrará na parede.</li>
          <li><b>Fazer a lava de Catacombs desaparecer:</b> Na sala em que se encontra o <NuxtLink to="enemies/Discus-Lord">Discus Lord</NuxtLink>, suba para a passagem que tem em cima dele e entre na sala da <Item item="Icebrand"/>. saia da sala usando vários backdashes (<img src="~static/img/triangulo.gif" alt="Triângulo"/>) até cair próximo ao <NuxtLink to="enemies/Discus-Lord">Discus Lord</NuxtLink>. Você verá que a lava desapareceu. Este efeito é semelhante ao de estar fora do castelo.</li>
          <li><b>Fazer o elevador de <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink> subir um pouco mais que o normal:</b> Esteja no 3º andar com o elevador no 2º. Invoque o elevador, e assim que ele começar a se mover (olhe para a corrente), entre na sala do chefe (à esquerda) e fique revezando rapidamente entre estas duas salas. Note que ele ficará um pouco mais alto do que costuma ficar e começará a descer.</li>
          <li><b>Retardar o elevador de <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>:</b> Com o elevador no 1º andar e você no 3º, invoque-o. Assim que ele começar a se mover, entre na sala do chefe e faça o retorno por cima. Volte à sala do elevador entrando pela direita. Você verá que o elevador ainda não está em cima. Obs.: não precisa ter pressa! (ele é lerdo mesmo).</li>
          <li><b>Sofrimento eterno para os <NuxtLink to="enemies/Spear-Guard">Spear Guard</NuxtLink>s:</b> Em Underground Caverns, empurre a caixa para trancar a passagem d'água. Assim que a caixa tocar a parede e obstruir a passagem da água, seja rápido e fuja para direita. Suba rapidamente pela passagem que tem ali próximo. Agora sempre que você passar por essa parte você verá os <NuxtLink to="enemies/Spear-Guard">Spear Guard</NuxtLink>s agonizando. Esse Truque não se desfaz ao passar por uma sala Load CD.</li>
          <li><b>Espinho que não fura:</b> Em Royal Chapel, no corredor dos espinhos, passe pela grade usando a Névoa e fique do outro lado bem encostado à grade. Use o 'Wing Smash' e não mexa no controle. Quando a magia acabar, Alucard cairá em um dos espinhos que não furam. (tem muitos outros nessa sala).</li>
          <li><b>Modificar o brilho do ataque do aliado Bat:</b> Transforme-se em lobo e se posicione longe de um inimigo com o 'Bat Familiar' ativo. Quando o "!" aparecer, use a 'Wolf Charge' em direção ao alvo. O brilho ficará na frente do familiar.</li>
          <li><b><Item item="Sword Familiar"/> na mão com o ataque branco:</b> Basta salvar o jogo com ela equipada, resetar o jogo, e dar Load no arquivo. Ela fica com um efeito branco semelhante ao de <Item item="Alucard sword"/>, só que com a chama verde.</li>
          <li><b><img src="~static/img/items/heart-max-up.gif"/>Heart Max Up esquisito:</b> Em <NuxtLink to="maps/Underground-Caverns">Underground Caverns</NuxtLink>, logo na entrada, desça e siga para esquerda até encontrar um 'Heart Max Up' e a <Item item="Bandanna"/>, bem próximos um do outro. Não pegue esse <abbr title="Heart Max Up">HMU</abbr>. Desça seguindo o jogo normalmente até a parte em que você encontra o único <NuxtLink to="enemies/Killer-Fish">Killer Fish</NuxtLink> do Primeiro Castelo. Logo após, você encontra o tal Coração. Na verdade é o mesmo <abbr title="Heart Max Up">HMU</abbr> que se encontra no início da fase, próximo da <Item item="Bandanna"/>, só que em uma localização diferente. Quando você pega em um local ele desaparece do outro.</li>
          <li><b>Informações erradas na opção "spells":</b> No comando do 'Wolf Charge', o jogo "diz": <img src="~static/img/baixo.gif" alt="Baixo"/>, <img src="~static/img/baixofrente.gif" alt="Diagonal inferior direita"/>, <img src="~static/img/frente.gif" alt="Direita"/> + <img src="~static/img/quadrado.gif" alt="Quadrado"/> ou <img src="~static/img/circulo.gif" alt="Círculo"/>. Tente fazer isso com <img src="~static/img/circulo.gif" alt="Círculo"/>. Não funciona! Está errado!</li>
          <li><b>Segurando algum botão, os comandos do 'Hyper Jump' e do 'Dark Metamorphosis' não funcionam.</b> Todos os outros funcionam.</li>
          <li><b>Morcego escondido:</b> em Underground Caverns, na parte onde o Ferryman aparece pela segunda vez, observe que há morcegos no teto. Junto ao último desses morcegos tem um morcego secretamente escondido dentro do teto. É mais fácil percebê-lo, vindo da esquerda para a direita.</li>
          <li><b><NuxtLink to="enemies/Jack-O'Bones">Jack O'Bones</NuxtLink> escondido:</b> Em Reverse Outer Wall, chegue até o 'Teleport Pad' do escorpião. Não entre, vá subindo. O 1º <NuxtLink to="enemies/Jack-O'Bones">Jack O'Bones</NuxtLink> que você encontrar na verdade são dois. mate-o e confira seus 'Kills'. Sobe dois pontos! Outro modo de perceber que são dois, é esperar que ele pule lá de cima. Às vezes pula um, e o outro fica lá.</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) <NuxtLink to="enemies/Flea-Man">Flea Man</NuxtLink> Flutuando:</b> . Usando a <Item item="Runesword"/>, pule junto com ele e ataque-o de modo que você esteja mais baixo do que ele. A <Item item="Runesword"/> o destrói e ele ficará voando. (fique parado).</li>
          <li><b>Morte diferente para <NuxtLink to="enemies/Rock-Knight">Rock Knight</NuxtLink> e <NuxtLink to="enemies/Bomb-Knight">Bomb Knight</NuxtLink>:</b> mate-o usando o 'Soul Steal' quando ele estiver com o item na mão. Obs.: o 'Soul Steal' causará vários hits.</li>
          <li><b>Alterar a morte do <NuxtLink to="enemies/Werewolf34">Werewolf</NuxtLink>:</b> Em Reverse Colosseum há uma sala com três <NuxtLink to="enemies/Werewolf34">Werewolf</NuxtLink> e três <NuxtLink to="enemies/Minotaur">Minotaur</NuxtLink>s. Entre na sala equipado com a <Item item="Crissaegrim"/> e saia andando e atacando rapidamente de modo que você mate todos os inimigos sem dar nenhuma pausa. Note que o primeiro e/ou o segundo morrem sem as chamas.</li>
          <li><b><NuxtLink to="enemies/Skull-Lord">Skull Lord</NuxtLink>, o espaçoso:</b> O jogo não suporta 2 desses monstros ao mesmo tempo na tela. (Tente juntá-los em <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink>.)</li>
          <li><b><NuxtLink to="enemies/Skull-Lord">Skull Lord</NuxtLink> sem o olho:</b> Na 1ª sala do 2º Castelo. (Reverse Keep), tem um <NuxtLink to="enemies/Skull-Lord">Skull Lord</NuxtLink>. Chegue até ele sem ter apertado pausa durante esta fase. Ele estará com o olho vermelho brilhando. Se você pausar durante esta fase, o olho dele fica todo negro. Chegue até ele sem antes ter pausado. Olhando para ele, pause e despause. Você notará que o olho desapareceu!</li>
          <li><b><NuxtLink to="enemies/Blue-Raven">Blue Raven</NuxtLink> esquece de morrer:</b> Mate-o quando ele estiver fora do seu lugar de origem. Ele deve estar acima da cabeça de Alucard. Ele descerá voando e só explodirá quando estiver na altura de sua cabeça. Desça até o piso para atraí-lo. Se tiver dificuldade, use uma bomba.</li>
          <li><b>Falha na foto do <NuxtLink to="enemies/Black-Crow">Black Crow</NuxtLink>:</b> Olhando a foto Nº 52 da 'Enemy List', observe que bem em cima do pássaro tem um ponto (pixel) preto (da cor dele).</li>
          <li><b>Uma falha na foto do <NuxtLink to="enemies/Bone-Pillar">Bone Pillar</NuxtLink>:</b> No item Nº 33 da 'Enemy List', note uma falha no canto inferior direito.</li>
          <li><b>Combinação de teletransportes:</b> Fique no centro do teletransporte, use um <Item item="Library card"/> e rapidamente ponha para cima. Alucard permanecerá na pose do <Item item="Library card"/> por alguns segundos, isso após chegar do outro lado. Se demorar em pôr para cima ele fica invisível.</li>
          <li><b>Usar os 'Teleport Pads' no ar:</b> fique bem no centro do 'Teleport Pad' e dê dois pulos e um super pulos ou faça a magia da espada <Item item="Flamberge"/> ou similares no ar, e quando for passando pela posição do teleport, ponha para cima.</li>
          <li><b>Alterar a chegada do teletransporte:</b> Faça a dica anterior de modo que o Alucard fique bem longe do centro do Teletransporte. Normalmente ficam uns ossos voando que caem logo em seguida quando se usa um teletransporte. Desta forma os ossos já aparecem no chão, do outro lado, além de uma pequena modificação no flash de luz. Também funciona usando o super pulo na diagonal a partir do chão.</li>
          <li><b>Usar teletransporte com estilo:</b> Realize um 'Backdash' e ponha para cima, isso no centro do 'Teleport Pad'. Na versão americana, a borda do 'Teleport Pad' "barra" Alucard. Na versão Japonesa, Alucard segue com o 'Backdash' passando para trás da parede.</li>
          <li><b>Lobo não pega o item deixado pelo <Item item="Meal ticket"/>:</b> Jogue o máximo de itens que o <Item item="Meal ticket"/> permite e transforme-se em lobo. Todos os itens somem, menos o último. Agora tente pegá-lo com o lobo; você não conseguirá.</li>
          <li><b><NuxtLink to="enemies/Cerberos">Cerberos</NuxtLink> senta em pleno ar:</b> Espere-o pular e mate-o. Ele se senta no ar para morrer.</li>
          <li><b><NuxtLink to="enemies/Cerberos">Cerberos</NuxtLink> ou <NuxtLink to="enemies/Cerberos">Cerberus</NuxtLink>?:</b> O nome que aparece quando você acerta ele é um, o nome que aparece na 'Enemy List' é outro.</li>
          <li><b>Você não usa o elevador de <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> se estiver envenenado:</b> Simplesmente não funciona.</li>
          <li><b>Desfecho no elevador secreto de <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink>:</b> Quebre apenas a parte de baixo da parede que se esconde o elevador, tomando cuidado para não quebrar a parte de cima. Use o 'Dive kick' na diagonal em direção ao buraco, de modo que Alucard caia abaixado e deslize para dentro do buraco. Espere os 20 segundos. O elevador será ativado e Alucard cairá fora do Castelo, mas não conseguirá sair totalmente!</li>
          <li><b>'Dive Kick' sem os dois pulos:</b> Pule, transforme e destransforme em lobo e, ainda no ar, faça <img src="~static/img/baixo.gif" alt="Baixo"/> + <img src="~static/img/x.gif" alt="X"/>.</li>
          <li><b>Pegando atalhos e alterando a história:</b> Faça a dica acima no relógio central para quicar na velinha e seguir para <NuxtLink to="maps/Olrox's-Quarters">Olrox's Quarters</NuxtLink>.</li>
          <li><b>Magia da <Item item="Heaven sword"/> paralisada na tela:</b> Equipado com duas <Item item="Heaven sword"/>s, faça a magia (<img src="~static/img/quadrado.gif" alt="Quadrado"/> + <img src="~static/img/circulo.gif" alt="Círculo"/>), espere a magia formar uma "meia-lua", então transforme-se em Wolf. Dependendo da hora em que você virar o lobo, poderá observar algumas figuras dentro da magia como patas de lobo.</li>
          <li><b>Magia da <Item item="Heaven sword"/> um pouco diferente:</b> Faça a magia descrita acima e imediatamente transforme-se em névoa.</li>
          <li><b>Piso falso:</b> Em <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink>, na primeira sala vindo de <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink>, faça a magia 'Sword Brothers' e rapidamente transforme-se em Wolf e saia correndo para a esquerda com a magia 'Wolf Charge'. Na sala seguinte, ainda correndo com o lobo, pule do topo da escada e continue pressionando para <img src="~static/img/tras.gif" alt="Esquerda"/> e <img src="~static/img/x.gif" alt="X"/>. Você pulará bem alto até pisar sobre o último piso falso. Note que ficará um pedaço da pedra voando. (Quando feito com sucesso, na versão japonesa, a vela que guarda a 'Sub-Weapon' 'Rebound Stone' nesta sala desaparecerá. Esta vela está logo acima do piso falso próximo à sala mais alta à esquerda.)</li>
          <li><b><Item item="Monster Vial 1"/> e <Item item="Magic Missile"/> não desaparecem ao transformar-se em lobo:</b> Quando se usa um item e transforma-se em lobo, o item é cancelado. Mas há uma forma em fazer com que estes não desapareçam. Com um em cada mão, ative rapidamente o máximo que puder. Quando você apertar o botão e não sair nenhum, transforme-se em lobo. (Obs.: Do <Item item="Magic Missile"/>, só a flecha não desaparece.)</li>
          <li><b>(<abbr title="United States of America">USA</abbr>) Pinguinhos Azuis na destransformação do Wolf:</b>  Com o lobo virado para a direita, pule e, quando estiver caíndo, aperte <img src="~static/img/quadrado.gif" alt="Quadrado"/> e antes que o som do ataque saia, e com o lobo ainda no ar, destransforme-se.</li>
          <li><b>Deslizar de costas com o Lobo (1):</b> Na forma de lobo, faça <img src="~static/img/tras.gif" alt="Trás"/> e <img src="~static/img/baixo.gif" alt="Baixo"/> rapidamente até mudar de sala em uma escada que passe de uma sala para outra. Ex.: A primeira escada de <NuxtLink to="maps/Long-Library">Long Library</NuxtLink> ou em Anti-Chapel para entrar na sala de save próximo à <NuxtLink to="enemies/Medusa">Medusa</NuxtLink>.</li>
          <li><b>Deslizar de costas com o Lobo (2):</b> O mesmo padrão da primeira, mas deixando o lobo o mais baixo da escada possível sem que ele mude de tela, então, pule e não mexa no direcional, ou pule e controle o lobo no ar para que ele caia nesse limite de tela com a metade para baixo e a outra para cima e solte os comandos ainda no ar.</li>
          <li><b>Colocar a névoa um pouco dentro da parede do chão ou do teto:</b> Fique encostado na parede e vire lobo. Use a dica de mover o lobo de costas e quando ele estiver metade dentro da parede, vire névoa. Teto - Com o Morcego, segure para cima encostado no teto. Quando o morcego estiver com as asas bem abertas, transforme-se em névoa. Piso - Com o morcego, segure para baixo encostado no piso. Espere o momento em que o Bat esteja com as asas bem fechadas, então transforme-se em névoa.</li>
          <li><b>Acessar o menu do Master Librarian de costas:</b> Na sala do Master Librarian, transforme-se em lobo, fique de costas para ele e faça a dica 47.</li>
          <li><b>Escada rolante em <NuxtLink to="maps/Marble-Gallery">Marble Gallery</NuxtLink>:</b> Avance 3 salas para a direita após o relógio central. Nesse sala há uma vela com a 'Sub-Weapon' 'Rebound Stone'. Mais adiante tem uma escada com duas <NuxtLink to="enemies/Ouija-Table">Ouija Table</NuxtLink>s. É essa a escada rolante. Mate todos os inimigos dessa sala e, na parte de cima, onde tinha um <NuxtLink to="enemies/Skeleton">Skeleton</NuxtLink>, encoste na parede à extrema esquerda, transforme-se em lobo e corra para a direita usando a magia 'Wolf Charge'. Segure <img src="~static/img/frente.gif" alt="Direita"/> até o lobo se chocar contra a parede. Ele cairá na escada onde tinham as <NuxtLink to="enemies/Ouija-Table">Ouija Table</NuxtLink>s e sairá rolando de costas. (Pode ser preciso tentar algumas vezes para conseguir).</li>
          <li><b>Mudar a cor do traseiro do lobo:</b> Na forma de lobo, ponha para trás para que o lobo vire para o outro lado, espere ele ficar de frente para a tela, então ponha para baixo. Com o traseiro do lobo já escuro, se você desviar, o efeito desaparece. Se quiser virar sem que o efeito desapareça, pule e vire ainda no ar. Ande vagarosamente em uma escada para ver o lobo cortado ao meio. Note também pequenas modificações nos "ombros" do lobo.</li>
          <li><b>Lobo atrapalha o brilho das poções:</b> Use uma <Item item="Uncurse"/> ou <Item item="Antivenom"/> segurando para baixo ou pulando em diagonal e, imediatamente, transforme-se em lobo. Seja rápido e volte à forma de Alucard. Pode ser feito também com Alucard virado para a direita. Use a poção, aperte <img src="~static/img/tras.gif" alt="Esquerda"/> + R2, segure para a <img src="~static/img/frente.gif" alt="Direita"/> e aperte R2 rapidamente para voltar à forma de Alucard.</li>
          <li><b>Deixar o lobo em cima da barra de <abbr title="Magic Points">MP</abbr>:</b> Com o <Item item="Talisman"/> equipado e na forma de lobo, deixe que um inimigo bata em você. Nessa hora, o <Item item="Talisman"/> deverá funcionar (Depende do <abbr title="Luck">LCK</abbr>). Então, quando o reflexo de Alucard estiver no ar, ainda na forma de lobo, aperte L1 para se transformar em Mist. Agora, quando você passar de uma sala para outra na forma de lobo, o lobo passará em cima da barra de <abbr title="Magic Points">MP</abbr>. Mas, só na hora em que a tela estiver escura. Na forma de lobo, aperte 'Select' e você verá o lobo no mapa. Da forma de Alucard, transforme-se em lobo e em seguida em Mist e mude de uma sala para a outra ou aperte 'Select' para ver apenas as patas do lobo sobre a barra de <abbr title="Magic Points">MP</abbr>. Se apertar 'Start', também dá para ver o lobo lá.</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) Deixar a imagem do lobo na barra de <abbr title="Magic Points">MP</abbr> por mais tempo:</b>  Faça a dica anterior em <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> e, em seguida, entre na sala que tem o elevador secreto. Fique em cima do elevador e transforme-se em Lobo. A imagem do lobo aparecerá na barra de <abbr title="Magic Points">MP</abbr>, não destransforme e saia andando pela fase. Corra com o lobo e você verá apenas as patas dianteiras. Pode ser feita em outros lugares que tenham "switch" do mesmo estilo do elevador secreto.</li>
          <li><b><Item item="Runesword"/> pregada na Mist (1):</b> Dê um pulo duplo bem alto e quando estiver no auge do segundo pulo, solte <img src="~static/img/x.gif" alt="X"/> e jogue uma ou duas <Item item="Runesword"/>s. No mesmo instante, faça um 'Dive Kick'. Alucard cairá no chão agachado. Não mexa mais no direcional e aperte L1 para a se transformar em Mist. Quando as espadas voltarem, elas ficarão pregadas na Mist.</li>
          <li><b><Item item="Runesword"/> pregada na Mist (2):</b> Jogue as <Item item="Runesword"/>, seja rápido dando um 'Hyper Jump', espere Alucard colar no teto (De cabeça pra baixo) e transforme-se em Mist. Se você se mover, o truque se desfaz. (Se fizer com uma espada, ficarão duas juntas à névoa. Faça com duas e serão quatro).</li>
          <li><b><Item item="Chakram"/> pregado na Mist:</b> Para essa dica, você precisará da <Item item="Leap Stone"/>, <Item item="Power of Mist"/>, <Item item="Gravity Boots"/> e <Item item="Chakram"/>. Vá para uma área que tenha bastante espaço para cima, dê dois pulos e, rapidamente, faça dois 'Hyper Jumps'. Assim que o segundo 'Hyper Jump' terminar, atire os <Item item="Chakram"/>s e deixe que Alucard caia sem que você toque no direcional. Quando estiver próximo do chão, mais ou menos à altura de dois pulos, aperte L1 para Mist. Não toque no direcional e espere os <Item item="Chakram"/>s voltarem e pregarem na Mist.</li>
          <li><b>Efeito da <Item item="Sword of Dawn"/> no ar ou debaixo do chão:</b> Em uma área que tenha tela para cima, faça a magia da <Item item="Sword of Dawn"/> e, imediatamente, segure <img src="~static/img/cima.gif" alt="Cima"/> e L1 para Mist, assim o efeito surgirá no ar. Ou então, <img src="~static/img/baixo.gif" alt="Baixo"/> + L1 para o efeito surgir debaixo do chão.</li>
          <li><b>Sonar parado na tela:</b> Em Catacombs, na sala escura, use a 'Sub-Weapon' 'Stop Watch' e rapidamente transforme-se em morcego. Seja rápido e dispare vários sonares. Atire uns para a direita e outros para esquerda. Os sonares ficarão parados na tela e só sumirão quando o tempo da 'Sub-Weapon' acabar. Dica: Quando o tempo do relógio estiver acabando, transforme-se em Alucard e use outro. Retorne à forma de morcego e continue a apertar <img src="~static/img/triangulo.gif" alt="Triângulo"/>.</li>
          <li><b>Transformações muito lentas:</b> Em Catacombs, na sala escura, faça a dica acima, usando dez ou mais sonares. Em seguida, ainda com o tempo parado, transforme-se em névoa, passe rapidamente para a forma de morcego ou lobo e volte rapidamente para a forma de Alucard e você ficará paralisado e invisível. (Melhor visualização na versão americana).</li>
          <li><b>Fazer o sonar subir na tela:</b> Deixe o sonar paralisado na tela como descrito acima, mova o morcego (ou Alucard) para cima do switch que acende a sala. (Essa dica pode ser feita sobre o teto dessa sala).</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) Lobo sem corpo e seu reflexo na barra de <abbr title="Magic Points">MP</abbr> (1):</b> Em Catacombs, entre na sala escura. Saia da sala, transforme-se em lobo e retorne para a sala. Agora você verá o lobo sem corpo e seu reflexo na barra de <abbr title="Magic Points">MP</abbr>.</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) Lobo sem corpo e seu reflexo na barra de <abbr title="Magic Points">MP</abbr> (2):</b> Estando na sala escura, transforme-se em lobo e saia da sala para que o reflexo dele esteja na barra de <abbr title="Magic Points">MP</abbr>. Saia da sala usando a magia 'Wolf Charge' e veja o que acontece com o lobo.</li>
          <li><b>Mist na escuridão:</b> Entre na sala escura na forma de mist. Às vezes é preciso que você transforme-se em Mist 1 ou 2 segundos antes de entrar na sala.</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) Sombras do Lobo na barra de <abbr title="Magic Points">MP</abbr>:</b> Em Catacombs, na parte da Lava, transforme-se em lobo e note que a sombra dele irá para a barra de <abbr title="Magic Points">MP</abbr>. Ele possui outra sombra que quase não se nota. É a sombra das patas dianteiras e da espada do lobo. Para vê-la com mais facilidade, segure <img src="~static/img/frente.gif" alt="Direita"/> e vá dando pequenos pulos. Você também pode vê-la assim que se transforma.</li>
          <li><b>(<abbr title="Japanese">JAP</abbr>) Sombra Estranha:</b> Na forma de lobo, segure <img src="~static/img/baixo.gif" alt="Baixo"/> e, sem soltar, transforme-se em Alucard e veja uma sombra "redonda".</li>
          <li><b>Névoa Negra:</b> Equipe o <Item item="Talisman"/>, transforme-se em Lobo e leve uma pancada. O <Item item="Talisman"/> deverá funcionar (Dependendo do seu <abbr title="Luck">LCK</abbr>). Antes que a "sombra do Alucard" suma da tela, transforme-se em névoa. Ela ficará preta e o <abbr title="Health Points">HP</abbr> ficará impresso nela. (permanentemente na versão Japonesa)</li>
          <li><b>Bug gráfico:</b> Faça a dica acima, só que, substitua a forma de mist pela forma de Alucard ou Morcego. Você verá que ele se transformará por instantes na sua própria barra de <abbr title="Health Points">HP</abbr>/<abbr title="Magic Points">MP</abbr>.</li>
        </ol>
      </main>
      <hr/>
      <Footer/>
    </div>
  </div>
</template>

<script>
  export default {}
</script>

<style scoped>
  li { margin-bottom: 15px; }
</style>