<template>
  <div>
    <Navbar/>
    <div class="container">
      <div class="breadcrumb">
        <NuxtLink to="/">GOD</NuxtLink> &raquo;
        <NuxtLink to="/sotn">Castlevania: Symphony of the Night</NuxtLink> &raquo;
        Oddities
      </div>
      <Header/>
      <h2>Oddities</h2>
      <hr/>
      <main>
        <center><NuxtLink to="oddities">Oddities</NuxtLink> | <NuxtLink to="easter-eggs">Easter Eggs</NuxtLink> | <NuxtLink to="bugs">Bugs</NuxtLink> | <NuxtLink to="glitches">Glitches</NuxtLink></center>
        <p>Here is a list of odd stuff cataloged by my castlevanian pal, <b>Jack (O' Bones) Wilker Barros</b>. Stuff that most players do not notice even after completely beat the game.</p>
        <ol>
        <li><b><Item item="Alucard shield"/> up close:</b> At the first option menu of the game, the background is a blue picture where you can see the Alucard Shield in detail.</li>
        <li><b>The system selects your name:</b> If you push 'START' in the "Name Select" screen without entry any letter. The name of your file will be automatically selected as "ALUCARD"</li>
        <li><b>About the Luck Mode (X-X!V''Q):</b> Most people think that it is necessary to beat the game first in order to this code work, but it's not true. You can make it right away the first time you play.</li>
        <li><b>If the Memory Cards are full:</b> The game will start just by pressing 'START'. If you have 2 memory cards plugged, both must be full.</li>
        <li><b>Gostly Memory Card:</b> With just one memory card plugged, select 'Name Change' and change the name of a file. During the confirmation the other memory card slot will show empty blocks instead of "NO MEMORY CARD".</li>
        <li><b>About the "Now Loading" phrase:</b> Most people knows that you can move this text during the load, but you can also make it stop moving by doing a little tap <img src="/img/tras.gif" alt="Left"/> and <img src="/img/baixo.gif" alt="Down"/>.</li>
        <li><b>Classic Richter:</b> The battle that occurs before the game starts for real is the ending of "Castlevania: Rondo of Blood". Some stuff in this prologue are different. If you quickly press the jump button, Richter will jump up as high as if you have pressed and held the button. And the Big Hearts (that worth 5) are dirrerent from the rest of the game (they don't spin).</li>
        <li><b>Different stuff in the prologue:</b> The stairs are still unbroken, there are different items inside the pots at the secret passage and there's a platform that is at a different height than when you play as Alucard.</li>
        <li><b>Strange chandeliers:</b> There are no candles in the room where Alucard confronts Richter, but after the battle and the <abbr title="Computer Graphics">CG</abbr> scene when the screen comes back to Alucard and Richter, there they are! You can break them before entering the room. Just get close to the entrance and attack or make a spell. You will hear the sound of the breaking chandelier.</li>
        <li><b>Missing lamp in the castle:</b> At the end of <NuxtLink to="maps/Marble-Gallery">Marble Gallery</NuxtLink>, there's a corridor with <NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink>s. Just before this corridor is there is a lamp holder with no lamp. This also can be found in another places in the castle.</li>
        <li><b>About the Central Clock:</b> It counts the play time. When the game starts as Richter, the clock in the inventory and the Central Clock are both on 00:00.</li>
        <li><b>Mysteries on the Clock :</b> It has two skulls that moves inside it each 20 minutes. When the minute's hand reach "X" they hide, at "II" they show up, up, and at "VI" they get down.</li>
        <li><b>Strange number on the Clock:</b> The number 4 is writen as "IIII". Normally it is writen as "IV". I heard that it's to improve the Clock's esthetics.</li>
        <li><b>The Clock gets stuck:</b> When the game time reaches 99:59:59 the Central Clock stops working. The left passage that leads to <NuxtLink to="maps/Olrox's-Quarters">Olrox's Quarters</NuxtLink> won't open anymore and the skulls will stop moving but you still can hear the "tic-tac".</li>
        <li><b>Alternative way to open the Rituals Room passage:</b> Equip two <Item item="Silver Ring"/>s or two <Item item="Gold Ring"/>s. (Game Shark needed).</li>
        <li><b>Central Clock passages:</b> The left one is 1 minute opened and 1 minute closed, working everytime the seconds reach "00" being closed at odd and open at even minutes. The right one opens when the 'Stop Watch' sub-weapon is used and waits the duration time of the 'Stop Watch'.</li>
        <li><b>You can attack the Central Clock statues:</b> When they are moving. And you can also perform 'Dive kicks' to climb them.</li>
        <li><b>The Central Clock passages never closes:</b> If you stay flying at the same height as the statues.</li>
        <li><b>Places where you can't use the 'Stop Watch':</b> At the Master Librarian's shop and at the Confession Room in <NuxtLink to="maps/Royal-Chapel">Royal Chapel</NuxtLink>.</li>
        <li><b>Music at the inventory:</b> Open it at the Master Librarian's shop or at the Confession Room.</li>
        <li><b>The items from under Master Librarian:</b> To get them you have to make various 'Hyper Jumps' and take the old man's chair off the ground every time. In the first jump you will get a <b>Life Max Up</b>. Doing a chain of nearly 15 jumps, you will get a <Item item="Ring of Arcana"/>. Doing like 8 more (aproximately 23 chained) the <Item item="Dracula tunic"/> will drop. And when you jump around 60 times in total (no need to be chained), you will get a <Item item="Axe Lord armor"/>. Note: You need to reach the Reverse Castle in order to drop the <Item item="Dracula tunic"/>.</li>
        <li><b>Richter gets the Master Librarian's items:</b> They are Hearts...</li>
        <li><b>Alternative way to run as Richter:</b> <img src="/img/tras.gif" alt="Left"/>, <img src="/img/frente.gif" alt="Right"/></li>
        <li><b>Alternative way to run as Wolf:</b> Facing right, press <img src="/img/tras.gif" alt="Left"/>, and when the Wolf turns to the other side, hold <img src="/img/frente.gif" alt="Right"/>.</li>
        <li><b>Wolf moves backwards:</b> As Wolf, do <img src="/img/tras.gif" alt="Left"/>, <img src="/img/baixo.gif" alt="Down"/> repeatedly.</li>
        <li><b>Wolf runs in mid air:</b> Stand at the border of a ledge make a 'Wolf Charge'.</li>
        <li><b>Wolf jumps in mid air:</b> Do the above and before the end of the skill, press <img src="/img/x.gif" alt="X"/>.</li>
        <li><b>Wolf's Super jump:</b> Run over some stairs and press <img src="/img/x.gif" alt="X"/>. No needs to be too fast.</li>
        <li><b>Wolf's Back Attack:</b> <img src="/img/baixo.gif" alt="Down"/> <img src="/img/baixofrente.gif" alt="Down/Right"/> <img src="/img/frente.gif" alt="Right"/> <img src="/img/tras.gif" alt="Left"/> + <img src="/img/quadrado.gif" alt="Quadrado"/> (Needs the <Item item="Skill of Wolf"/> Relic).</li>
        <li><b>Swiming Wolf:</b> Press <img src="/img/triangulo.gif" alt=""/> (underwater, of course).</li>
        <li><b>Higher Wolf jump:</b> <img src="/img/cima.gif" alt="Up"/> + <img src="/img/x.gif" alt="X"/>.</li>
        <li><b>Bat and Wolf with 'Dark Metamorphosis':</b> Just equip the <Item item="Muramasa"/>.</li>
        <li><b>(<abbr title="United States of America">USA</abbr>) Long Wing Smash:</b> Do the spell repeatedly before it ends. This way you can get through large corridors with a single 'Wing Smash'.</li>
        <li><b>Mist in front of the bells:</b> The bells appears in front of everything else in the game, except the mist.</li>
        <li><b>The bells gives invulnerability:</b> When you are inside a <NuxtLink to="maps/Royal-Chapel">Royal Chapel</NuxtLink>'s bell you become invulnerable.</li>
        <li><b>About the bells:</b> If you are inside a bell and decide to get down you become invulnerable, even when you are completely out of the bell. The invulnerability wears off just before you reach the ground.</li>
        <li><b>The bells cancels some commands:</b> While you are inside the bells the attack and jump commands won't work. Richter can't do anything inside the bells.</li>
        <li><b>Odd stuff about the bells:</b> When you're inside a bell you can turn into mist, bat and wolf. The odd stuff is that you can switch to mist from bat and bat from mist, but if you turn into wolf you can't turn into something else and will fall.</li>
        <li><b>The bells and the double jump:</b> If you get inside the bell using double jump, Alucard hits his head at some kind of ceiling.</li>
        <li><b>Self-repairing wall:</b> In <NuxtLink to="maps/Catacombs">Catacombs</NuxtLink>, break only the lower portion of the wall that blocks the way to the <Item item="Icebrand"/>, then go through the gap using the wolf, bat or mist form. Enter the room and come back. The wall will rebuild itself. This happens to any wall with two breakable sections.</li>
        <li><b>By the telescope in <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> you can see:</b> nothing; one, two or three fish jumping varying in 6 different positions and different timing; Ferryman with or without fishes; a piece of the boat varying in two sizes going away, with or without fishes; all these variatins with different wheather (normal, rain or mist).</li>
        <li><b>The telescope's hint:</b> My theory is that the <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> is in someway linked  to <NuxtLink to="maps/Underground-Caverns">Underground Caverns</NuxtLink> where the Ferryman is, as from <b>Reverse Caverns</b> you can reach the "3rd Outer Wall".</li>
        <li><b>The area's name always appear when you enter:</b> If you get to another room before the name of the area is completelly shown. If it start to vanish it's too late. When you come back to the room where it appear it will be shown again.</li>
        <li><b>What exactly to do to open the <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink> passage:</b> Coming right to left, in the first tower, hit the higher gear 14 times and 3 times the lower one. In the second tower, hit the lower gear 2 times and 8 times the lower one which is above the gate.</li>
        <li><b>A complete spin of the gears is equal to 15 hits:</b> If one of the gears in <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink> just made "click", you need to hit it more 15 times in order to hear another "click".</li>
        <li><b>The <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> secret lift:</b> Did you notice that the secret lift which moves if you stand over it for 20 seconds is identic or similar to the lifts in the Teleport Pads in the Inverted Castle?</li>
        <li><b>The clue the game gives about this lift:</b> There's an <NuxtLink to="enemies/Armor-Lord">Armor Lord</NuxtLink> guarding the entrance to the room with the secret lift and if you kill it, it won't reappear until you pass through a <abbr title="CD Load Room">CDLR</abbr>. The second is a bit more hard to notice but nearby, scattered through the scennery there are sculptures similar to the Teleport Pads lifts in the Inverted Castle. Maybe three, but these scupltures don't have the same size or colour. One of them is at the telescope room above the vase.</li>
        <li><b>About the switches that activates elevators and spears:</b> You can activate by touching or attacking them.</li>
        <li><b>The <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> elevator waits for you:</b> The <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> elevator is relocated depending on the room you come from. If you come from the teleport pad room (escorpion), it stays up. From the Library, it stays in the middle. From the <NuxtLink to="enemies/Doppleganger10">Doppleganger10</NuxtLink> room, it stays down.</li>
        <li><b>The <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> elevator moves you aside:</b> Without pressing the D-pad right or left, repeatedly use the elevator up and down. In a given moment it won't work because you aren't positioned in the middle of the elevator.</li>
        <li><b>Summoning the elevators:</b> If you are on a different floor from the one which the lift is, press <img src="/img/cima.gif" alt="Up"/> or <img src="/img/baixo.gif" alt="Down"/> to call the elevator faster. If you just stand waiting it will come, but it takes a little longer.</li>
        <li><b>Noise in the <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>'s lift:</b> Move the elevator to the third floor. Listen to the sound it makes when it stops. Turn into a bat and alternate rapidly between the second and third floor. Whenever you change screens you'll hear a sound and the elevator moves a bit down.</li>
        <li><b>The real effect of the lever that is supposed to activate the <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> Elevator:</b> It simply opens the <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> elevator door and activates the <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>'s lift. The other elevators including the one in <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> can be used without activating the lever.</li>
        <li><b>To activate the lever:</b> Most people attacks it, but you can push it with your body as you push a block.</li>
        <li><b>Attacking with 'Curse':</b> Just remove the items from the hands. (You can use spells and sub-weapons as well).</li>
        <li><b><Item item="Axe Lord armor"/> protects against everything:</b> Poison, curse, stone and from grabs from <NuxtLink to="enemies/Akmodan-II">Akmodan II</NuxtLink>, <NuxtLink to="enemies/Succubus">Succubus</NuxtLink> and <NuxtLink to="enemies/Darkwing-Bat">Darkwing Bat</NuxtLink>.</li>
        <li><b><abbr title="Magic Points">MP</abbr> doesn't fill if Alucard is:</b> Petrified, using the <Item item="Axe Lord armor"/> or at the Master Librarian's menu.</li>
        <li><b>When the <abbr title="Magic Points">MP</abbr> fill up, Alucard glows:</b> But if Alucard is sitting when it fills, he will only glow when he get up.</li>
        <li><b>Not coded bigger aura:</b> If Alucard is using <Item item="Secret boots"/> and uses the Stop Watch, he won't left the white aura.</li>
        <li><b>Bat Familiar Super Combo:</b> Approach the <NuxtLink to="enemies/Discus-Lord">Discus Lord</NuxtLink> with 'Bat Familiar'. Get down right next to it and wait for the Bat to attack. Once it starts the attack, it will only stop when the <NuxtLink to="enemies/Discus-Lord">Discus Lord</NuxtLink> dies.</li>
        <li><b>'Ghost Familiar' oddity:</b> Find a room with a screen change above. Turn into a bat and the 'Ghost Familiar' will flee. Then follow the Ghost with the bat. When you arrive the other room, the 'Ghost Familar' will be there, but it will quickly disappear. Keep alternating between the upper and the lower room to notice more easily.</li>
        <li><b>'Ghost Familiar' also flee if you equip the <Item item="Axe Lord armor"/>.</b> Besides when you turn into bat.</li>
        <li><b>'Faerie Familiar' wastes your items:</b> Use an <Item item="Antivenom"/> or <Item item="Uncurse"/> without need. She will use another right after!</li>
        <li><b>Change the pose of the allies:</b>Call one of the familiars, except the Ghost and Bat and stay put. When the ally is present, open the cover of the Playstation before it say something. With the cover still open, walk around the room (don't leave or the game will freeze). While walking, notice that the ally is stil in its presentation position. After about 3 minutes, close the PlayStation cover and the familiar will stay in this position throughout the area. The Sword won't attack and won't listen to 'Sword Brothers' command. The Faerie is always looking at the screen. The Pixie is always vibrating (jumping). The Demon doesn't attack. Always wielding its spear looking at the screen with flashing red eyes. The Nose Demon, with the cover open, stares at the screen laughing. With the cover closed it stares at the screen seriously.</li>
        <li><b>Sluggish Faerie:</b> Doing the above, the familiars become slow, except the Sword. Do it with the Faerie in <NuxtLink to="maps/Olrox's-Quarters">Olrox's Quarters</NuxtLink>, near the passage to <NuxtLink to="maps/Royal-Chapel">Royal Chapel</NuxtLink>. With the playstation cover already closed, turn into wolf and run as fast as you can. Get to the spiked corridor and die!! The Faerie will take an eternity to ressurect you.</li>
        <li><b>'Faerie Familiar' cryes:</b> The Faerie makes about three different cryes when she falls from Alucard's shoulders.</li>
        <li><b>Alucard can use without make the Faerie fall from his shoulder:</b> <Item item="Crissaegrim"/>, <Item item="Chakram"/>, <Item item="Blue knuckles"/>, <Item item="Yasutsuna"/>, <Item item="Holbein dagger"/>, <Item item="Heaven Sword"/>, <Item item="Vorpal blade"/>, <Item item="Runesword"/> (Weapons he can use without stop walking) and all [USE] items.</li>
        <li><b>About the <img src="/img/tras.gif" alt="Left"/> <img src="/img/frente.gif" alt="Right"/> Special moves of knives and rods:</b> They also can be made in the air, chounching and diagonally downwards.</li>
        <li><b>Multiple ways to make the <Item item="Combat Knife"/>'s horizontal attack:</b> Considering it's equipped in the right hand. 1: <img src="/img/tras.gif" alt="Left"/> <img src="/img/frente.gif" alt="Right"/> + <img src="/img/quadrado.gif" alt="Quadrado"/>. 2: <img src="/img/baixo.gif" alt="Down"/> <img src="/img/frente.gif" alt="Right"/> + <img src="/img/quadrado.gif" alt="Quadrado"/>. 3: <img src="/img/quadrado.gif" alt="Quadrado"/> hold, release and press again quickly. Attack twice quickly, in addition to the combinations above.</li>
        <li><b><Item item="Gurthang"/> and its effects:</b> If you are under 'Dark Metamorphosis' effect, it becomes more powerful. Use its special (<img src="/img/baixo.gif" alt="Down"/> <img src="/img/frente.gif" alt="Right"/> + <img src="/img/quadrado.gif" alt="Quadrado"/> or <img src="/img/circulo.gif" alt="Círculo"/>) and it will become even more powerful. Keep attacking after the special move and all the subsequent attacks will have the same power as the special move.</li>
        <li><b><Item item="Sword of Dawn"/> Special fails:</b> Make the move at the border of a ledge or platform.</li>
        <li><b><Item item="Runesword"/>'s mystery:</b> Equip two of them. If you press <img src="/img/quadrado.gif" alt="Quadrado"/>, <img src="/img/circulo.gif" alt="Círculo"/>, Alucard will throw 2 swords, but if you press <img src="/img/circulo.gif" alt="Círculo"/>, <img src="/img/quadrado.gif" alt="Quadrado"/>, he will throw just one.</li>
        <li><b><Item item="Holy Sword"/> and <NuxtLink to="items/Holy-rod">Holy Rod</NuxtLink> angel:</b> When you make the special move of these weapons the image of an angel is shown very briefly. It's the same for both weapons.</li>
        <li><b>The two <Item item="Heart Refresh"/> angels are different:</b> The left one seems to be a woman and the letf one, a man, androgen, but a man.</li>
        <li><b><Item item="Gold Ring"/> is in the air:</b> After defeating <NuxtLink to="enemies/Succubus">Succubus</NuxtLink> and come back from the Nightmare, the <Item item="Gold Ring"/> appears to the right. Exit the room without getting it. Come back to the room and notice that the ring falls as if something have dropped it. Keep alternating the screen to notice that it stays in a relatively high height! This can be made with several other items.</li>
        <li><b>Eating <Item item="Peanuts"/>:</b> Throw it, postion Alucard where it will fall and press <img src="/img/cima.gif" alt="Up"/>.</li>
        <li><b><Item item="Monster vial 1"/> is guided:</b> If the enemy is above it goes up, if the enemy is below it goes up.</li>
        <li><b>If there are no enemies, where the <Item item="Monster Vial 1"/> goes to?</b> Mostly of the time it follows something depending on which point of the room it's used. Normally it goes straightly or just a little up.</li>
        <li><b><Item item="Monster vial 3"/> (maybe also the 2) makes 33 hits:</b> Throw it to make it appear just where the enemy is.</li>
        <li><b>(<abbr title="Japanese">JAP</abbr>) Follow the <Item item="Power of Sire"/>'s light:</b> In <NuxtLink to="Underground Caverns">Underground Caverns</NuxtLink> or <b>Reverse Caverns</b>, at that big fall near the purple coffing room, do some 'Hyper Jumps' and when you're high enough, use the <Item item="Power of Sire"/>. If it shoots down you'll fall along the light and it continues falling even after the effect of the item has gone.</li>
        <li><b><Item item="Bat Pentagram"/> has two faces:</b> The image that appears if you equip it on the right hand is different than when you equip it on the left hand.</li>
        <li><b><Item item="Iron ball"/> rolls down the stairs:</b> Use it at <NuxtLink to="maps/Outer-Wall">Outer Wall</NuxtLink> near the elevator and follow it. It will roll down the stairs killing the enemies as the <NuxtLink to="enemies/Bone-Pillar">Spiked Ball</NuxtLink> does in <NuxtLink to="maps/Royal-Chapel">Royal Chapel</NuxtLink>.</li>
        <li><b><Item item="Shuriken"/>s gets nailed on enemies:</b> When it hits the target it got nailed for a little while. Throw it at candles to notice more easily.</li>
        <li><b><Item item="Magic Missile"/> does 2 hits:</b> Basta que ela pegue bem apoiada em um inimigo.</li>
        <li><b><Item item="Dynamite"/> fails:</b> Sometimes when you use a <Item item="Dynamite"/>, Alucard throws it unlit and it doesn't explodes.</li>
        <li><b><Item item="TNT"/> hits enemies before explode:</b> When Alucard throws it, if it hits an enemy before explode it will cause 1 HIT damage.</li>
        <li><b><Item item="TNT"/> attack types:</b> The first and second hit it causes when it explodes has fire effect, the following ones aren't. And when it's almost gone, it makes about three hits with fire effect.</li>
        <li><b>Fake fire:</b> The fireballs from <Item item="Monster vial 1"/> and from <Item item="Sword of Dawn"/> special move doesn't have fire effect.</li>
        <li><b>(BUG) Where are the H2O Elemental?</b> The enemy list says that some enemies absorbs or are immune to H2O. (<NuxtLink to="enemies\Frozen-Shade">Frozen Shade</NuxtLink>, <NuxtLink to="enemies/Merman2">Merman2</NuxtLink>, <NuxtLink to="enemies/Merman3">Merman3</NuxtLink>, <NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink>, <NuxtLink to="enemies/Scylla-Wyrm">Scylla Wyrm</NuxtLink>, <NuxtLink to="enemies\Toad">Toad</NuxtLink>, <NuxtLink to="enemies\Scylla">Scylla</NuxtLink> and <NuxtLink to="enemies\Frozen-Half">Frozen Half</NuxtLink>). But there's not any attack with H2O effect.</li>
        <li><b><NuxtLink to="enemies/Slime">Slime</NuxtLink> colorful death:</b> Kill it using a weapon with an elemental effect when it is in the ceiling. It will die with the element's color.</li>
        <li><b>2 kinds of <NuxtLink to="enemies/Sword-Lord">Sword Lord</NuxtLink>s:</b> One of them turns into <NuxtLink to="enemies/Vandal-Sword">Vandal Sword</NuxtLink> the other does not.</li>
        <li><b>2 kinds of <NuxtLink to="enemies/Stone-Skull">Stone Skull</NuxtLink> only one is in the Enemy List:</b> The one that is missing is the bull skull found in Reverse Collosseum.</li>
        <li><b>Duplicated names in the Enemy List:</b> Merman: <NuxtLink to="enemies/Merman2">Nº 6</NuxtLink> and <NuxtLink to="enemies/Merman3">Nº10</NuxtLink>. Axe Knight: <NuxtLink to="enemies/Axe-Knight4">Nº 12</NuxtLink> and <NuxtLink to="enemies/Axe-Knight9">Nº 30</NuxtLink>. Medusa Head. O <NuxtLink to="enemies/Medusa-Head7">Nº24</NuxtLink> and <NuxtLink to="enemies/Medusa-Head8">Nº27</NuxtLink>. Spectral Sword: <NuxtLink to="enemies/Spectral-Sword13">Nº57</NuxtLink>, <NuxtLink to="enemies/Spectral-Sword15">Nº63</NuxtLink> and <NuxtLink to="enemies/Spectral-Sword36">Nº119</NuxtLink>. Werewolf: <NuxtLink to="enemies/Werewolf18">Nº75</NuxtLink> and <NuxtLink to="enemies/Werewolf34">Nº108</NuxtLink>.</li>
        <li><b>Incomplete Tactics List:</b> There's no Tactics recorded for <NuxtLink to="enemies/Lesser-Demon">Lesser Demon</NuxtLink> Boss.</li>
        <li><b>Easier way to cast the 'Summon Spirit' spell:</b> Facing right, press <img src="/img/tras.gif" alt="Left"/> <img src="/img/cima.gif" alt="Up"/> <img src="/img/baixo.gif" alt="Down"/> + <img src="/img/quadrado.gif" alt="Quadrado"/> or <img src="/img/circulo.gif" alt="Círculo"/>.</li>
        <li><b>Secret Spells:</b> 'Wolf Charge', 'Wing Smash', and 'Sword Brothers'. These you need to discover for yourself. The others you can buy its scrolls at the Librarian Shop.</li>
        <li><b>Weird Hyper Jump:</b> From <NuxtLink to="maps/Abandoned-Mine">Abandoned Mine</NuxtLink>, go to <NuxtLink to="maps/Underground-Caverns">Underground Caverns</NuxtLink>. Once you arrive, use a super jump diagonally. There are other places you can do that kind of Hyper Jump, but it is difficult to explain.</li>
        <li><b>Shielded Hyper Jump:</b> Press <img src="/img/baixo.gif" alt="Down"/>, hold the shield, press <img src="/img/cima.gif" alt="Up"/> + <img src="/img/x.gif" alt="X"/>.</li>
        <li><b>Floating shield:</b> Use a <Item item="Library Card"/> while holding a shield. If you are using the 'Sword Familiar', It will look like a ghost warrior. (the flying sword and shield. :P)</li>
        <li><b>Uma animação de escudo inédita:</b> quando você leva uma pancada segurando o escudo, ele sai voando (comum). Morra segurando o escudo e o escudo sairá girando! (esta é a inédita.) É um pouco difícil de perceber. Se não ficar claro com um escudo, tente com outro.</li>
        <li><b>Qualquer escudo defende os <NuxtLink to="enemies/Bat">Bat</NuxtLink>s e <NuxtLink to="enemies/Ghost">Ghost</NuxtLink>s:</b> Segure qualquer escudo e deixe que um <NuxtLink to="enemies/Bat">Bat</NuxtLink> ou um <NuxtLink to="enemies/Ghost">Ghost</NuxtLink> toque nele. Você verá que os inimigos tocam o escudo, mas não sofrem nenhum dano.</li>
        <li><b>Você pode subir na cabeça de:</b> <NuxtLink to="enemies/Diplocephalus">Diplocephalus</NuxtLink>, <NuxtLink to="enemies/Paranthropus">Paranthropus</NuxtLink>, <NuxtLink to="enemies/Fishhead">Fishhead</NuxtLink> e <NuxtLink to="enemies/Gorgon">Gorgon</NuxtLink>.</li>
        <li><b>O inimigo que grita "stop!":</b> <NuxtLink to="enemies/Gurkha">Gurkha</NuxtLink>.</li>
        <li><b>Inimigos que "mangam" de Alucard:</b> <NuxtLink to="enemies/Ctulhu">Ctulhu</NuxtLink>, <NuxtLink to="enemies/Malachi">Malachi</NuxtLink>, <NuxtLink to="enemies/Richter-Belmont">Richter Belmont</NuxtLink>, <NuxtLink to="enemies/Doppleganger10">Doppleganger10</NuxtLink> e <NuxtLink to="enemies/Fake-Trevor">Fake Trevor</NuxtLink>. Se você morrer para eles, eles farão uma pose característica.</li>
        <li><b><NuxtLink to="enemies/Orobourous">Orobourous</NuxtLink> tornam-se seus aliados:</b> Se você matar o flea man que o controla, mas depois de um tempo eles vão embora.</li>
        <li><b>Rival da 'Sword Familiar':</b> <NuxtLink to="enemies/Azaghal">Azaghal</NuxtLink>. A 'Sword Familiar' ataca o inimigo <NuxtLink to="enemies/Azaghal">Azaghal</NuxtLink> de maneira diferente. Se ela estiver num level maior que 70, quando pára de girar. Quando ela atacar, ela fará um "tremelique".</li>
        <li><b><NuxtLink to="enemies/Paranthropus">Paranthropus</NuxtLink> morre de olho em seu carrasco:</b> Normalmente se mata esse monstro pela frente, mas espere que ele inicie um ataque e passe para as costas dele e mate-o. A cabeça dele fica olhando para você.</li>
        <li><b>Terceiro ataque de <NuxtLink to="enemies/Skeleton-Ape">Skeleton Ape</NuxtLink>:</b> Após ele arremeçar o barril, pule para trás dele e fique bem próximo das costas dele. Ele dará uma cotovelada.</li>
        <li><b><NuxtLink to="enemies/Bone-Ark">Bone Ark</NuxtLink> só ataca para frente:</b> Se você ficar atrás, ele não atacará com a esfera de energia.</li>
        <li><b><NuxtLink to="enemies/Skelerang">Skelerang</NuxtLink> se abaixa:</b> Apenas aproxime-se dele. Ele se encolherá com medo.</li>
        <li><b><NuxtLink to="enemies/Bloody-Zombie">Bloody Zombie</NuxtLink> covarde:</b> Se você virar as costas para este inimigo ele vem correndo e lhe ataca pelas costas. Se você ficar olhando para ele, ele o ignora.</li>
        <li><b>O ataque da <NuxtLink to="enemies/Salome">Salome</NuxtLink> que se autodestrói:</b> A <NuxtLink to="enemies/Salome">Salome</NuxtLink> joga um crânio que fica quicando no chão. não deixe que ele suma da tela. Para isso siga-o a onde quer que ele for. Depois de algum tempo, ele racha e se quebra. Não sei por que perderam tempo programando isso no jogo.</li>
        <li><b>(<abbr title="Japanese">JAP</abbr>) Sobre a magia de <NuxtLink to="enemies/Lossoth">Lossoth</NuxtLink>:</b> <NuxtLink to="enemies/Lossoth">Lossoth</NuxtLink> tem um ataque que é uma onda de fogo, que mais parece um monstro, pois se você a atacar, esse fogo irá "morrer" (sem desaparecer) e você poderá acompanhá-lo até o outro lado da sala dentro dele sem receber dano. Se preferir ataque-o com um escudo, em seguida use o 'Backdash' para acompanhar a onda de fogo sem receber dano.</li>
        <li><b>Mudar a posição das <NuxtLink to="enemies/Hunting-Girl">Hunting Girl</NuxtLink>s:</b> Saindo da sala de save à Right de <NuxtLink to="maps/Colosseum">Colosseum</NuxtLink>, suba na escadinha que tem bem na entrada da sala, vire morcego e siga para a Left até tocar a parede. Então dê um toque para Down para poder seguir caminho. Continue para a Left até avistar a <NuxtLink to="enemies/Hunting-Girl">Hunting Girl</NuxtLink>. Observe que ela está em uma posição bem mais alta do que costuma. Segure para Down para encostar no piso. Passe por Down dela. Siga até avistar a outra e veja que ela está bem mais aDown do que costuma. Você pode passar por Up dela e elas não lhe atacarão.</li>
        <li><b>Fazer as <NuxtLink to="enemies/Hunting-Girl">Hunting Girl</NuxtLink>s subirem ou descerem:</b> Na sala citada na dica anterior, atraia uma <NuxtLink to="enemies/Hunting-Girl">Hunting Girl</NuxtLink> até o buraco antes da sala de save, transforme-se em morcego e comece a descer pelo buraco. Ela lhe seguirá. Obs.: ela não pode sumir da tela. Se você se destransformar ela tornará a subir.</li>
        <li><b><NuxtLink to="enemies/Hunting-Girl">Hunting Girl</NuxtLink> tem três ataques:</b> O primeiro ela desenha uma estrela de 5 pontas, as outras formas são bem distintas mas difíceis de se descrever com palavras.</li>
        <li><b><NuxtLink to="enemies/Blade">Blade</NuxtLink>, <NuxtLink to="enemies/Gurkha">Gurkha</NuxtLink> e <NuxtLink to="enemies/Hammer">Hammer</NuxtLink> são Irmãos:</b> É isso que diz na descrição dos três.</li>
        <li><b><NuxtLink to="enemies/Discus-Lord">Discus Lord</NuxtLink> joga o disco para Up:</b> Basta ficar longe dele e voando.</li>
        <li><b><NuxtLink to="enemies/Flea-Man">Flea Man</NuxtLink> não te ataca:</b> Passe voando por Up dele (não muito alto).</li>
        <li><b>Quando <NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink> abre?:</b> Após tirar 30 de <abbr title="Health Points">HP</abbr> dela. (Tem 60 <abbr title="Health Points">HP</abbr> no total).</li>
        <li><b><NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink> tremendo e confusa:</b> Tire o <abbr title="Health Points">HP</abbr> dela para que ela fique aberta, então a ataque com a <Item item="Mormegil"/> para que ela absorva o seu ataque. Agora jogue <Item item="TNT"/> de modo que só tire 1 de <abbr title="Health Points">HP</abbr> dela (mencionado anteriormente), então vire lobo para evitar a explosão. Obs.: Depois de aberta a Stone Rose se fechará!</li>
        <li><b><NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink>s se regeneram</b> Os golpes que você desfere na forma pequena da <NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink> e da <NuxtLink to="enemies/Blue-Venus-Weed">Blue Venus Weed</NuxtLink> não contam para matar a forma grande.</li>
        <li><b><NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink>s têm três tons de cor:</b> Basta que você deixe que ela lhe acerte de modo que seu sangue jorre nela. A última cor é vermelho intenso.</li>
        <li><b>O ataque da <NuxtLink to="enemies/Blue-Venus-Weed">Blue Venus Weed</NuxtLink> e da <NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink> mudam de cor:</b> note que elas jogam umas rosas brancas em você, quando essas rosas tocam o acertam, elas mudam de cor. Use uma poção para notar melhor.</li>
        <li><b>Espírito de corvo por trás do <NuxtLink to="enemies/Karasuman">Karasuman</NuxtLink>:</b> Quando ele é destruído, note que tem uma aura de um corvo por trás dele de asas abertas maior do que o próprio <NuxtLink to="enemies/Karasuman">Karasuman</NuxtLink>.</li>
        <li><b>Diferença entre os <NuxtLink to="enemies/Jack-O'Bones">Jack O'Bones</NuxtLink> branco e laranja:</b> O branco joga o ossos para frente e seu ataque não se destrói. O laranja joga seu osso para Down (quica no chão) e seu ataque se autodestrói.</li>
        <li><b>A velocidade do osso que o <NuxtLink to="enemies/Jack-O'Bones">Jack O'Bones</NuxtLink> branco atira:</b> É exatamente a mesma de movimento do Alucard com <Item item="Axe Lord armor"/>.</li>
        <li><b>A velocidade do <NuxtLink to="enemies/Dodo-Bird">Dodo Bird</NuxtLink>:</b> É exatamente a mesma de Alucard.</li>
        <li><b><NuxtLink to="enemies/Flea-Man">Flea Man</NuxtLink> sem nome e não catalogado:</b> É a criatura que fica em Up do <NuxtLink to="enemies/Orobourous">Orobourous</NuxtLink>.</li>
        <li><b><NuxtLink to="enemies/Dark-Octopus">Dark Octopus</NuxtLink> tem duas partes:</b> A parte de Down e a parte de Up. As pancadas que atingem uma das partes não contam para destruir a outra parte.</li>
        <li><b><NuxtLink to="enemies/Fire-Demon">Fire Demon</NuxtLink> mostra sua garra:</b> Mate-o quando ele fizer o terceiro movimento de andar (quando ele estiver com o braço bem esticado).</li>
        <li><b>As <NuxtLink to="enemies/Black-Panther">Black Panther</NuxtLink>s não se esquivam:</b> Do ataque normal do lobo, de magias, sub-weapons, itens [use] e ataque dos familiars.</li>
        <li><b>O <NuxtLink to="enemies/Axe-Knight9">Axe Knight LV 9</NuxtLink> tem duas animações para morrer:</b> Na mais comum ele morre se desmontando, na outra ele morre sem se desmontar. Para isso mate-o quando ele mudar a passada e esconder o seu machado. Nesse tipo de morte ele emite um flash de luz branca. Na outra não.</li>
        <li><b>O pescoço de <NuxtLink to="enemies/Scylla-wyrm">Scylla wyrm</NuxtLink> é inofensivo:</b> Tente passar por esse local e você não será atingido. É muito difícil de fazer, pois ela não pára quieta! (Use o Stop Watch para facilitar.)</li>
        <li><b>O Barril do <NuxtLink to="enemies/Skeleton-Ape">Skeleton Ape</NuxtLink> reaparece:</b> Após o barril dele ser destruído (por você ou por ele), fuja para bem longe e retorne.</li>
        <li><b>O mostro <NuxtLink to="enemies/Owl">Owl</NuxtLink> está em duas fotos:</b> Na de <NuxtLink to="enemies/Owl">Nº35</NuxtLink> e na de <NuxtLink to="enemies/Owl-Knight">Nº62</NuxtLink>.</li>
        <li><b>Inimigos com vários tipos de cores:</b> <NuxtLink to="enemies/Zombie">Zombie</NuxtLink>: Laranja claro, laranja escuro e vermelho. <NuxtLink to="enemies/Bone-Musket">Bone Musket</NuxtLink>: um mais claro e um mais escuro. <NuxtLink to="enemies/Ectoplasm">Ectoplasm</NuxtLink>: Verde e roxo. <NuxtLink to="enemies/Blood-Skeleton">Blood Skeleton</NuxtLink>: O verde, o amarelo, o branco e o vermelho.</li>
        <li><b>Vários tipos de <NuxtLink to="enemies/Blood-Skeleton">Blood Skeleton</NuxtLink>s:</b> Cada tipo de <NuxtLink to="enemies/Blood-Skeleton">Blood Skeleton</NuxtLink>, distinguidos pela cor, tem um tempo de se recompor diferente. O <abbr title="Health Points">HP</abbr> de todos é 9, mas depois que se desmontam uma vez, qualquer ataque ou até mesmo encostar nele, fará com que se desmonte novamente.</li>
        <li><b>3 tipos de <NuxtLink to="enemies/Bone-Scimitar">Bone Scimitar</NuxtLink>:</b> O comum é o de ossos brancos e equipamento azul. Os demais aparecem no início do jogo em <NuxtLink to="maps/Entrance">Entrance</NuxtLink>. O de ossos Amarelos e equipamento verde sempre dropa <Item item="Red rust"/>. O de ossos brancos e equipamento verde sempre dropa <Item item="Short sword"/>. Você sempre pega a <Item item="Red rust"/>que é o item raro no começo, mas se você não dropar do <NuxtLink to="enemies/Bone-Scimitar">Bone Scimitar</NuxtLink> branco, ele não aparecerá na Enemy List.</li>
        <li><b>3 tipos de <NuxtLink to="enemies/Merman2">Merman</NuxtLink>s:</b> O amarelo usa um slide e atira uma pequena bola de fogo. O vermelho ataca com uma grande bola de fogo e o roxo só fica passeando.</li>
        <li><b><NuxtLink to="enemies/Thornweed">Thornweed</NuxtLink> tem vários tipos:</b> As <NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink>s e o <NuxtLink to="enemies/Corpseweed">Corpseweed</NuxtLink> nascem de <NuxtLink to="enemies/Thornweed">Thornweed</NuxtLink>s. Cada <NuxtLink to="enemies/Thornweed">Thornweed</NuxtLink> tem seu <abbr title="Health Points">HP</abbr> próprio. Aliás, o <abbr title="Health Points">HP</abbr> desses monstros que é exibido na Enemy List é o <abbr title="Health Points">HP</abbr> do <NuxtLink to="enemies/Thornweed">Thornweed</NuxtLink> do qual nascem.</li>
        <li><b>Inimigos blindados:</b> <NuxtLink to="enemies/Flea-Armor">Flea Armor</NuxtLink> tem blindagem na ponta do seu machado. <NuxtLink to="enemies/Paranthropus">Paranthropus</NuxtLink> tem blindagem no osso que segura. <NuxtLink to="enemies/Diplocephalus">Diplocephalus</NuxtLink>, toda sua calda e patas são blindadas. <NuxtLink to="enemies/Ouija-Table">Ouija Table</NuxtLink>, os objetos que voam são blindados. <NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink> é toda blindada, exceto sua cabeça, <NuxtLink to="enemies/Stone-Skull">Stone Skull</NuxtLink> é totalmente blindada (indestrutível).</li>
        <li><b>Ponto fraco de alguns inimigos:</b> <NuxtLink to="enemies/Minotaur">Minotaur</NuxtLink>, <NuxtLink to="enemies/Hippogryph">Hippogryph</NuxtLink> e <NuxtLink to="enemies/Galamoth">Galamoth</NuxtLink>, Na cabeça. <NuxtLink to="enemies/Blade">Blade</NuxtLink> <NuxtLink to="enemies/Gurkha">Gurkha</NuxtLink> e <NuxtLink to="enemies/Hammer">Hammer</NuxtLink>, ataque-os de pé. <NuxtLink to="enemies/Bomb-Knight">Bomb Knight</NuxtLink> e <NuxtLink to="enemies/Rock-Knight">Rock Knight</NuxtLink>: Na mão, quando ele estiver segurando a pedra. Uma só pancada pode causar vários hits.</li>
        <li><b><NuxtLink to="enemies/Gorgon">Gorgon</NuxtLink> tem muitos pontos atacáveis:</b> Perna Left, perna Right, casco, tronco e cabeça. sendo a cabeça o seu ponto fraco.</li>
        <li><b>Inimigos que reaparecem:</b> <NuxtLink to="enemies/Yorick">Skull</NuxtLink>, desde que você não mate o <NuxtLink to="enemies/Yorick">Yorick</NuxtLink>. <NuxtLink to="enemies/Cloaked-Knight">Cloaked Knight</NuxtLink> na torre mais alta de <NuxtLink to="maps/Clock-Tower">Clock Tower</NuxtLink> (A torre do relógio que se pode ver em <NuxtLink to="maps/Castle-Keep">Castle Keep</NuxtLink>). Obs.: Na versão americana só funciona no 2º Castelo. <NuxtLink to="enemies/Stone-Rose">Stone Rose</NuxtLink>, basta matar a primeira e a segunda e voltar até a primeira. <NuxtLink to="enemies/Dark-Octopus">Dark Octopus</NuxtLink>, se você destruir a parte de Up. Todos os inimigos na sala com <NuxtLink to="enemies/Venus-Weed">Venus Weed</NuxtLink> em Abandoned Mine.</li>
        <li><b>Inimigos que perseguem Alucard:</b> <NuxtLink to="enemies/Owl">Owl</NuxtLink> <NuxtLink to="enemies/Fire-Warg">Fire Warg</NuxtLink>, <NuxtLink to="enemies/Skull-Lord">Skull Lord</NuxtLink>, <NuxtLink to="enemies/Cloaked-Knight">Cloaked Knight</NuxtLink>, <NuxtLink to="enemies/Imp">Imp</NuxtLink> e <NuxtLink to="enemies/Salome">Salome</NuxtLink>. Após vê-los fuja para bem longe mas sem sair da sala.</li>
        <li><b>Inimigos não catalogados:</b> As caveiras que carregam o <NuxtLink to="enemies/Bone-Ark">Bone Ark</NuxtLink>, o flea man que controla o <NuxtLink to="enemies/Orobourous">Orobourous</NuxtLink>; os ovos e os filhotes que o <NuxtLink to="enemies/Hippogryph">Hippogryph</NuxtLink> gera; os crânios e os morcegos que <NuxtLink to="enemies/Olrox">Olrox</NuxtLink> invoca; as moscas e os "tapurus" de <NuxtLink to="enemies/Beezelbub">Beezelbub</NuxtLink>; os zumbis que caem do <NuxtLink to="enemies/Granfaloon">Granfaloon</NuxtLink>. O zumbi invocado por <NuxtLink to="enemies/Fake-Sypha">Fake Sypha</NuxtLink> quando você mata os outros dois chefes (O dano causado a este inimigo não é exibido). A esfera verde que controla <NuxtLink to="enemies/Richter-Belmont">Richter Belmont</NuxtLink>.</li>
        <li><b>Sub-enemies:</b> São inimigos que não aparecem na enemy list da livraria, mas têm nome prórpio. Sempre aparecem juntos a outros inimigos. <NuxtLink to="enemies/Bone-Pillar">Spiked Ball</NuxtLink>: Aparece aUp de um <NuxtLink to="enemies/Bone-Pillar">Bone Pillar</NuxtLink> na escadaria de Royal Chapel; dropa <Item item="Axe Lord armor"/> e <Item item="Iron Ball"/>. Ele é o monstro que dá mais <abbr title="Experience Points">EXP</abbr> no Primeiro Castelo. <NuxtLink to="enemies/Yorick">Skull</NuxtLink>: É a cabeça do <NuxtLink to="enemies/Yorick">Yorick</NuxtLink>; dropa <Item item="Turquoise"/> e <Item item="Monster vial 3"/>. <NuxtLink to="enemies/Spectral-Sword13">Poltergeist</NuxtLink>: Existem 15 tipos diferentes: Pick, War Hammer, Rapier, Broad Sword, Long Axe, Spear, Whip, Dark Blade, War Pick, Dagger, Battle Axe, Falchion, Morning Star, Sword e Arrow. Giram em torno da <NuxtLink to="enemies/Spectral-Sword13">Spectral Sword LV 13</NuxtLink> e dropam <Item item="Bwaka knife"/>. <NuxtLink to="enemies/Spectral-Sword15">Puppet Sword</NuxtLink>: São as espadas que giram em torno da <NuxtLink to="enemies/Spectral-Sword15">Spectral Sword LV 15</NuxtLink>. Tem dois tipos, grande e pequena, e dropam <Item item="Takemitsu"/>. <NuxtLink to="enemies/Spectral-Sword36">Spear</NuxtLink>: São as lanças que ficam em volta da <NuxtLink to="enemies/Spectral-Sword36">Spectral Sword LV 36</NuxtLink> e dropam <Item item="Javelin"/>. <NuxtLink to="enemies/Spectral-Sword36">Shield</NuxtLink>: São os escudos que protegem a <NuxtLink to="enemies/Spectral-Sword36">Spectral Sword LV 36</NuxtLink> e dropam <Item item="Knight Shield"/>.</li>
        <li><b>Já notaram o que o <NuxtLink to="enemies/Sword-Lord">Sword Lord</NuxtLink> usa na mão?</b> É uma <NuxtLink to="enemies/Spectral-Sword15">Puppet Sword</NuxtLink> longa. Sua descrição é: Cavaleiro armado com Great Sword.</li>
        <li><b>'Axe' e 'Dagger' ricocheteam:</b> Quando atingem inimigos armadurados.</li>
        <li><b>'Stop Watch' tem efeitos diferentes contra inimigos diferentes:</b> Dependendo do inimigo, pode paralizá-lo, deixar seus movimentos lentos ou não causar nenhum efeito. Também tem efeitos diferentes sobre projéteis. Em alguns inimigos, o 'Stop Watch' pode não surtir efeito, mas deixar seus projéteis lentos, por exemplo.</li>
        <li><b>Seqüência de raios:</b> Usando a Sub-Weapon 'Agunea', se você apertar e segurar <img src="/img/cima.gif" alt="Up"/> + <img src="/img/quadrado.gif" alt="Quadrado"/> ou <img src="/img/circulo.gif" alt="Círculo"/>, ela soltará vários raios consecutivos, consumindo 10 'Hearts' por raio.</li>
        <li><b>Seqüência de raios infinita:</b> Com o <Item item="Heart Refresh"/> equipado no <img src="/img/circulo.gif" alt="Círculo"/>, faça a dica anterior em um inimigo com bastante <abbr title="Health Points">HP</abbr>. No momento em que o raio o atingir, fuja ainda segurando <img src="/img/cima.gif" alt="Up"/> + <img src="/img/quadrado.gif" alt="Quadrado"/>. O raio continuará a disparar mesmo sem que você veja o inimigo. Quando seus corações forem acabando use o HR sem soltar os comandos.</li>
        <li><b>Se você usar o 'Teleport Pad' do cavalo por 1º:</b> Ele não te levará para lugar algum. (use DHR para entrar).</li>
        <li><b>O desenho dos 'Teleport Pads':</b> Eles têm o formato de uma fechadura e Alucard é a chave. Se um mortal comum usar o teletransporte, ele se espedaça. Um exemplo disso são os ossos que tem nessa sala. (é uma teoria. :P)</li>
        <li><b>Sobre a sala do <NuxtLink to="enemies/Doppleganger10">Doppleganger10</NuxtLink>:</b> O portal de onde ele vem tem um brilho idêntico ao dos Teleport Pads que, por sua vez, é formado por um disco com as cores do espectro de luz.</li>
        <li><b>As mortes do <NuxtLink to="enemies/Doppleganger10">Doppleganger10</NuxtLink>:</b> Mate-o usando algum elemental. Com Fogo, por exemplo, ele carrega as fagulhas de fogo para dentro do portal. Mas o efeito mais legal é matá-lo usando o Elemental 'Stone'. Mate-o usando este elemental e você verá um efeito de pedra bem legal. (Os efeitos são idênticos aos das mortes de Alucard.)</li>
        <li><b>Sobre a sala do chefe <NuxtLink to="enemies/Olrox">Olrox</NuxtLink>:</b> Se durante a batalha contra Olrox você não destruir nada, quando ele for para a segunda forma, tudo será destruído automaticamente.</li>
        <li><b>A mesa do <NuxtLink to="enemies/Olrox">Olrox</NuxtLink> possui um <abbr title="Health Points">HP</abbr> próprio:</b> ela não se destrói com apenas uma pancada. A maioria das pessoas não percebem isso por que chegam lá com força suficiente para quebrá-la. Para notar isso, use um <Item item="Karma Coin"/> (que absorve <abbr title="Health Points">HP</abbr>) e veja que ela leva umas 4 pancadas para ser destruída.</li>
        <li><b>Desfecho contra <NuxtLink to="enemies/Scylla-wyrm">Scylla wyrm</NuxtLink>:</b> Entre na sala, mas não avance para que as laterais não fechem. Então use magia de longo alcance ('Soul Steal', 'Tetra Spirit' ou 'Summon Spirit') ou um item tipo bomb. Ela morre antes de aparecer e sem que a sala se feche. (coitada.)</li>
        <li><b>A verdadeira forma de <NuxtLink to="enemies/Scylla">Scylla</NuxtLink>:</b> Na mitologia ela é completa, mas aqui não. Ela é só a mulher e as três cabeças de lobo. Os tentáculos são apenas figuras de cenário. Para notar isso, use um truque de sair dessa sala de modo que fique revezando entre essa sala e a sala onde se encontra a <Item item="Crystal cloak"/>.</li>
        <li><b>Saber qual das <NuxtLink to="enemies/Succubus">Succubus</NuxtLink> é a verdadeira:</b> Quando a <NuxtLink to="enemies/Succubus">Succubus</NuxtLink> se multiplica, a verdadeira não ataca.</li>
        <li><b>Ouvir o grito das vítimas de <NuxtLink to="enemies/Cerberos">Cerberos</NuxtLink>:</b> Entre na sala do chefe, mas não avance para que as portas não se fechem. Espere que a labareda de fogo toque o teto e saia. Se fizer correto você ouvirá um grito de mulher. Às vezes o grito é cortado, mas você pode tentar novamente alterando o tempo que sai da sala até que escute bem claramente.</li>
        <li><b>Som diferente no ataque de <NuxtLink to="enemies/Cerberos">Cerberos</NuxtLink>:</b> Faça com que ele jogue a rajada de fogo para Up. Para isso fique em uma plataforma mais alta do que o chefe. Assim que ele jogar a rajada de fogo para Up, pause o jogo e você ouvirá um som bem diferenciado. Com Select funciona, mas com Start é bem mais interessante.</li>
        <li><b><NuxtLink to="enemies/Beezelbub">Beezelbub</NuxtLink> tem 12 partes:</b> 2 pés, 2 pernas, 2 mãos, 2 braços, 2 ombros, cabeça e tórax, sendo o tórax o verdadeiro chefe.</li>
        <li><b>Grito estranho de <NuxtLink to="enemies/Shaft">Shaft</NuxtLink>:</b> No Segundo Castelo, na batalha contra <NuxtLink to="enemies/Shaft">Shaft</NuxtLink>, quando estiver faltando uma ou duas pancadas para que ele morra, use um <Item item="Library Card"/>. Equipe a <Item item="Axe Lord armor"/> para retomar os comandos e mate <NuxtLink to="enemies/Shaft">Shaft</NuxtLink> rapidamente. Aperte START para cancelar o diálogo de modo que a tela já esteja toda branca quando ele começar a Gritar. Você ouvirá um som inédito no jogo.</li>
        <li><b>O <abbr title="Health Points">HP</abbr> da esfera verde de <NuxtLink to="enemies/Shaft">Shaft</NuxtLink>:</b> o <abbr title="Health Points">HP</abbr> desse inimigo é definido por pancadas. Não importa sua força. Você tem que se acertar 10 pancadas nela para destruí-la.</li>
        <li><b>Alucard perde os movimentos quando entra em algum lugar apertado.</b> Richter não...</li>
        <li><b>Entrar em lugares apertados sem perder os comandos (1):</b> Encoste em algumas paredes que possuem uma brecha e faça: <img src="/img/baixo.gif" alt="Down"/> <img src="/img/frente.gif" alt="Right"/> <img src="/img/baixo.gif" alt="Down"/> <img src="/img/frente.gif" alt="Right"/> várias vezes em direção à brecha. Alucard irá entrar como se estivesse andando abaixado. Já dentro da brecha, dê vários toques no direcional para frente até que Alucard chegue até o limite da brecha. Esse tipo de brecha pode ser encontrada em Abadoned Mine. Mais especificamente na sala onde se pega a <Item item="Combat knife"/>.</li>
        <li><b>Entrar em lugares apertados sem perder os comandos (2):</b> Use o 'Dive kick' na diagonal, de modo que o Alucard caia abaixado e deslize para dentro do ou deDown do buraco. Quando já estiver dentro da brecha, dê vários toquinhos para frente para que o Alucard avance. (quase nunca é preciso dar esses toquinhos).</li>
        <li><b>Poses diferenciadas (e engraçadas) de Alucard:</b> Ao fazer a dica anterior você poderá conferir as diversas poses que Alucard possui. Poses essas que ele faz rapidamente quando vai se abaixar mais que são quase imperceptíveis porque ele as faz muito rapidamente.</li>
        <li><b>Poses estranhas de Alucard (2):</b> Em <NuxtLink to="maps/Long-Library">Long Library</NuxtLink>, na sala do Velho. Chegue bem próximo a ele, com cuidado para não ativar o menu de compras. Tenha um <Item item="Toadstool"/> na mão, pule bem alto e jogue-o. Ainda no ar, use o segundo pulo e o direcional para pegar o cogumelo bem alto. Você será jogado para frente e ativará o menu de compras antes de cair. Alucard ficará paralisado em pleno ar enquanto você usa o menu. Obs.: pode ser feito sem os dois pulos.</li>
        <li><b>Alucard equilibrando escudo na testa (1):</b> Quando você fizer a dica de entrar em lugares apertados sem perder os comandos, use um escudo para vê-lo na cabeça de Alucard. Se mesmo assim não conseguir, faça a dica aDown.</li>
        <li><b>Alucard equilibrando escudo na testa (2):</b> No Segundo Castelo, em Cave, após a sala do chefe, tem uma área que você vai subindo e encontrando vários morcegos. (onde o aliado Demon, aciona o Switch.) Na segunda fileira de morcegos tem uma escada quebrada. Encoste na parte que está quebrada. Se você segurar em direção à parede você cai. Então segure somente até onde der para ir sem cair. Dê um toque para Down e Alucard não se levantará. Agora basta segurar o escudo. Alucard fica abaixado mas o escudo fica como se ele estivesse em pé!</li>
        <li><b>Fireball saindo da testa de Alucard:</b> Equipado com , faça a o seguinte comando; .</li>
        <li><b>'Repeated Fist' abaixado:</b> Com <Item item="Fist of Tulkas"/>:, <img src="/img/tras.gif" alt="Left"/> <img src="/img/frente.gif" alt="Right"/> <img src="/img/baixo.gif" alt="Down"/> <img src="/img/quadrado.gif" alt="Quadrado"/> ou <img src="/img/circulo.gif" alt="Círculo"/>. Com <Item item="Iron Fist"/>: <img src="/img/baixo.gif" alt="Down"/> <img src="/img/frente.gif" alt="Right"/> <img src="/img/baixo.gif" alt="Down"/> <img src="/img/quadrado.gif" alt="Quadrado"/> ou <img src="/img/circulo.gif" alt="Círculo"/>. Fique segurando <img src="/img/baixo.gif" alt="Down"/> + ataque. Se soltar, o truque será desfeito.</li>
        <li><b>Descansar os ombros rapidamente:</b> Deixe Alucard em uma superfície inclinada. Nesse tipo de superfície ele fica com as pernas um pouco flexionadas, estando neste tipo de superfície dê um pulinho. Ao tocar o chão Alucard ficará na pose de descanso.</li>
        <li><b>Alucard se senta numa posição diferente:</b> Na cadeira que você se senta para se confessar (Isso significa que Alucard é religioso). Às vezes, se deixar Alucard sentado até o padre desaparecer, ele deixará um <Item item="Grape juice"/>.</li>
        <li><b>Transformação com Estilo:</b> Equipado com uma arma tipo fist, pule e, ainda no ar, faça <img src="/img/baixofrente.gif" alt="Diagonal inferior Right"/> + <img src="/img/quadrado.gif" alt="Quadrado"/> ou <img src="/img/circulo.gif" alt="Círculo"/> para desferir uma voadora e quando o Alucard virar as costas, faça a transformação. (Melhor com o Bat).</li>
        </ol>
      </main>
      <hr/>
      <Footer/>
    </div>
  </div>
</template>

<style scoped>
  li { margin-bottom: 15px; }
</style>

<script>
  export default {
    head() {
      return {
        title: 'Oddities - Castlevania: Symphony of the Night'
      }
    }
  }
</script>