<template>
  <div>
    <Navbar/>
    <div class="container">
      <div class="breadcrumb">
        <NuxtLink to="/">GOD</NuxtLink> &raquo;
        <NuxtLink to="/">Castlevania: Symphony of the Night</NuxtLink> &raquo;
        Secrets
      </div>
      <Header/>
      <h2>Secrets &amp; Tips</h2>
      <hr/>
      <main>
        <p><a id="betterstart"></a><img src="~static/img/coffing.gif"/><b>Start with better stats:</b><br/>
        Alucard's attributes changes depending on how Richter destroyed <NuxtLink to="/enemies/Dracula">Dracula</NuxtLink> in <NuxtLink to="/videos/85HP">Final Stage Bloodlines</NuxtLink>.<br/>
        - If you beat him in under 1 minute of gameplay, Alucard earns +5 <abbr title="Health Points">HP</abbr>.<br/>
        - If you beat him without getting damaged, Alucard earns +5 <abbr title="Health Points">HP</abbr>.<br/>
        - If you beat him without getting any 'Sub-Weapon', Alucard earns <abbr title="Health Points">HP</abbr> and +5 <abbr title="Luck">LCK</abbr>.<br/>
        - If you beat him with 'Holy Water' as 'Sub-Weapon', Alucard earns +5 <abbr title="Magic Points">MP</abbr> e +5 'Hearts'.<br/>
        - If you beat him with 'Holy Cross' as 'Sub-Weapon', Alucard earns +10 <abbr title="Magic Points">MP</abbr> e +5 'Hearts'.<br/>
        - If you get more than 40 'Hearts', Alucard starts with a <Item item="Neutron bomb"/>.<br/>
        - If Richter is beaten by <NuxtLink to="/enemies/Dracula">Dracula</NuxtLink>, Maria comes to make him invencible and Alucard starts with a <Item item="Potion"/>.<br/>
        - If you beat him with 0 'Hearts' left, Alucard starts with a <Item item="Heart Refresh"/>.<br/>
        Combine these ways to destroy "Count Vlad Tepes, the Impaler" to begin the game more powerful.</p>
        <p><a id="outerwall"></a><img src="~assets/items/jewel-knuckles.gif"/> <b><NuxtLink to="/items/Jewel-knuckles">Jewel knuckles</NuxtLink> and <NuxtLink to="/items/Mirror-cuirass">Mirror cuirass</NuxtLink>:</b><br/>
        Once you reach <NuxtLink to="/maps/Outer-Wall">Outer Wall</NuxtLink>, go down to the place where a <NuxtLink to="/enemies/Sword-Lord">Sword Lord</NuxtLink> guards a room. Kill him, enter the room, break the wall, grab the <Item item="Pot roast"/> and stay quiet in the broken wall for nearly 30 seconds. Alucard will get down in a floating stone to the inferior room where the <Item item="Jewel knuckles"/> and the <Item item="Mirror cuirass"/> can be found. Otherwise they could only be got using the <Item item="Form of Mist"/> when these items won't be as useful as if gotten at this time.</p>
        <p><a id="shortcut"></a><img src="~static/img/thu.gif"/> <b>Special shortcut:</b><br/>
        After getting to <NuxtLink to="/maps/Long-Library">Long Library</NuxtLink> and having the <Item item="Jewel of Open"/>, you don't need to go all the way back to the blue door. You can continue straight to <NuxtLink to="/maps/Clock-Tower">Clock Tower</NuxtLink>!! Get the <Item item="Soul of Wolf"/> on the way. If not known, you would go back when you face the falling bridges, but you can pass by as wolf. Just run and jump without touch the bridges. There are also two united bridges up ahead. Do the same thing to step on it's intersection and jump again and they won't fall. If the wolf steps on the wrong spot the bridges will fall, but you'll have time to jump again to "firm ground". If a bridge fall and the passage becomes a impossible task, go pass through the <abbr title="CD Load Room">CDLR</abbr>, and the bridges will reappear. Try again and when you get to the clock tower itself, go up to find a higher platform which can't be reached by a normal jump. Again, if not known, you would go back, but you can pass by put wolf in action again! Run as wolf and jump when steping on the stairs and the jump will be much higher. That way you can reach the platform and continue your way. Plus!!! When you were passing by, did you saw some "precious items" on top of some collums? You can get them!! Arriving at the top of the tower, go out by the right. Out there you'll find some S-T-A-I-R-S... Got it? Run and jump as wolf and it may fall on top of the treasures. Then you'll have to make the bridges reappear to continue your way through <NuxtLink to="/maps/Clock-Tower">Clock Tower</NuxtLink> fighting more powerful enemies, getting more <abbr title="Experience Points">EXP</abbr> and getting better items than if you were following the common way.</p>
        <a id="click"></a><p><img src="~assets/items/star-flail.gif"/> <b><NuxtLink to="/maps/Clock-Tower">Clock Tower</NuxtLink> Secret:</b><br/>
        This one is well known but I have to mention it... There are some gears on the <NuxtLink to="/maps/Clock-Tower">Clock Tower</NuxtLink>'s wall. Hit them until them sounds as "click". When this is done on all gears, the room on the base of the left tower will open. There you will find a <Item item="Star flail"/>, a <Item item="Steel helm"/> and a <Item item="Gold plate"/> which can be got early if you made the above.</p>
        <p><a id="alucart"></a><img src="~assets/items/alucart-mail.gif"/> <b>Alucart Status:</b><br/>
        After getting the <Item item="Soul of Bat"/>, go to the clock room and go up as bat by the central ceiling passage. Up there you'll find the <Item item="Gravity Boots"/> and the 'Alucart' set which isn't very useful if used separately, but is equipped all together you'll get the "Alucart Status" and receive, +30 <abbr title="Luck">LCK</abbr>!</p>
        <p><a id="librarian"></a><img src="~static/img/super.gif"/> <b>Old man's secret items:</b><br/>
        After getting the <Item item="Gravity Boots"/> (mentioned above), go to <NuxtLink to="/maps/Long-Library">Long Library</NuxtLink>, at the room under the Librarian Shop where you find a <Item item="Bronze cuirass"/> which apears to have fallen from a dute right under the old man's chair. Aparently, it's used to the old one make something important without having to leaving the shop. As greedy players we are, we won't be satisfied by a single little bronze mail a old man left behind. So, let's disturb his peace and he would left us better items. Use your new ability: <img src="~static/img/baixo.gif" alt="Down"/> <img src="~static/img/cima.gif" alt="Up"/> + <img src="~static/img/x.gif"/> by the dute, taking the librarian on your way. At the first time you will get a 'Life Max Up'. Continue playing and taking him off ground each time. If you get +/- 15 'Hyper Jumps' without fall to the floor, he will drop a <Item item="Ring of Arcana"/>. With +/- 23 not falling, you will get the <Item item="Dracula tunic"/> and when it counts 60 jumps, falling or not, an <Item item="Axe Lord armor"/> will be dropped.</p>
        <p><a id="money"></a><img src="~assets/items/diamond.gif"/> <b>255 jewels:</b><br/>
        After getting the 'Sword Familiar', go to the Librarian shop, make the 'Sword Brothers' spell and talk to him. Now it will be possible to enter the inventory while talking to the old man. Select 'Sell Gem', and max the number of the gem you want to multiply. Open yor inventory and equip the gem which the number you maxed before. Exit the inventory and sell those gems. When you look again your inventory, you'll have 255 of the jewel you sold. Then you can resell them and get milionary!! You can also have 255 of all jewel kinds.</p>
        <p><a id="fairysgift"></a><img src="~static/img/fairy.gif"/> <b>Fairy's Gift:</b><br/>
        This tech were found by my "castlevanian pal" <b>Paulo1179</b> and can give you 255 of the items the 'Faerie Familiar' can use on you (<Item item="Potion"/>, <Item item="High potion"/>, <Item item="Antivenom"/>, <Item item="Uncurse"/>, <Item item="Resist fire"/>, <Item item="Resist ice"/>, <Item item="Resist thunder"/>, <Item item="Resist stone"/>, <Item item="Resist dark"/> and <Item item="Resist holy"/>). To do it you'll need to have only one of the item you want to multiply and make the faerie use it on you. At the moment the faerie spins to throw the item, enter the inventory and equip it. The single one left will go to your hand and there will not be any for the faerie to use. close the inventory. The faerie will use the item anyway and it's number will go from 0 to 255 in stock!</p>
        <p><a id="entrance"></a><img src="~assets/items/jewel-sword.gif"/> <b>Secret Passage at <NuxtLink to="/maps/Entrance">Entrance</NuxtLink>:</b><br/>
        After getting the <Item item="Soul of Wolf"/> and the <Item item="Soul of Bat"/>, go to <NuxtLink to="/maps/Entrance">Entrance</NuxtLink> where you find a big rock in the middle of te room. You can break both sides of this rock at the beggining of the game to form something like a tunnel where you find a <Item item="Pot roast"/>. Make a transformation (bat or wolf), enter the "tunnel", make the other transformation and exit by the other side. if correctly done, a passage will open at the inferior left side of the room where you find a <Item item="Jewel sword"/> and a <Item item="Life apple"/>. The same passage can be opened in the Reverse Castle, there you find the <Item item="Beryl circlet"/>.</p>
        <p><a id="gooutcastle"></a><img src="~static/img/castle.gif"/> <b>Raise game percentage:</b><br/>
        After leveling 'Sword Familiar' to Level 90 (when it's blade become blue), go to <NuxtLink to="/maps/Royal-Chapel">Royal Chapel</NuxtLink>, at the base of the tower with the confession room. Make the 'Sword Brothers' spell, transform into bat and pass through the left door. You won't enter the other room, You will go outside the castle and open new white rooms on the map. You can open even more white rooms on the map using <Item item="Heart Refresh"/> at the edge of the screens outside castle. You also can exit castle anywhere using the <abbr title="Double Heart Refresh">DHR</abbr> glitch. To do it, equip <Item item="Heart Refresh"/>es on both hands, along with a <Item item="Duplicator"/>, jump or make a 'Dive Kick' in direction to any screen edge where you enter a new room, use the first <abbr title="Heart Refresh">HR</abbr> and hold the other button to use the second immediately at the end of the first one. Keep the <abbr title="Heart Refresh">HR</abbr> combo and at each time the item is used, Alucard will move a few pixels but the screen will stay at the same place. When Alucard reaches the end of the screen, the game will ignore any wall outside, so you can pass by them and slowly (and with a bit of patience) Alucard will opening new white rooms on the map. Making a big <abbr title="Heart Refresh">HR</abbr> combo will open a collumn of white rooms. This tech is called 'Sink Tech' or 'White Waterfall' and is considered as cheating by "glitchers". The 'Shield Combos' have the same effect as the <abbr title="Heart Refresh">HR</abbr> but has the limitation you can't use one after another without time span. Sometimes when you make this glitch at change screens Alucard may get stuck under the ground. The way to get out this situation is to use the 'Air Back' tech which consists on using a <Item item="Library card"/> in mid-air. To do this, equip a two-handed sword like <Item item="Flamberge"/>, <Item item="Zwei hander"/>, or <Item item="Obsidian sword"/> and make it's thrusting especial move (<img src="~static/img/tras.gif" alt="Left"/> <img src="~static/img/frente.gif" alt="Right"/> + <img src="~static/img/quadrado.gif" alt="Square"/> or <img src="~static/img/circulo.gif" alt="Circle"/>). During the move, equip and use a <Item item="Library card"/>. This tech works anywhere, but it's harder to do at someplaces under the ground. The easier way is to try it after change back from wolf form.</p>
        <p><a id="richter"></a><img src="~static/img/ricaluria.gif"/> <b>Play as Richter Belmont:</b><br/>
        After beating the game once, start a new game with "RICHTER" as name. You will appear at the castle entrance as Richter Belmont.</p>
        <p><a id="slide"></a><img src="~static/img/thu.gif"/> <b>Go out castle as Richter Belmont:</b><br/>
        Start a new game as Richter doing the above and, imediately when the game start, do a slide (<img src="~static/img/baixo.gif" alt="Down"/> + <img src="~static/img/x.gif" alt="X"/>) to the left. You may get out the castle before the door closes. Then you can walk in the forest but you won't be able to enter the castle again. If you go left to the end of the screen, Richter will come as Alucard does when he appears in the game for the first time and when Richter reaches the castle's bridge he will jump and shout "Holy Cross!",  but he'll be struck at the door. Then you have no choice but reset the game.</p>
        <p><a id="trapdoor"></a><img src="~static/img/blood.gif"/> <b>Secret Save Point at the unfinished passage to 'Underground Garden':</b><br/>
        To access this save point as Richter, imediately at the game start, run to the left and the door at the castle's gate may push Richter to the trapdoor making him to be sruck. Make some tapes to the right and Richter will fall in the unfinished passage to 'Underground Garden' which should be another area of the game but wasn't finished in time for the Playstation version, however it can be played on Sega Saturn. In this passage, you can find only a Save Point. As Richter Belmont, you can only enter the passage at the beggining of the game. If you didn't at this time, you won't be able to do it after. As Alucard, you can enter using <abbr title="Double Heart Refresh">DHR</abbr> glitch, already mentioned. In the corridor after the start Castle's room where the trapdoor is, jump to the change screens between the two rooms and start the <abbr title="Heart Refresh">HR</abbr> combo until Alucard position get under the ground. Then, just go left and you'll fall in there. To get out, just push the trapdoor up...</p>
        <p><a id="axearmor"></a><img src="~assets/items/axe-lord-armor.gif"/> <b>Start with an Axe Lord Armor:</b><br/>
        After beating the game once, start a new game with "AXEARMOR" as name. Alucard will have an <Item item="Axe Lord armor"/> in the inventory.</p>
        <p><a id="luck"></a><img src="~static/img/skull.gif"/> <b>Start with 99 LCK:</b><br/>
        Much people think that you it's necessary to beat the game to be able to make this secret work, but you can make it in the first play. Just start a new game with "X-X!V''Q" as name and Alucard will have 99 <abbr title="Luck">LCK</abbr> and a <Item item="Lapis lazuli"/>, however will also start with <abbr title="Health Points">HP</abbr>, 1 <abbr title="Magic Points">MP</abbr>, 1 <abbr title="Strenght">STR</abbr>, 0 <abbr title="Constitution">CON</abbr>, 0 <abbr title="Intelligence">INT</abbr> and 5 'Hearts'.</p>
        <p><a id="death"></a><img src="~static/img/skelly.gif"/> <b>Deceiving Death:</b><br/>
        Start a new game with "X-X!V''Q" as name to start with 99 <abbr title="Luck">LCK</abbr> and low defense as mentioned above. when you reach the room before the one you find Death, don kill the third <NuxtLink to="/enemies/Warg">Warg</NuxtLink>. Get near it and it wlll start to hoar. When it attacks you, jump over it. You can grab a <Item item="Turkey"/> breaking the ledge at the entrance of "Death's room". Unequip you gear till you have less than 8 <abbr title="Defense">DEF</abbr> then simply jump on the warg's mouth and you'll be set flying till you find any wall to stop you, in that case, it have to be the wall after the death's room. If you don't want to get the <Item item="Turkey"/>, you can use the first <NuxtLink to="/enemies/Warg">Warg</NuxtLink>, but don't jump on it, only touch it. After you pass by the death's room flying, the game will get bugged. You won't be able to open the inventory until you pass by a <abbr title="CD Load Room">CDLR</abbr>. Don't try to get the 'Heart Max Up' falling in the broken bridge on top of the buggy room or a uglier bug will take place: you'll be floating above the Death's room and will have to reset the game. Pass by a <abbr title="CD Load Room">CDLR</abbr> to "debug", get back to grab the item.</p>
      </main>
      <hr/>
      <Footer/>
    </div>
  </div>
</template>

<script>
  export default {}
</script>