<template>
  <div class="wrapper">
    <Navbar/>
    <div class="container">
      <div class="breadcrumb">
        <NuxtLink to="/">GOD</NuxtLink> &raquo;
        <NuxtLink to="/">Castlevania: Symphony of the Night</NuxtLink> &raquo;
        <NuxtLink to="/maps">Maps</NuxtLink> &raquo;
        Marble Gallery
      </div>
      <Header/>
      <h2>Marble Gallery</h2>
      <hr/>
      <main>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/30,74.gif"/><img src="~static/img/maps/31,74.gif"/><img src="~static/img/maps/32,74.gif"/><img src="~static/img/maps/33,74.gif"/><img src="~static/img/maps/34,74.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/32,75.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/37,75.gif"/><img src="~static/img/maps/38,75.gif"/><img src="~static/img/maps/39,75.gif"/><img src="~static/img/maps/40,75.gif"/><img src="~static/img/maps/41,75.gif"/><img src="~static/img/maps/42,75.gif"/><img src="~static/img/maps/43,75.gif"/><img src="~static/img/maps/44,75.gif"/><img src="~static/img/maps/45,75.gif"/><img src="~static/img/maps/46,75.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/rload.gif"/><img src="~static/img/maps/31,76.gif"/><img src="~static/img/maps/32,76.gif"/><img src="~static/img/maps/33,76.gif"/><img src="~static/img/maps/34,76.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/37,76.gif"/><img src="~static/img/maps/38,76.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/40,76.gif"/><img src="~static/img/maps/41,76.gif"/><img src="~static/img/maps/42,76.gif"/><img src="~static/img/maps/43,76.gif"/><img src="~static/img/maps/44,76.gif"/><img src="~static/img/maps/45,76.gif"/><img src="~static/img/maps/46,76.gif"/><img src="~static/img/maps/47,76.gif"/><img src="~static/img/maps/48,76.gif"/><img src="~static/img/maps/49,76.gif"/><img src="~static/img/maps/50,76.gif"/><img src="~static/img/maps/51,76.gif"/><img src="~static/img/maps/52,76.gif"/><img src="~static/img/maps/53,76.gif"/><img src="~static/img/maps/54,76.gif"/><img src="~static/img/maps/55,76.gif"/><img src="~static/img/maps/56,76.gif"/><img src="~static/img/maps/57,76.gif"/><img src="~static/img/maps/58,76.gif"/><img src="~static/img/maps/59,76.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/rload.gif"/><img src="~static/img/maps/22,77.gif"/><img src="~static/img/maps/23,77.gif"/><img src="~static/img/maps/24,77.gif"/><img src="~static/img/maps/25,77.gif"/><img src="~static/img/maps/26,77.gif"/><img src="~static/img/maps/27,77.gif"/><img src="~static/img/maps/28,77.gif"/><img src="~static/img/maps/29,77.gif"/><img src="~static/img/maps/30,77.gif"/><img src="~static/img/maps/31,77.gif"/><img src="~static/img/maps/32,77.gif"/><img src="~static/img/maps/33,77.gif"/><img src="~static/img/maps/34,77.gif"/><img src="~static/img/maps/35,77.gif"/><img src="~static/img/maps/36,77.gif"/><img src="~static/img/maps/37,77.gif"/><img src="~static/img/maps/38,77.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/rload.gif"/><img src="~static/img/maps/41,77.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/44,77.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/27,78.gif"/><img src="~static/img/maps/28,78.gif"/><img src="~static/img/maps/lsave.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/rsave.gif"/><img src="~static/img/maps/32,78.gif"/><img src="~static/img/maps/33,78.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/25,79.gif"/><img src="~static/img/maps/26,79.gif"/><img src="~static/img/maps/27,79.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/32,79.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/25,80.gif"/><img src="~static/img/maps/26,80.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/32,80.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/25,81.gif"/><img src="~static/img/maps/26,81.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/31,81.gif"/><img src="~static/img/maps/32,81.gif"/><img src="~static/img/maps/33,81.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/25,82.gif"/><img src="~static/img/maps/26,82.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/31,82.gif"/><img src="~static/img/maps/32,82.gif"/><img src="~static/img/maps/33,82.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/25,83.gif"/><img src="~static/img/maps/26,83.gif"/><img src="~static/img/maps/27,83.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/31,83.gif"/><img src="~static/img/maps/32,83.gif"/><img src="~static/img/maps/33,83.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/27,84.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/21,85.gif"/><img src="~static/img/maps/22,85.gif"/><img src="~static/img/maps/23,85.gif"/><img src="~static/img/maps/24,85.gif"/><img src="~static/img/maps/25,85.gif"/><img src="~static/img/maps/26,85.gif"/><img src="~static/img/maps/27,85.gif"/><br/>
        <img src="~static/img/maps/blank.gif"/><img src="~static/img/maps/21,86.gif"/><img src="~static/img/maps/22,86.gif"/><img src="~static/img/maps/23,86.gif"/><img src="~static/img/maps/24,86.gif"/><img src="~static/img/maps/25,86.gif"/><img src="~static/img/maps/26,86.gif"/><br/>
        <img src="~static/img/maps/rload.gif"/><img src="~static/img/maps/21,87.gif"/><img src="~static/img/maps/22,87.gif"/><img src="~static/img/maps/23,87.gif"/><img src="~static/img/maps/24,87.gif"/><img src="~static/img/maps/25,87.gif"/><img src="~static/img/maps/26,87.gif"/>
      </main>
      <hr/>
      <Footer/>
    </div>
  </div>
</template>

<script>
  export default {}
</script>

<style scoped>
  img {
    vertical-align: bottom;
  }
  .wrapper, .container {
    width: max-content;
  }
</style>